### PR TITLE
Bump version to 1.1.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Made a mistake to fix version only pom.xml on root directory.

For preventing same mistake again, I created this pull request instead of commit and push directly.

@ptgoetz @harshach Could you take a look? I did find & replace "1.0.1-SNAPSHOT" to "1.1.0-SNAPSHOT" against whole directory so I guess I don't miss a spot, but would like to confirm.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by dossett** [comment]
In other projects I use `mvn versions:set` and `mvn versions:commit` to make changes like this to every pom file.  Simple local experiment looks for the Storm repo.  I'll confirm that and maybe add a note to the developer documentation if that would be helpful.

**Comment by HeartSaVioR** [comment]
Oh thanks @dossett that is great tip for me! If it works like a charm, I believe adding a note is helpful for many people.

**Comment by kishorvpatil** [comment]
+1

**Comment by ptgoetz** [comment]
+1

**Comment by ptgoetz** [comment]
Thanks @HeartSaVioR. Merged.

**Pull request merged**
