### PR TITLE
[Storm 1715] Jedis Default Host

### PR DESCRIPTION
**Pull request by darionyaphet**
Useing Jedis Protocol.DEFAULT_HOST to replace DEFAULT_HOST :)

[STORM-1715](https://issues.apache.org/jira/browse/STORM-1715)

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@darionyaphet 
+1
Could you rebase and squash your commits into one?

**Comment by darionyaphet** [comment]
@HeartSaVioR It's seems I make a mistake.  `pull request #1` is a merge request I commit long time ago. I couldn't checkout it . Maybe I should remove this repo and recommit this PR ?

**Comment by HeartSaVioR** [comment]
@darionyaphet Yeah, if `git rebase master` doesn't work, you may want to create a new branch and try to cherry pick b3c0e2d.

**Comment by darionyaphet** [comment]
@HeartSaVioR thanks for you help . I will close this pull request and reopen another . 👍

**Pull request closed without merging**
