### PR TITLE
STORM-1196: Upgrade to thrift 0.9.3

### PR DESCRIPTION
**Pull request by knusbaum**

### CODE REVIEW

**Comment by knusbaum** [comment]
Travis failure appears unrelated.

**Comment by revans2** [comment]
+1 looks good to me.

**Comment by kishorvpatil** [comment]
+1. This would simplify a lot of pull requests

**Comment by HeartSaVioR** [comment]
+1, great for removing date. It also removes unneeded ';' from python generated codes which looks better.

**Pull request merged**
