### PR TITLE
[STORM-1400] adds null check before trying to remove connections

### PR DESCRIPTION
**Pull request by d2r**

### CODE REVIEW

**Comment by knusbaum** [comment]
+1

**Comment by zhuoliu** [comment]
+1

**Comment by d2r** [comment]
Both test failures were expected, and will be fixed with #950

**Comment by HeartSaVioR** [comment]
+1 Great finding.

**Comment by d2r** [comment]
Close/Open to start new build.

**Comment by d2r** [comment]
multi-lang test crashed for jdk7, which seems unrelated.  All other tests passed.

**Comment by d2r** [comment]
Created [STORM-1401](https://issues.apache.org/jira/browse/STORM-1401) for the test error.

**Comment by jerrypeng** [comment]
+1

**Pull request merged**
