### PR TITLE
STORM-691 Add basic lookup / persist bolts

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* Add Basic lookup / persist Bolts
  * support data types : string, list, hash, set, sorted set, hyperloglog
* rename util package to common

 Type | Read | Write
-------- | ------- | ------
STRING | GET (key) | SET (key, value)
HASH | HGET (key, field) | HSET (key, field, value)
LIST | LPOP (key) | RPUSH (key, value)
SET | SCARD (key) | SADD (key, member)
SORTED SET | ZSCORE (key, member) | ZADD (key, score, member)
HLL (HyperLogLog) | PFCOUNT (key) | PFADD (key, element)

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
When this PR will be merged to master, we can apply RedisDataTypeDescription to Trident in order to support more data types.

**Comment by HeartSaVioR** [comment]
@revans2 Could you take a look?

**Comment by revans2** [comment]
The code looks fine to me.  My only comment is that it would be nice to have a default in most of the case statements, mostly as defensive programming so if something gets off we wold get an error instead of falling through and ignoring the tuples.

**Comment by HeartSaVioR** [comment]
@revans2 Thanks for reviewing! It's updated. Could you please check again?

**Comment by ptgoetz** [comment]
+1

**Comment by HeartSaVioR** [comment]
@revans2 Could you take a look again?

**Comment by revans2** [comment]
+1, again sorry about this taking so long, I'll merge it in.

**Pull request merged**
