### PR TITLE
STORM-1395: move JUnit dependency to top-level pom

### PR DESCRIPTION
**Pull request by ptgoetz**
https://issues.apache.org/jira/browse/STORM-1395

### CODE REVIEW

**Comment by d2r** [comment]
Looks good to me +1

**Comment by HeartSaVioR** [comment]
+1

**Comment by unsleepy22** [comment]
+1

**Comment by revans2** [comment]
+1

**Comment by knusbaum** [comment]
24-hours is up. I'm going to merge this.

**Pull request merged**
