### PR TITLE
STORM-724 [storm-redis] Document RedisStoreBolt and RedisLookupBolt which is missed

### PR DESCRIPTION
**Pull request by HeartSaVioR**
I've missed it from STORM-691, sorry!

### CODE REVIEW

**Comment by dashengju** [comment]
+1

**Comment by dashengju** [comment]
@revans2  I think we should merge this PR to all branches. please help to review.

**Comment by HeartSaVioR** [comment]
@dashengju Basic Bolts are planned to release 0.11.0. You can find it from CHANGES.md.
But we can also discuss it to include Basic Bolts to 0.10.0, and actually I'd like to.

**Comment by harshach** [comment]
@HeartSaVioR it looks like PR removed code from a test topology any reason for this?

**Comment by HeartSaVioR** [comment]
@harshach It became unused from #451 but I missed to remove it. ;)

**Comment by harshach** [comment]
@HeartSaVioR  Thanks for the details. +1

**Comment by HeartSaVioR** [comment]
@harshach Thanks for reviewing. :)

**Pull request merged**
