### PR TITLE
storm-starter: Guide JDK version to later than 7

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Apache Storm doesn't support JDK 6 from 0.10.0 and later.

### CODE REVIEW

**Comment by ptgoetz** [comment]
+1

**Comment by knusbaum** [comment]
Do we want to mention that 8 is equally supported? Maybe say 'JDK 7 and above' or something?

**Comment by HeartSaVioR** [comment]
@knusbaum I agree. Updated.

**Comment by haohui** [comment]
+1

**Comment by knusbaum** [comment]
+1

**Pull request merged**
