### PR TITLE
[STORM-2815] UI HTTP server should return 403 if the user is unauthorized

### PR DESCRIPTION
**Pull request by Ethanlm**
Storm UI HTTP server returns 500 for all kind of exceptions. 
It should return 403 if it's an AuthorizationException.

### CODE REVIEW

**Comment by Ethanlm** [comment]
A test:

Original:
```
C02T72WRG8WL-lm:~ ethanli$ curl -i  --negotiate -u:anyUser  -b ~/cookiejar.txt -c ~/cookiejar.txt   http://persistmist.corp.ne1.yahoo.com:8080/api/v1/cluster/summary
HTTP/1.1 500 Server Error
Date: Tue, 14 Nov 2017 21:42:44 GMT
Cache-Control: no-cache, no-store
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Access-Controler-Allow-Origin, X-Requested-By, X-Csrf-Token, Authorization, X-Requested-With
Content-Type: application/json;charset=utf-8
Content-Length: 4908
Server: Jetty(9.4.7.v20170914)

{"error":"Internal Server Error","errorMessage":"AuthorizationException(msg:UI request 'getClusterInfo' for 'ethan@ETHAN.STORM.NET' user is not authorized).....(omitted)
```



With this patch:
```
C02T72WRG8WL-lm:~ ethanli$ curl -i  --negotiate -u:anyUser  -b ~/cookiejar.txt -c ~/cookiejar.txt   http://persistmist.corp.ne1.yahoo.com:8080/api/v1/cluster/summary
HTTP/1.1 403 Forbidden
Date: Tue, 14 Nov 2017 21:39:21 GMT
Cache-Control: no-cache, no-store
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Access-Controler-Allow-Origin, X-Requested-By, X-Csrf-Token, Authorization, X-Requested-With
Content-Type: application/json;charset=utf-8
Content-Length: 4908
Server: Jetty(9.4.7.v20170914)

{"error":"Internal Server Error","errorMessage":"AuthorizationException(msg:UI request 'getClusterInfo' for 'ethan@ETHAN.STORM.NET' user is not authorized).....(omitted)
```

**Comment by HeartSaVioR** [comment]
I also would like to get it in 1.x version lines as well. (1.x, 1.1.x)

**Comment by Ethanlm** [comment]
With the last commit (about `exceptionToJson`)
```
C02T72WRG8WL-lm:~ ethanli$ curl -i  --negotiate -u:anyUser  -b ~/cookiejar.txt -c ~/cookiejar.txt   http://persistmist.corp.ne1.yahoo.com:8080/api/v1/cluster/summary
HTTP/1.1 403 Forbidden
Date: Wed, 15 Nov 2017 15:16:29 GMT
Cache-Control: no-cache, no-store
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Access-Controler-Allow-Origin, X-Requested-By, X-Csrf-Token, Authorization, X-Requested-With
Content-Type: application/json;charset=utf-8
Content-Length: 4900
Server: Jetty(9.4.7.v20170914)

{"error":"403 Forbidden","errorMessage":"AuthorizationException(msg:UI request 'getClusterInfo' for 'ethan@ETHAN.STORM.NET' user is not authorized)
```

Thanks @HeartSaVioR for pointing it out

**Comment by Ethanlm** [comment]
I will file another PR for 1.x-branch after this patch gets merged in.

**Comment by HeartSaVioR** [comment]
@Ethanlm Thanks I merged this into master. Please let me know when you craft another PR for 1.x. Thanks in advance.

**Pull request closed without merging**
