### PR TITLE
[STORM-591] exclude logback.xml from jar

### PR DESCRIPTION
**Pull request by Lewuathe**
`logback.xml` should not be included jar file because it will override other configuration who use your jar. 
To avoid this case exclude `logback.xml` file from storm-core jar file.

### CODE REVIEW

**Comment by Lewuathe** [comment]
I found logback searches logback-test.xml first and at eventually I renamed xml file and excluded it when it is packaged. I think it is a better way because it can show this xml file is only used for test explicitly.

**Comment by d2r** [comment]
I like the change, but I think now we need to update for log4j2. @Lewuathe would you be willing to convert the syntax for log4j2?

**Comment by d2r** [comment]
@Lewuathe ,
The file has been converted to log4j2.xml, so all we need to do get your branch upmerged.  Would you take a look?

**Comment by knusbaum** [comment]
Closing this. Feel free to reopen with updates.

**Pull request closed without merging**
