### PR TITLE
Kafka spout failure config

### PR DESCRIPTION
**Pull request by ogorun**
This pull request offers plugable MessageFailureHandler for failed message.

Solution structure. 
PartitionManger uses instance of class that implements IMassageFailureHandler interface for failure handling.
For instance creation it uses factory object stored in MessageFailureHandlerFactoryRepository.
  
This request provides 2 implementations for IMessageFailureHanlder: 
- DefaultFailureHandler repeats current KafkaSpout behaviour
- ConfigurableRetriesFailureHandler enables possibility to configure number of retires per message.

There is also one implementation of IMessageFailureHandlerFactory: MessageFailureHandlerDefaultFactory that provides possibility to create either  DefaultFailureHandler or ConfigurableRetriesFailureHandler.

By default, if nobody filled MessageFailureHandlerFactoryRepository, it returns MessageFailureHandlerDefaultFactory object that creates DefaultFailureHandler object.

### CODE REVIEW

**Comment by harshach** [comment]
@ogorun There is work in progress to refactor kafka code at STORM-631. Can you please add your requirements/issue there so that we can fix it as part of STORM-631. Thanks.

**Comment by ogorun** [comment]
Thank you for feedback. I'll look at it

**Comment by wurstmeister** [comment]
Hi, 

Thanks for pointing out your PR. This looks like it is fairly similar to https://github.com/apache/storm/pull/254, which has been merged recently.

**Comment by ogorun** [comment]
@wurstmeister ,
Thank you for pointing me to https://github.com/apache/storm/pull/254  .
It is definitely progress in direction of failure handling functionality encapsulation. But there are two points that I'would solve another way. 

* I feel plugable failure handler (with reasonable default) is needed. For example, I'd rather have one point in topology (spout) that decides when to stop  reprocessing the same message (for example, after configurable number of retries) than checking all possible exceptions are handled properly in every bolt.

* fail() event is divided into two parts: one part is handled in PartitionManager class and another one in FailedMsgRetryManager. I don't see cause for such division.

**Comment by d2r** [comment]
Hi @ogorun, Could you file a JIRA issue for this pull request [here](https://issues.apache.org/jira/browse/STORM/)?

**Comment by ogorun** [comment]
Hi @d2r ,

Is it better to open separate JIRA issue or this pull request is considered as part of subjects discussed in  STORM-650?

**Comment by d2r** [comment]
> Is it better to open separate JIRA issue or this pull request is considered as part of subjects discussed in STORM-650?

@ogorun  I am sorry I did not see the notification for you comment earlier.  Yes, I think the place to discuss this is STORM-650.  We might ask on STORM-650 whether we should add a new JIRA Issue for this to the STORM-650 epic.  We might ask on STORM-650 whether we should add a new JIRA Issue for this to the STORM-650 epic.  So far, I am not sure this specific issue is addressed in STORM-650, and it seems some kafka API changes are coming as well.

**Comment by d2r** [comment]
@ogorun, how should we move forward with this work?  Has this issue been resolved as part of STORM-650, or does it still need to be addressed?

**Comment by knusbaum** [comment]
Closing. Feel free to reopen with updates.

**Pull request closed without merging**
