### PR TITLE
MINOR: Remove unused dev-tools/test-ns.py

### PR DESCRIPTION
**Pull request by krichter722**
… order to avoid unnecessary clutter in the logs

### CODE REVIEW

**Comment by srdo** [comment]
+1 for the change, but I'm not sure what this file is for. It looks like it used to be for running tests in storm-core when it was still mainly Clojure code. I think this file is here because running tests in a specific namespace was a bit involved. Since we've switched to Java, this file seems a little redundant.

There doesn't appear to be any references to test-ns from build scripts, and I don't think that anyone is still using it(?). Maybe we should just delete it.

**Comment by krichter722** [comment]
I have to admit that it's an old branch and that I just rebased it and opened the PR. I didn't check whether it was still used. I could reuse this PR to delete the file. What do you think?

**Comment by srdo** [comment]
Deleting the file would be fine by me.

**Comment by srdo** [comment]
+1

**Comment by srdo** [comment]
Thanks @krichter722

**Pull request merged**
