### PR TITLE
Storm-818: storm-eventhubs configuration improvement and refactoring

### PR DESCRIPTION
**Pull request by shanyu**
In Storm-583 EventHubSpout and EventHubBolt implementation were added. During the review and licensing clearance process, we've improved the code base around the spout/bolt configuration. Specifically, the following changes need to be checked in:

1. EventHubBolt improvement: add event formatter to format tuples into bytes for EventHubs and support each bolt sending to a separate EH partition etc.

2. Refactor EventHubSpoutConfig, use setXXX() instead of specifying configuration in constructor for optional configurations.

3. EventHubSpoutConfig specify consumer group name

4. Workaround for Qpid bug that cannot receive messages from EventHubs in rare cases

5. Upgrade to newer Qpid version 0.32

### CODE REVIEW

**Comment by ptgoetz** [comment]
+1

**Comment by ptgoetz** [comment]
@shanyu, I'm getting test failures with the latest code:

```
Tests in error:
  testSpoutCheckpoint(org.apache.storm.eventhubs.spout.TestEventHubSpout): org/apache/qpid/amqp_1_0/type/messaging/Data : Unsupported major.minor version 51.0
  testSpoutBasic(org.apache.storm.eventhubs.spout.TestEventHubSpout): org/apache/qpid/amqp_1_0/type/messaging/Data
  testPMCheckpointWithPendingAndResend(org.apache.storm.eventhubs.spout.TestPartitionManager): org/apache/qpid/amqp_1_0/type/messaging/Data
  testPartitionManagerNoFail(org.apache.storm.eventhubs.spout.TestPartitionManager): org/apache/qpid/amqp_1_0/type/messaging/Data
  testPartitionManagerResend(org.apache.storm.eventhubs.spout.TestPartitionManager): org/apache/qpid/amqp_1_0/type/messaging/Data
  testPMCheckpointWithResend(org.apache.storm.eventhubs.spout.TestPartitionManager): org/apache/qpid/amqp_1_0/type/messaging/Data
  testPMCheckpointWithNoPendingAndNoResend(org.apache.storm.eventhubs.spout.TestPartitionManager): org/apache/qpid/amqp_1_0/type/messaging/Data
  testPartitionManagerMaxPendingMessages(org.apache.storm.eventhubs.spout.TestPartitionManager): org/apache/qpid/amqp_1_0/type/messaging/Data
  testPMCheckpointWithPending(org.apache.storm.eventhubs.spout.TestPartitionManager): org/apache/qpid/amqp_1_0/type/messaging/Data
  testPartitionManagerEnqueueTimeFilter(org.apache.storm.eventhubs.spout.TestPartitionManager): org/apache/qpid/amqp_1_0/type/messaging/Data
  testEmitInSequence(org.apache.storm.eventhubs.trident.TestTransactionalTridentEmitter): org/apache/qpid/amqp_1_0/type/messaging/Data
  testReEmit(org.apache.storm.eventhubs.trident.TestTransactionalTridentEmitter): org/apache/qpid/amqp_1_0/type/messaging/Data
```

Can you take a look?

**Comment by shanyu** [comment]
Hi Taylor,

One of the dependencies (Apache Qpid) requires Java 1.7 and above, therefore you have to use Java 1.7 to build and run unit tests for storm-eventhubs. You’ll see those exceptions when using Java 1.6 to build the project.

What is the Java version used on the build server? Is there a requirement for Java versions for Storm? I couldn’t find any info online.

The Qpid library is a must for EventHubSpout to work properly. So if we cannot change Java version requirement for Storm, I’ll have to disable a few unit tests to let it pass on Java 1.6.

Thanks,
Shanyu

**Comment by ptgoetz** [comment]
@shanyu, yeah I realized what was happening as soon as I posted that, which is why I deleted the comment.

I just started an email thread regarding dropping support for Java 1.6 and requiring 1.7. I don't see it as a problem, but I want to get the community's opinion first.

**Pull request merged**
