### PR TITLE
STORM-807: quote args correctly

### PR DESCRIPTION
**Pull request by revans2**

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
LGTM, I've confirmed with print COMMAND and ARGS.

Before applying
```
$ ./storm list "a b" c d
list
['a', 'b', 'c', 'd']
```

After applying
```
$ ./storm list "a b" c d
list
['a b', 'c', 'd']
```

**Comment by liaokevin** [comment]
What you mean

**Comment by HeartSaVioR** [comment]
LGTM = Looks good to me

**Comment by revans2** [comment]
@liaokevin previously bin/storm was a python script but recently it changed to a shell script that wraps the original python script.  The shell script did not quote arguments passed to the python script correctly so if I ran.

```./storm list "a b" c d```
it would not honor the quotes around "a b" and treat them as separate arguments.  This is a problem if we include space in the name of a topology, or if we try to add a config to the command line with a space in it.

**Comment by ptgoetz** [comment]
+1

**Comment by revans2** [comment]
@ptgoetz I am merging this into 0.10.x-branch as well, because it was introduced there.  If you disagree please let me know and I will revert it.

**Comment by revans2** [comment]
@ptgoetz never mind, JIRA is off STORM-675 said it went into 0.10.0, but it did not.  I will just merge this to trunk.

**Pull request merged**
