### PR TITLE
STORM-2468: Remove clojure from storm-client

### PR DESCRIPTION
**Pull request by revans2**
This is based off STORM-2447

### CODE REVIEW

**Comment by revans2** [comment]
Only the last commit is the one to look at.

**Comment by revans2** [comment]
Now that STORM-2447 is in I have rebased this on master.

**Comment by revans2** [comment]
@knusbaum please take a look at this.

There were a number of changes here.  Some to replace functionality being used from clojure runtime with java code.  Some of it was moving/deduplicating dependencies, but the two big ones were adding in support to register the clojure kryo serialization transparently and making a tuple have the same clojure integration it had before by replacing it with a new tuple.

**Comment by revans2** [comment]
@HeartSaVioR @ptgoetz If you have time to take a look I would appreciate it.  It looks like @knusbaum might be a bit too busy to take a look in a timely manor.

**Comment by knusbaum** [comment]
Missed the previous request. This all looks good to me.

+1

**Comment by ptgoetz** [comment]
+1 Sorry for the delayed review.

**Pull request merged**
