### PR TITLE
[STORM-1558] Utils in java breaks component page due to illegal type cast

### PR DESCRIPTION
**Pull request by unsleepy22**

### CODE REVIEW

**Comment by hustfxj** [comment]
+1

**Comment by arunmahadevan** [comment]
+1

**Comment by revans2** [comment]
+1

**Comment by redsanket** [comment]
+1

**Comment by redsanket** [comment]
upmerge please

**Comment by unsleepy22** [comment]
Upmerged, please help review again. The CI failure seems unrelated to this PR.

**Comment by wuchong** [comment]
I find that `event-log-link` breaks component page due to the same reason.

https://github.com/apache/storm/blob/master/storm-core/src/clj/org/apache/storm/ui/core.clj#L148

So we can fix it in this PR too. 

+1  otherwise

**Comment by arunmahadevan** [comment]
the first commit has that change but seems to have disappeared after the upmerge.

**Comment by unsleepy22** [comment]
@arunmahadevan sorry missed that, I've added it back.

**Comment by satishd** [comment]
+1

**Comment by unsleepy22** [comment]
All tests pass on my Mac, the CI failure should be unrelated.

**Comment by redsanket** [comment]
Still +1

**Comment by arunmahadevan** [comment]
+1

**Pull request merged**
