### PR TITLE
STORM-2294 Send activate and deactivate command to ShellSpout

### PR DESCRIPTION
**Pull request by obiwabrakenobi**
By sending activate and deactivate to ShellSpout it is possible to react on these events i.E. closing/opening resources

### CODE REVIEW

**Comment by redsanket** [comment]
LGTM +1

**Comment by HeartSaVioR** [comment]
I like that idea but in order to add this we need to address this to multilang implementations, and doc to announce new feature.
I'd be happy if @obiwabrakenobi follows up this issue, but if in case of not available, I can take it over.

**Comment by obiwabrakenobi** [comment]
i'll update the docs @HeartSaVioR

**Comment by andrewkcarter** [comment]
+1
I would like to see this made available so it can be used in pystorm/streamparse.

**Comment by HeartSaVioR** [comment]
@obiwabrakenobi Any updates here? If you're not available I'll file an issue and take it over.

**Comment by obiwabrakenobi** [comment]
i'll finish it until the end of this week...is was busy on vacation :) @HeartSaVioR

**Comment by obiwabrakenobi** [comment]
@HeartSaVioR docu is updated, do you need a jira issue too?

**Comment by HeartSaVioR** [comment]
@obiwabrakenobi Yes please. This is worth to be filed to issue.

**Comment by obiwabrakenobi** [comment]
@HeartSaVioR done. https://issues.apache.org/jira/browse/STORM-2294

**Comment by HeartSaVioR** [comment]
@obiwabrakenobi 
Please change your PR title to have STORM-2294 as prefix. If possible squashing your commits into one would be more appreciated.

**Comment by obiwabrakenobi** [comment]
well, i try to rebase, but not sure if that works properly

**Comment by HeartSaVioR** [comment]
@obiwabrakenobi I'll try to take care of rebasing while merging.

**Pull request closed without merging**
