### PR TITLE
[STORM-2672] Expose a metric for calls to reportError()

### PR DESCRIPTION
**Pull request by Ethanlm**
See: https://issues.apache.org/jira/browse/STORM-2672

Add a metric for calls to reportError.

### CODE REVIEW

**Comment by revans2** [comment]
Could you update the metrics documentation to include the new metric?  This is new and under `docs/Metrics.md`

otherwise the change looks good.

**Comment by revans2** [comment]
Could you update the metrics documentation to include the new metric?  This is new and under `docs/Metrics.md`

otherwise the change looks good +1

**Comment by Ethanlm** [comment]
Yes. Will do

**Comment by Ethanlm** [comment]
@roshannaik  Could you please let me know what issues you are talking about?

**Pull request merged**
