### PR TITLE
[STORM-1057] Add throughput metrics to spouts/bolts and display them on web ui for 1.x-branch

### PR DESCRIPTION
**Pull request by wangli1426**
Hi @HeartSaVioR, @revans2, @harshach,@d2r,@unsleepy22,

I upmerge PR apache/storm#753 to 1.x-branch.
Sorry for the delay.
Please review.

Thanks.

### CODE REVIEW

**Comment by wangli1426** [comment]
@HeartSaVioR Can you review this PR? Thanks.

**Comment by wangli1426** [comment]
Can I create a new PR based on the latest master version rather than upmerging this RP to master? The former would be much easier, since a lot of changes have been made from 1.x to 2.x.

**Comment by HeartSaVioR** [comment]
Yes sure. You don't essentially need to upmerge/rebase old pull request if you want to provide new pull request based on current.

**Comment by wangli1426** [comment]
Thanks for the prompt response. I will create a new pull request for master asap.

**Pull request closed without merging**
