### PR TITLE
[STORM-934] Add doc descriptions for the TOPOLOGY_ACKER_EXECUTORS

### PR DESCRIPTION
**Pull request by zhuoliu**
The current doc for ackers is outdated (it is for TOPOLOGY_ACKERS), we need to update the descriptions for TOPOLOGY_ACKER_EXECUTORS in Config.java, Guaranteeing-message-processing.md and Running-topologies-on-a-production-cluster.md.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1, good explanation.

**Comment by HeartSaVioR** [comment]
@zhuoliu 
Btw, I think we need to create new issue cause STORM-658 is actually wrong.
Could you create new issue? Thanks!

**Comment by zhuoliu** [comment]
Thanks @HeartSaVioR ! Sure, a new issue is created (storm-934). 
https://issues.apache.org/jira/browse/STORM-934

**Comment by HeartSaVioR** [comment]
I merged it into master branch at ASF git repos, but seems like Github mirror is out of sync.

I'll resolve issue when mirror keeps up ASF repo.

**Comment by zhuoliu** [comment]
Thanks for that, @HeartSaVioR !

**Comment by HeartSaVioR** [comment]
Github mirror catches up ASF now, but it isn't treated as merged.
Actually I modified some commit's log to point proper issue number, and it could be the reason. 
@zhuoliu Could you close this PR manually? Thanks in advance!

**Comment by zhuoliu** [comment]
Thanks  @HeartSaVioR. I see the changes merged to master though no log shows. 
No problem, I am closing it now.

**Pull request closed without merging**
