### PR TITLE
STORM-748: Package Multi-Lang scripts so they don't have to be duplicated

### PR DESCRIPTION
**Pull request by ptgoetz**
This moves storm's multi-lang components to a single location so they can be referenced from, rather than copied to other projects.

Each language implementation then becomes an optional dependency. `storm-core` uses them for unit tests, while `storm-starter` now uses them as a dependency rather than duplicating them.

Please hold off on merging until I have a chance to better document the changes. I'm putting this pull request up so others can comment on the approach I took.

### CODE REVIEW

**Comment by ptgoetz** [comment]
Commenting to trigger JIRA sync. Ignore.

**Comment by HeartSaVioR** [comment]
Your approach is great!
Btw, since each language contains only one source file, how about aggregating these into multilang module? pom.xml seems to be duplicated, and seems like aggregating these makes no effect on testing / using.

**Comment by ptgoetz** [comment]
@HeartSaVioR Thanks for the feedback. I'm open to either approach...

My thought behind keeping them separate was that some languages may require compilation (e.g. go, c++, etc.), or some sort of build process (maybe involving Maven filtering?). In that case keeping them separate makes more sense. We don't have that requirement now, but we could in the future.

**Comment by HeartSaVioR** [comment]
@ptgoetz Yes, you're right. I didn't think about language which needs compilation. 
Thanks for clarification.

**Comment by harshach** [comment]
+1

**Comment by revans2** [comment]
+1 great job.

**Pull request merged**
