### PR TITLE
STORM-1222. Support Kafka as external tables in StormSQL

### PR DESCRIPTION
**Pull request by haohui**
This PR adds the support of Kafka as external tables in StormSQL.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by harshach** [comment]
Thanks @haohui merged into STORM-1040

**Comment by darionyaphet** [comment]
@haohui thanks for you great work :+1:  

Storm SQL need more documents to learning how to use it :)

Will you do some document to explain it ?

**Comment by haohui** [comment]
Yes I'll file another jira to document it.

**Pull request merged**
