### PR TITLE
[STORM-3900] Upgrade Cassandra version and Datastax to latest version 4.

### PR DESCRIPTION
**Pull request by bipinprasad**
## What is the purpose of the change

*Cassandra project specifically suppresses certain CVE's. In Storm project, snakeyaml dependency has been upgraded to version 2.0. However Cassandra uses version 1.32 and suppresses the CVE. Use CVE suppression file used in Cassandra to build this project*

## How was the change tested

*By building the external/storm-cassandra subproject.*

### CODE REVIEW

**Comment by rzo1** [comment]
No changes?

**Review by rzo1 — APPROVED** [review]

**Comment by rzo1** [comment]
Hey @bipinprasad 

it seems, that the Cassandra update has some problems with Java 17 as the related tests are crashing (multple runs). Do you want to have a look yourself or shall I have a look at it?

**Comment by rzo1** [comment]
It works in Java 11 because we [excluded](https://issues.apache.org/jira/browse/STORM-3914) the related tests from being run in Java 11. I am having a look now.

**Comment by rzo1** [comment]
I did some additional modifications. The current tests are executable on that branch but will crash as the cassandra driver cannot connect to the local cassandra instance

```bash
	Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt
		at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
		at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
		at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThr
```

This is weird because the related host / port is open and accepts connections. Needs some more digging but at least we are not seeing JVM issues or missing classes due to netty, etc.

**Comment by rzo1** [comment]
@jnioche Maybe you can also have a look here?

**Comment by bipinprasad** [comment]
I tried a few things to get the Cassandra running (like application an application.conf file) with content:
`datastax-java-driver {
  basic.load-balancing-policy {
    local-datacenter = "datacenter1"
  }
}	
`
and read the conf file when creating the cql session. This gets rid of the localdatacenter error.
However, looks like there is a basic incompatibility with JDK17 and Cassandra. JDK17 will not allow call to System.setSecurityManager and throws the following Exception for me. And I dont know how to get around this.
`java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
    at java.lang.System.setSecurityManager(System.java:429) ~[?:?]
    at org.apache.cassandra.security.ThreadAwareSecurityManager.install(ThreadAwareSecurityManager.java:96) ~[cassandra-all-4.1.3.jar:4.1.3]
    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:248) ~[cassandra-all-4.1.3.jar:4.1.3]
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:751) ~[cassandra-all-4.1.3.jar:4.1.3]
    at org.apache.storm.cassandra.testtools.EmbeddedCassandraResource.startCassandraDemonAndInitialize(EmbeddedCassandraResource.java:80) ~[test-classes/:?]
    at org.apache.storm.cassandra.testtools.EmbeddedCassandraResource.beforeAll(EmbeddedCassandraResource.java:95) ~[test-classes/:?]
`

**Comment by bipinprasad** [comment]
jvm option  `-Djava.security.manager=allow` fixes the `java.lang.System.setSecurityManager` exception.
There is still the error com.datastax.oss.driver.api.core.NoNodeAvailableException

**Pull request closed without merging**
