### PR TITLE
STORM-2296 Kafka spout - no duplicates on leader changes

### PR DESCRIPTION
**Pull request by ernisv**
Current behavior of Kafka spout emits duplicate tuples whenever Kafka topic leader's change.
In case of exception caused by leader changes, PartitionManagers are simply recreated losing the state about which tuples were already emitted and new PartitionManager re-emits them again.

This is fine as at-least-once is fulfilled, but still it would be better to not emit duplicate data if possible.
Moreover this could be easily avoided by moving the state related to emitted tuples from old PartitionManager to new one.

### CODE REVIEW

**Comment by harshach** [comment]
@ernisv can you file JIRA under STORM here https://issues.apache.org/jira/browse/STORM-1757

**Comment by ernisv** [comment]
Created JIRA issue: https://issues.apache.org/jira/browse/STORM-2296

**Comment by harshach** [comment]
@ernisv please add to PR title as well. Also can you open this against 1.x-branch or master so that we can cherry-pick from there to other branches.

**Comment by ernisv** [comment]
Created another pull request for 1.x-branch:

https://github.com/apache/storm/pull/1888

**Comment by HeartSaVioR** [comment]
@ernisv Hi, I merged this patch to the master and 1.x branch, and I don't think this should be applied to 1.0.x branch since it's not a bugfix. If you agree please close this PR, and if you want to include this to bugfix version line please let me know.

**Comment by ernisv** [comment]
That's fine - i'll close this PR

**Pull request closed without merging**
