### PR TITLE
STORM-635. logviewer returns 404 if storm_home/logs is a symlinked dir.

### PR DESCRIPTION
**Pull request by harshach**

### CODE REVIEW

**Comment by revans2** [comment]
The change to check the parent directory is the root dir was put in on purpose for security reasons.  if someone puts in a file called "../../../etc/passwd" there could be some serious security issues involved.

-1

I am fine with supporting symlinks but we need to have a way to restrict what can be accessed through the logviewer.

**Comment by harshach** [comment]
@revans2 my bad I missed security fix that went in before. Please check the latest patch . Thanks.

**Comment by Parth-Brahmbhatt** [comment]
+1.

**Comment by revans2** [comment]
+1 looks good to me.

**Pull request merged**
