### PR TITLE
STORM-1120 fix keyword (schema -> scheme) from main-routes

### PR DESCRIPTION
**Pull request by HeartSaVioR**

### CODE REVIEW

**Comment by knusbaum** [comment]
Oops. Didn't see this before I opened #812 
I can close or you can close. Either way.

**Comment by HeartSaVioR** [comment]
@knusbaum 
It is a tiny patch and I don't mind closing this.
But if you also don't mind, let's resolve it with normal way in open source world, 
"If diff is same, first input wins, later input will be marked as duplicate." :)

**Comment by knusbaum** [comment]
@HeartSaVioR Sounds good to me. I wasn't aware of that bit of etiquette. #812 is closed.

**Comment by knusbaum** [comment]
+1

**Comment by HeartSaVioR** [comment]
@knusbaum Thanks for the consideration! :)

**Pull request merged**
