### PR TITLE
STORM-2324 : Fix deployment failure if resources directory is missing in topology jar

### PR DESCRIPTION
**Pull request by roshannaik**
This is same as https://github.com/apache/storm/pull/1898 ... just  specific to master branch.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1 Given that it's identical to #1898 we don't need to wait for 24hr.

**Comment by HeartSaVioR** [comment]
Sorry missed build failure, revoking +1.

```
testSetup(org.apache.storm.daemon.supervisor.ContainerTest)  Time elapsed: 0.761 sec  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 
Wanted but not invoked:
advancedFSOps.createSymlink(
    /tmp/testing/workers/worker_id/resources,
    /tmp/testing/supervisor/stormdist/test_topology/resources
);
-> at org.apache.storm.daemon.supervisor.ContainerTest.testSetup(ContainerTest.java:219)
However, there were other interactions with this mock:
-> at org.apache.storm.daemon.supervisor.Container.<init>(Container.java:135)
-> at org.apache.storm.daemon.supervisor.Container.setup(Container.java:305)
-> at org.apache.storm.daemon.supervisor.Container.setup(Container.java:312)
-> at org.apache.storm.daemon.supervisor.Container.setup(Container.java:313)
-> at org.apache.storm.daemon.supervisor.Container.setup(Container.java:314)
-> at org.apache.storm.daemon.supervisor.Container.setup(Container.java:317)
-> at org.apache.storm.daemon.supervisor.Container.getWorkerUser(Container.java:462)
-> at org.apache.storm.daemon.supervisor.Container.writeLogMetadata(Container.java:372)
-> at org.apache.storm.daemon.supervisor.Container.saveWorkerUser(Container.java:481)
-> at org.apache.storm.daemon.supervisor.Container.createArtifactsLink(Container.java:385)
-> at org.apache.storm.daemon.supervisor.Container.createArtifactsLink(Container.java:387)
	at org.apache.storm.daemon.supervisor.ContainerTest.testSetup(ContainerTest.java:219)
```

**Comment by roshannaik** [comment]
Updated PR with UT fix.

**Comment by HeartSaVioR** [comment]
+1 UT passed from local dev.

**Pull request merged**
