### PR TITLE
[STORM-3384] set-log-level command throws wrong exception if the topology is not running

### PR DESCRIPTION
**Pull request by Ethanlm**
cherrypick of https://github.com/apache/storm/pull/3001

### CODE REVIEW

**Comment by srdo** [comment]
Isn't 1.0.x dead?

**Comment by Ethanlm** [comment]
@srdo If it's dead, we can close this pr

**Comment by srdo** [comment]
I think it's dead, last time we released, we only went off the 1.1 and 1.x branches. Last commit was last June as well.

Closing.

**Comment by Ethanlm** [comment]
@srdo Thank you

**Pull request closed without merging**
