### PR TITLE
Storm-456 cannot navigate to topology page when name contains spaces

### PR DESCRIPTION
**Pull request by NareshKosgi**
@Parth-Brahmbhatt 
I had pull request open for this but I deleted it accidentally. 

You were rite the decode only fixed the space issue but caused issues with percent sign.  After looking thru the code I found where the url is being encoded and changed it to use the ring encoder.  This fixed the issue for both percent and space.

### CODE REVIEW

**Comment by d2r** [comment]
@Parth-Brahmbhatt, @NareshKosgi , Does #360 sufficiently resolve STORM-456?  If so, we should close this pull request and resolve STORM-456.

**Comment by Parth-Brahmbhatt** [comment]
Yes, I think its ok to close the jira. @NareshKosgi can you test and comment. The changes are merged into master so should be easy to test.

**Comment by NareshKosgi** [comment]
@Parth-Brahmbhatt I tried to build the lastest storm but i'm having the following issue:

[ERROR] Error resolving version for plugin 'org.apache.storm:storm-maven-plugins' from the repositories [local (/Users/nareshkosgi/.m2/repository), central (http://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository 

I spent sometime trying to see if its something local to mine but haven't had success.  am I missing something new that was added to storm that I need in order to build the latest master?  I installed node which was the only new thing I saw.

**Comment by revans2** [comment]
We put in some changes so the storm build now uses a plugin that is also built as part of the build.  This makes it so you cannot run ```mvn compile``` on its own any more, you need to run at least ```mvn package``` because needs a jar on the classpath.  If you plan on building in just storm-core you need to have installed the plugin  into your local repo first.  We are working on a way to fix this, but don't have a perfect solution yet https://issues.apache.org/jira/browse/STORM-639.

**Comment by NareshKosgi** [comment]
@revans2 @Parth-Brahmbhatt I was able to build and run by using mvn install.  I checked with topo name with space and '%' sign.  They are working.  Do I just close the pull request and jira ticket in that case?

**Comment by Parth-Brahmbhatt** [comment]
@NareshKosgi Thanks for testing the feature, yes you can just close it.

**Pull request closed without merging**
