### PR TITLE
STORM-3817 - Upgrade Zookeeper to 3.5.9

### PR DESCRIPTION
**Pull request by rzo1**
## What is the purpose of the change

- Upgrades to Zookeeper 3.5.9 (see https://issues.apache.org/jira/browse/STORM-3817)

## Additional notes

I did not upgrade Curator to 5.x as this breaks exhibitor support and I don't know, if this is a commonly used and required feature. Looks like Curator in 4.3.x depends on an Zookeeper 3.5.x, so I upgraded only to 3.5.9

## How was the change tested

I managed to run the build on a Ubuntu 16.04 LTS Server VM (based on the *.sh scripts from Travis).  With this system running OpenJDK-8 I conducted a full build with all tests (similar to Travis)

JDK | ENV | OS | State  
-- | -- | -- | -- 
openjdk8 | MODULES=Client | Linux | OK
openjdk8 | MODULES=Server | Linux | OK
openjdk8 | MODULES=Core | Linux | OK
openjdk8 | MODULES=External | Linux | OK
openjdk8 | MODULES=Integration-Test | Linux | OK
openjdk8 | MODULES=Check-Updated-License-Files | Linux | OK

Ran build and unit tests - CI build needs #3437

### CODE REVIEW

**Comment by rzo1** [comment]
Changed it back to WIP to check the CI logs. Looks like I am missing some deps /classes.

**Comment by rzo1** [comment]
This is now ready for review! If someone could have a look, it would be very much appreciated!

**Comment by rzo1** [comment]
Rebased to latest log4j2 changes / license file from master.

**Comment by rzo1** [comment]
Looks like the CI env now has some problems with locating packages:

```
E: Unable to locate package python3.6
E: Couldn't find any package by glob 'python3.6'
E: Couldn't find any package by regex 'python3.6'
The command "sudo apt-get install python3.6" failed and exited with 100 during .
```

**Comment by rzo1** [comment]
CI build needs #3437

**Review by agresch — APPROVED** [review]
seems ok to me.  @bipinprasad - do you have any concerns?

**Pull request merged**
