### PR TITLE
[STORM-1066] add current directory for worker process launcher and fix absolute-storm-local-dir bug

### PR DESCRIPTION
**Pull request by zhuoliu**
Currently, when supervisor launches a worker, the current directory of the worker process is not specified. In that case, the worker will be launched with a current directory as ".", which is a random directory. It can cause problems especially when the worker needs to dump something to its current directory.
To fix this, we should enable ProcessBuilder to specify worker's current directory as worker-root/worker-uuid.

Secondly, this pull request fixes one bug in absolute-storm-local-dir function. If STORM-LOCAL is configured as nil or not configured, "(is-absolute-path? path)" can cause NPE.

### CODE REVIEW

**Comment by revans2** [comment]
+1 looks good to me.

**Comment by HeartSaVioR** [comment]
+1 Nice work.

**Comment by ptgoetz** [comment]
+1

**Comment by HeartSaVioR** [comment]
Since PR contains bugfix which is introduced to 0.10.x-branch, I'll backport this to 0.10.x.

**Pull request merged**
