### PR TITLE
STORM-3075 fix NPE

### PR DESCRIPTION
**Pull request by agresch**

### CODE REVIEW

**Comment by Ethanlm** [comment]
It looks reasonable. But would like to understand more about it. Could you elaborate on in which case tc will be null?

**Comment by agresch** [comment]
@Ethanlm - I see tc being null whenever I start nimbus (at least with no topologies).

**Comment by agresch** [comment]
@Ethanlm - nice catch.  Will fix the source of the problem instead....

**Comment by agresch** [comment]
@Ethanlm - please take a look.  Thanks.

**Comment by agresch** [comment]
@Ethanlm - done.  Added a spelling fix.

**Pull request merged**
