### PR TITLE
[STORM-1496] Nimbus periodically throws blobstore-related exception

### PR DESCRIPTION
**Pull request by redsanket**
Can backport to 1.x-branch

### CODE REVIEW

**Comment by revans2** [comment]
+1 pending screwdriver

**Comment by redsanket** [comment]
@HeartSaVioR - Put a pull request against master as per the suggestion

**Comment by HeartSaVioR** [comment]
+1 

I think we can merge now cause origin pull request (#1035) waits for 3 days, and now there're two committers' +1.

**Comment by satishd** [comment]
Verified that topology visualization works fine with this fix.

**Pull request merged**
