### PR TITLE
Kafka Spout New Consumer API - KafkaSpoutRetryExponentialBackoff Bug

### PR DESCRIPTION
**Pull request by hmcl**
- KafkaSpoutRetryExponentialBackoff#nextTime(...) method is off by order of magnitude

### CODE REVIEW

**Comment by hmcl** [comment]
Please merge this into 1.x-branch as well

**Comment by hmcl** [comment]
@harshach @priyank5485 can you please review. Thanks.

**Comment by hmcl** [comment]
@priyank5485 thanks for catch.

**Comment by priyank5485** [comment]
@hmcl One minor thing. Should we handle long overflows?

**Comment by priyank5485** [comment]
+1

**Comment by ptgoetz** [comment]
+1

**Pull request merged**
