### PR TITLE
STORM-980 Re-include storm-kafka to Travis CI build

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Please refer https://issues.apache.org/jira/browse/STORM-980 to more details.

We should resolve storm-hive build issue first (#609 may help to resolve), so that Travis CI has a chance to run unit tests on storm-kafka.

For confirmation, I merged #609 and current PR into another branch on my fork and built it from Travis CI.
https://travis-ci.org/HeartSaVioR/storm/builds/75071270

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Upmerged master to check build also works well with apache repo.

**Comment by HeartSaVioR** [comment]
One of two build failed with random failure of storm-core. 
storm-hive build issue seems to be resolved, and unit tests of storm-kafka seems to play well.

**Comment by zhuoliu** [comment]
LGTM +1

**Comment by d2r** [comment]
+1 on your testing of this.  We can revert if it does not work.

**Pull request merged**
