### PR TITLE
STORM-1197: Migrate Travis-CI to container-based builds.

### PR DESCRIPTION
**Pull request by knusbaum**
http://docs.travis-ci.com/user/migrating-from-legacy/

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@knusbaum 
It makes build slower than current now. Please refer #761 for more info.

Btw, if it is more stable than legacy (I mean less random test failures) I'll definitely vote +1.

**Comment by knusbaum** [comment]
@HeartSaVioR 

There. I shaved a little more than 5 minutes off the build time.

**Comment by HeartSaVioR** [comment]
@knusbaum 
Container based build doesn't save build time. 
Seems like splitting build matrix saves build time, so I'd like to see it applied to legacy.

Btw, container based build is triggered faster than legacy, so container based build takes advantage when build time is small enough.

**Comment by HeartSaVioR** [comment]
@knusbaum 
Hey, I see the benefit of splitting build matrix, since it seems faster than current.
If ```legacy + splitting build matrix``` doesn't work, I'd like to vote +1 to ```container based + splitting build matrix```.
I'd like to see reason of closing this PR. Did you see the disadvantage of splitting build matrix?

**Comment by knusbaum** [comment]
@HeartSaVioR 
Yes, I remembered that the external parts I split off the storm-core build are dependent on the storm-core jar, so they must be done after storm-core. There isn't any benefit to doing the external, etc. in parallel with each other either, since they are so small that the startup cost overwhelms the parallelization benefit.

The caching is still valid, but it only shaves a few seconds off.

**Pull request closed without merging**
