### PR TITLE
[STORM-3595] Refactor Resource Aware Strategies (Base, Generic, Default)

### PR DESCRIPTION
**Pull request by bipinprasad**
Code is duplicated in incompatible ways. Refactor BaseResourceAwareStrategy, DefaultResourceAwareStrategy and GenericResourceAwareStrategy to remove duplicated code and minor incompatibilities.

Differences in processing between Default and Generic can be specified via two variables:
    - flag for whether to sort nodes for every executor assignment
    - type of sorting to be applied to object resources when node sorting is done

### CODE REVIEW

**Comment by Ethanlm** [comment]
It's a good idea to reduce code duplications.  But the refactored code seems less extendable and heavily coupled with the parent class. 

So after the refactoring, the child class needs to set two attributes 
Attribute 1: sortNodesForEachExecutor
Attribute 2: objectResourceSortType

Imaging a case here:
  If we want to implement another child class, which has another requirement, then we need to add an `Attribute 3`, and it will require us to update all the existing classes (BaseResourceAwareStrategy, DefaultResourceAwareStrategy, and GenericResourceAwareStrategy and even the IStrategy interface to reflect the change).


For Attribute 2: objectResourceSortType,

I am seeing the same code is copied from `DefaultResourceAwareStrategy` and `GenericResourceAwareStrategy` to the parent class `BaseResourceAwareStrategy`, and use `objectResourceSortType` to distinguish between which one of `sortObjectResourcesDefault` and `sortObjectResourcesGeneric` to be used.  This doesn't reduce code duplication. But it increased code coupling.

For Attribute 1: sortNodesForEachExecutor

The duplication mostly happens in whether or not sorting nodes for each executor, in the `schedule` function.  Current way of setting a `sortNodesForEachExecutor` variable to control the parent class's `schedule` logic doesn't seem straightforward and increases code coupling. My suggestion on reducing the code duplication is to extract the following part:

https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java#L65-L92

from `DefaultResourceAwareStrategy` as a separate function (say **func1**) and re-implement it in `GenericResourceAwareStrategy`.

And the hierarchy will be 

`DefaultResourceAwareStrategy` extends `BaseResourceAwareStrategy`,
`GenericResourceAwareStrategy` extends `DefaultResourceAwareStrategy`.

We can also have `BaseResourceAwareStrategy` to implement the `schedule` function, and 
`DefaultResourceAwareStrategy` and `GenericResourceAwareStrategy` both extend `BaseResourceAwareStrategy` and implement **func1** respectively.

**Comment by bipinprasad** [comment]
Moved the flags into Base constructor, removed from interface.

**Comment by kishorvpatil** [comment]
The end goal for this to ensure that `BaseResourceAwareStrategy` -> `GenericResourceAwareStrategy`-> `ConstraintSolverStrategy` where `wouldFit`, `sortingNodes` and `sortingExecutors` are extendable methods. So code is simplified in structure. The `DefaultResourceAwareStrategy` is nothing but `GenericResourceAwareStrategy` without special resources or affinity specified by topology.
This patch is a good step towards simplified this goal.

**Comment by Ethanlm** [comment]
As we discussed, we are going to finish all the refactoring and then push it back to community. Closing this for now.

**Pull request closed without merging**
