### PR TITLE
[STORM-1473] enable log search for daemon logs

### PR DESCRIPTION
**Pull request by zhuoliu**

### CODE REVIEW

**Comment by revans2** [comment]
+1

**Comment by revans2** [comment]
@zhuoliu I see from the JIRA that you have targeted this to 1.0.  It is a really small change so I am inclined to merge it in, but I would like to hear others opinions before doing so.

**Comment by zhuoliu** [comment]
Sure. Merging it in directly makes sense.

**Comment by ptgoetz** [comment]
+1 (and +1 for merging to 1.x as well)

**Pull request merged**
