### PR TITLE
STORM-2012: Upgrade Kafka to 0.8.2.2

### PR DESCRIPTION
**Pull request by vesense**
https://issues.apache.org/jira/browse/STORM-2012

### CODE REVIEW

**Comment by darionyaphet** [comment]
@vesense  could you describe what is update with `Kafka 0.8.2.2` ? thanks

**Comment by vesense** [comment]
@darionyaphet two important fixes for snappy compression. please take a look the above link first, thanks.

**Comment by vesense** [comment]
@HeartSaVioR I recommend upgrading kafka to the 0.8.2.2 version since this version fixed some important bugs. this is a minor change. hope to be merged.

**Comment by harshach** [comment]
+1

**Comment by knusbaum** [comment]
Builds fine locally.
+1

**Pull request merged**
