### PR TITLE
update PartitionManager.java

### PR DESCRIPTION
**Pull request by iBuddha**
fix wrong output in log when committed offset is too far behind latest offset

### CODE REVIEW

**Comment by Parth-Brahmbhatt** [comment]
+1.

**Comment by d2r** [comment]
Created [STORM-685](https://issues.apache.org/jira/browse/STORM-685) for this.

**Comment by d2r** [comment]
@iBuddha, thanks.  I merged this to master.
Post your name if you would like it in the contributors list along with your github id.
If you would like attribution in STORM-685 on JIRA, please post your JIRA user name too.

**Comment by iBuddha** [comment]
@d2r Sorry, my description  "behind lastest offset" is not corrent. It should be "currentOffset", "currentOffset" could be other offset besides latest. But "currentOffset" could still be confused.

**Pull request closed without merging**
