### PR TITLE
STORM-1546: Adding Read and Write Aggregations for Pacemaker to make it HA compatible (1.x-branch)

### PR DESCRIPTION
**Pull request by knusbaum**
1.x-branch version of Pacemaker-HA

### CODE REVIEW

**Comment by redsanket** [comment]
+1

**Comment by HeartSaVioR** [comment]
Please add a documentation here too.

**Comment by HeartSaVioR** [comment]
Seems like this PR has different diff compared to master (#1710) except Clojure things. This could be OK in short time, but will make us bothering if we need to fix something with Pacemaker.

I'd recommend to sync this with #1710 except pacemaker_state_factory.clj. I'm also OK to replace related clojure files to ported files in 1.x since it doesn't matter.

**Comment by knusbaum** [comment]
@HeartSaVioR I've synced the java files between the branches so there are almost no differences.

**Comment by knusbaum** [comment]
Also updated the docs.

**Comment by HeartSaVioR** [comment]
Thanks for the change. +1

**Pull request merged**
