### PR TITLE
STORM-809: Topology.message.timeout.secs should not allow null or <= 0

### PR DESCRIPTION
**Pull request by revans2**

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
LGTM.
Regarding NotNullPosIntegerValidator, it may be better to add some tests on config_test.clj.

**Comment by revans2** [comment]
@HeartSaVioR great comment.  I added in the tests.

**Comment by HeartSaVioR** [comment]
Great! I looked at b5ace22 and also looks good to me.

**Comment by harshach** [comment]
+1

**Pull request merged**
