### PR TITLE
[STORM-2144] Fix Storm-sql group-by behavior in standalone mode

### PR DESCRIPTION
**Pull request by arunmahadevan**
Fix group-by to not rely on monotonic group-by keys

### CODE REVIEW

**Comment by satishd** [comment]
+1 LGTM

**Comment by HeartSaVioR** [comment]
Found storm-jms version issue while checking Travis CI failing. Will submit a patch shortly.

**Comment by HeartSaVioR** [comment]
Other than that I'm +1. IMHO, standalone mode also needs to have some abstraction or introduce something to not creating source code by manipulate string directly.

**Comment by arunmahadevan** [comment]
@HeartSaVioR you are right, its very tedious to maintain. Right now its kind of a bridge to translate sql to java so that sql abstractions can be executed in storm core. IMO we should get out of standalone mode in future and add support in storm-sql to directly translate to storm-core topologies via the streams api proposed in STORM-1961 (https://github.com/apache/storm/pull/1693).

**Comment by satishd** [comment]
+1 for replacing code generation with an abstract API as it is hard to maintain. But that can be a different task and it is not related to this PR.

**Comment by harshach** [comment]
+1. Isn't standalone mode still helpful for devs instead of just moving to abstract API.

**Comment by HeartSaVioR** [comment]
I guess Calcite itself can provide interpreter for handling query. If then standalone users can just move to Calcite interpreter, and standalone mode could be removed. I'm planning to find it from Calcite.

**Comment by HeartSaVioR** [comment]
I guess `Interpreter` seems to be candidate for replacement of standalone more on storm-sql.

https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/interpreter/Interpreter.java

Unit tests are here.

https://github.com/apache/calcite/blob/master/core/src/test/java/org/apache/calcite/test/InterpreterTest.java

It still need to register tables and functions to root schema but storm-sql is same.

**Comment by HeartSaVioR** [comment]
Spend some time to look into it but it looks like breaking changes are needed.
Interpreter expects static input table before initializing Interpreter, which is valid for most of case, but Storm SQL standalone mode works like streaming, emitting input tuples and receive the outputs.

**Comment by satishd** [comment]
Thanks @arunmahadevan for the fix.

**Comment by satishd** [comment]
Pushed to master branch also.

**Pull request merged**
