### PR TITLE
STORM-1432: Spurious failure in storm-kafka test

### PR DESCRIPTION
**Pull request by knusbaum**
ExponentialBackoffMsgRetryManagerTest.testMaxBackoff() fails sometimes, I think due to too small times. It can miss the mark on slow machines.

### CODE REVIEW

**Comment by revans2** [comment]
I'm not sure that this fixed it.

```Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.696 sec <<< FAILURE! - in storm.kafka.ExponentialBackoffMsgRetryManagerTest
testSingleDelay(storm.kafka.ExponentialBackoffMsgRetryManagerTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expect no message ready for retry yet expected null, but was:<101>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:664)
	at org.junit.Assert.assertNull(Assert.java:646)
	at storm.kafka.ExponentialBackoffMsgRetryManagerTest.testSingleDelay(ExponentialBackoffMsgRetryManagerTest.java:57)
```

From the travis CI JDK8 build.

**Comment by knusbaum** [comment]
@revans2 I'll keep testing.

**Comment by knusbaum** [comment]
That looks like a different test entirely that has the same problem. I'll try to fix that one as well.

**Comment by revans2** [comment]
+1

**Pull request merged**
