### PR TITLE
Storm 1539 - Improve Storm ACK-ing performance

### PR DESCRIPTION
**Pull request by roshannaik**
PR for 1.x-branch

### CODE REVIEW

**Comment by knusbaum** [comment]
Should remove the corresponding function from `util.clj`

**Comment by revans2** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1

**Comment by vesense** [comment]
LGTM

**Comment by knusbaum** [comment]
+1

**Comment by ptgoetz** [comment]
+1

**Comment by zkendall** [comment]
I found this as a performance update in change log. I'm curious why the new implementation is so much better than the old?

One consideration is [bit-xor contains `reduce` inside it already](https://github.com/clojure/clojure/blob/clojure-1.7.0/src/clj/clojure/core.clj#L1276). So maybe removing the extra reduce in the closure would have helped without resulting to Java alternative.

**Comment by roshannaik** [comment]
The clojure reduce operation was much slower than a Java for loop. Also Storm is moving away from clojure so holding on to clojure was not important.

**Comment by zkendall** [comment]
Did not know that. Is there a roadmap/timeline on the java effort?

**Comment by roshannaik** [comment]
happening incrementally, most of it happening in 2.0 branch   ... look for jiras with titles starting with  "port .. "

**Pull request merged**
