### PR TITLE
[Storm-1579] Fix NoSuchFileException when running tests in storm-core

### PR DESCRIPTION
**Pull request by unsleepy22**
The old code takes "storm.local.dir" property as logDir while changes in STORM-1552 used `ConfigUtils.getLogDir`, which doesn't take this property, causing the ultimate event log directory to be "/logs/xxxx" and resulting in NoSuchFileException.

Note that the only effective change is in `getLogDir` method, I just formatted the whole class.

### CODE REVIEW

**Comment by unsleepy22** [comment]
There're test failures, I'll look into it first.

**Comment by abhishekagarwal87** [comment]
I didn't see such error on my system while running the tests though

**Comment by unsleepy22** [comment]
@abhishekagarwal87 they're in test-reports, when running tests, you'll get messages like "Exception: java.lang.ClassCastException thrown from the UncaughtExceptionHandler in thread "Thread-35-__eventlogger-executor[2 2]", by looking into the detailed test-reports, you'll get NoSuchFileException.

**Comment by abhishekagarwal87** [comment]
ohk. I see. Once the commit is ready, you can squash the commits. Looks good to me otherwise.

**Comment by unsleepy22** [comment]
My change was quite simple: just adding back the logic to check "storm.local.dir" property/conf, but there're 3 test failures in "org.apache.storm.supervisor-test" (all the others pass without exceptions), I've no idea why, can someone please help take a look?

**Pull request closed without merging**
