### PR TITLE
STORM-1754: Correct java version in 0.10.x storm-starter

### PR DESCRIPTION
**Pull request by vesense**
Correct java version in storm-starter, because we drop supporting JDK 1.6 since Storm 0.10.0.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
can you add the JIRA id in commit message and update the commit message to "correct java version in documentation"? Looks good otherwise

**Comment by vesense** [comment]
Thanks @abhishekagarwal87 Done.

**Comment by dossett** [comment]
+1

**Comment by hustfxj** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1 Thanks for addressing.

**Pull request merged**
