### PR TITLE
STORM-130: Supervisor getting killed due to java.io.FileNotFoundException: File '../stormconf.ser' does not exist.

### PR DESCRIPTION
**Pull request by harshach**

### CODE REVIEW

**Comment by ptgoetz** [comment]
+1

I'll presume +1 approvals carry over from #401, but allow others time to comment.

**Comment by revans2** [comment]
yes +1

**Comment by revans2** [comment]
@ptgoetz  I merged the corresponding pull into master, but I'm not totally sure what version number you want for a 0.9.3 update,  will it be 0.9.4?  0.9.3.1?  If you just want to merge it in and update the JIRA with the new number that will be great, otherwise I'll just go with 0.9.4 and call it good.

**Comment by ptgoetz** [comment]
merged to 0.9.3-branch. The next release of that branch will be 0.9.4, I'll update JIRA.

@harshach Can you close this PR?

**Comment by harshach** [comment]
Thanks @ptgoetz

**Comment by sweetest** [comment]
hi guys, I want to know about when you will release 0.9.4 including this feature.

**Comment by HQebupt** [comment]
It works. Thanks.

**Comment by ssudhaiyer** [comment]
I'm using 0.9.4 and seeing this issue. This seems to happen for me after an exception in my topology. I deactivate the topology and try deploying the topology again and I run into this issue.

**Comment by harshach** [comment]
@ssudhaiyer can you give us some steps on reproducing this.

**Comment by ssudhaiyer** [comment]
I'm seeing this error again. I'm able to reproduce this when there in an exception in my spout ( in this case it was a gson parse failure), I attempted to deactivate and activate my topology. I see this issue. Though I find the .ser file is present in the directory.

java.io.FileNotFoundException: File '/mnt/storm/supervisor/stormdist/my-topology-3-1433613276/stormconf.ser' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~[commons-io-2.4.jar:2.4]
	at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1763) ~[commons-io-2.4.jar:2.4]
	at backtype.storm.config$read_supervisor_storm_conf.invoke(config.clj:212) ~[storm-core-0.9.4.jar:0.9.4]
	at backtype.storm.daemon.worker$worker_data.invoke(worker.clj:182) ~[storm-core-0.9.4.jar:0.9.4]
	at backtype.storm.daemon.worker$fn__5033$exec_fn__1754__auto____5034.invoke(worker.clj:398) ~[storm-core-0.9.4.jar:0.9.4]
	at clojure.lang.AFn.applyToHelper(AFn.java:185) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__5033$mk_worker__5089.doInvoke(worker.clj:389) [storm-core-0.9.4.jar:0.9.4]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:500) [storm-core-0.9.4.jar:0.9.4]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.4.jar:0.9.4]
2015-06-09 12:48:58 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) [storm-core-0.9.4.jar:0.9.4]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$fn__5033$mk_worker__5089.doInvoke(worker.clj:389) [storm-core-0.9.4.jar:0.9.4]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:500) [storm-core-0.9.4.jar:0.9.4]
	at clojure.lang.AFn.applyToHelper(AFn.java:172) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.9.4.jar:0.9.4]

**Pull request closed without merging**
