### PR TITLE
[STORM-1413] remove unused variables for some tests

### PR DESCRIPTION
**Pull request by vesense**
https://issues.apache.org/jira/browse/STORM-1413

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by zhuoliu** [comment]
+1

**Comment by vesense** [comment]
@harshach @zhuoliu I have rebased the PR. Could you take a look?

**Comment by zhuoliu** [comment]
still +1

**Comment by ptgoetz** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1

**Comment by revans2** [comment]
+1

**Pull request merged**
