### PR TITLE
STORM-1012 STORM-967 STORM-922 STORM-1042 Shaded almost everything 0.10.x

### PR DESCRIPTION
**Pull request by revans2**
This is a back-port of https://github.com/apache/storm/pull/736 for 0.10.x

### CODE REVIEW

**Comment by revans2** [comment]
Travis is likely to fail just because the build log file gets too long now.  I have run the builds myself and everything seems to work fine.

**Comment by HeartSaVioR** [comment]
It would be better to backport STORM-803 to 0.10.x-branch since we may want to apply some patches to 0.10.x-branch after releasing 0.10.0.

**Comment by HeartSaVioR** [comment]
@revans2 
I backported STORM-803 to 0.10.x-branch now.
In a result, this PR needs to be upmerged. Could you do it? Thanks!

**Comment by revans2** [comment]
@HeartSaVioR Great I will upmerge.

**Comment by revans2** [comment]
Upmerged so we should be good to go on this pull request.

**Comment by kishorvpatil** [comment]
+1

**Comment by d2r** [comment]
+1, similar to #736

**Comment by ptgoetz** [comment]
-1 (for now) for the reasons listed in the comments on #736.

**Comment by revans2** [comment]
I just updated this pull request to match the changes I made to #736

**Comment by revans2** [comment]
The travis ci failure is unrelated to this change.

**Comment by ptgoetz** [comment]
+1

**Pull request merged**
