### PR TITLE
STORM-1920 version of parent pom for storm-kafka-monitor is set 1.0.2-SNAPSHOT in master branch

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* set it back to 2.0.0-SNAPSHOT

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
As it just fixes one pom file, and it's HOTFIX for CI, when CI seems good I'll go merge this.

**Comment by HeartSaVioR** [comment]
Travis CI seems to be service outage at this time: it even doesn't boot up yet. Need to wait more.

**Comment by darionyaphet** [comment]
`versions-maven-plugin` is used when we want to manage the versions in a project's POM file . 

`Storm` have lot of modules  this is maybe useful .

**Comment by HeartSaVioR** [comment]
CI build green. Merging.

**Pull request merged**
