### PR TITLE
STORM-1494 Link to supervisor logs form UI

### PR DESCRIPTION
**Pull request by yegortokmakov**

### CODE REVIEW

**Comment by yegortokmakov** [comment]
I've also removed not used argument in nimbus-log-link

**Comment by zhuoliu** [comment]
LGTM! +1

**Comment by revans2** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1
Since this modifies clj file, we may want to decide how to apply this to master.
Would it better to merge to 1.x first and just leave notice? Or do we just want to change PR's destination to master, and doing backport?

**Comment by ptgoetz** [comment]
+1  

For now I'd say it should be applied to the 1.x branch. Master should be considered as well, since the .clj files involved haven't really come into play yet, in terms of migration.

**Pull request merged**
