### PR TITLE
STORM-632: New grouping for better load balancing

### PR DESCRIPTION
**Pull request by gdfm**

### CODE REVIEW

**Comment by revans2** [comment]
+1 I also filed STORM-637 as a follow on JIRA to finish the integration.

**Comment by revans2** [comment]
Oops I missed one thing.  None of the new files have the Apache header in them.  I am +1 once the header in all of the other java files is also in these.

**Comment by gdfm** [comment]
I always forget them :)
Fixed.

**Comment by kishorvpatil** [comment]
LGTM. +1.

**Comment by HeartSaVioR** [comment]
Great research, +1.

**Pull request merged**
