### PR TITLE
STORM-950: Update website for publishing.

### PR DESCRIPTION
**Pull request by ptgoetz**
https://issues.apache.org/jira/browse/STORM-950

This pull request builds on the previous work:

* adds a people section
* cleaned up/expanded talks and slideshows page
* Added documentation section for "external" components
* removed hard-coded links to news section
* Misc. minor fixes

Once this is in, we can publish via svn one last time, then ask INFRA to turn on git publishing so the site gets updated anytime the `asf-site` branch gets updated.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by Parth-Brahmbhatt** [comment]
+1.

**Comment by d2r** [comment]
https://github.com/apache/storm/blob/1d09012e718091f67e3c8710fae7e6da64d86378/css/style.css#L341-L344

Sorry, but could we tone down the button hover transition to 100 or 200ms from 1s?  It's pretty intense. :)

**Comment by d2r** [comment]
Some of the links referencing code in Message-passing-implementation, storm-jdbc, Transactional-topologies look like they might be broken or pointing to the wrong place.  We can correct this separately.

+1 even with these issues.  I think this looks really good, nice work.

**Pull request merged**
