### PR TITLE
STORM-3097: deprecate storm-druid (1.x)

### PR DESCRIPTION
**Pull request by revans2**

### CODE REVIEW

**Comment by revans2** [comment]
This can be cherry-picked into 1.1.x, but 1.0.x does not even support storm-druid.

**Comment by srdo** [comment]
+1, but please also add the note to https://github.com/apache/storm/blob/1.x-branch/docs/storm-druid.md

**Comment by revans2** [comment]
Thanks @srdo I updated the docs to include the deprecated message.

**Comment by ptgoetz** [comment]
+1

**Pull request merged**
