### PR TITLE
[STORM-993] include uptimeSeconds as JSON integer field

### PR DESCRIPTION
**Pull request by d2r**

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by HeartSaVioR** [comment]
@d2r 
Overall looks fine.

Btw, seems like asfgit doesn't recognize your PR.
(Please see https://issues.apache.org/jira/browse/STORM-993.)
Could you modify title to STORM-993 instead of YSTORM-993?
And please upmerge this.

**Comment by HeartSaVioR** [comment]
@d2r Ping.

**Comment by d2r** [comment]
@HeartSaVioR , OK updated. Merge conflict was with HA nimbus STORM-166.  Also fixed the UI REST API doc, and made a tiny tooltip text edit in the nimbus-summary-template.

Not sure why I did not get the notification email from github; sorry for the delay.

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
