### PR TITLE
STORM-2127: Storm-eventhubs should use latest amqp and eventhubs-client versions

### PR DESCRIPTION
**Pull request by raviperi**
Update eventhub client dependency. Move Storm-Eventhubs dependency vesion definitions to parent pom. Introduce new schemes for message handling

### CODE REVIEW

**Comment by raviperi** [comment]
Below JIRA that reflects the need for the above work.
STORM-2127 - Storm-eventhubs should use latest amqp and eventhubs-client versions

**Comment by harshach** [comment]
+1

**Comment by harshach** [comment]
@raviperi  can you add the STORM jira number to the commit message and squash commits in both the PRs. Use the same title as the JIRA title https://issues.apache.org/jira/browse/STORM-2127

**Comment by raviperi** [comment]
@harshach  
Updated title as per your recommendation.

**Pull request merged**
