### PR TITLE
STORM-1033 replace closer.cgi to closer.lua

### PR DESCRIPTION
**Pull request by HeartSaVioR**
It's another version of #725, only difference is base branch. It is asf-site now.
Please refer STORM-1033 or #725 to more details.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@revans2 It's another version of #725. Please check.

**Comment by harshach** [comment]
+1

**Comment by revans2** [comment]
+1

@HeartSaVioR 
If you want to update the website yourself. After checking this into master.  You can regenerate the site using the instructions in https://github.com/apache/storm/blob/master/docs/README.md then checkout the svn site repository

https://svn.apache.org/repos/asf/storm/site

Update the publish/ directory with the newly generated files, don't delete old files unless you know what you are doing, just overwrite + add.  Then check it in.  The new site will start to show up in 10 to 30 mins as the different servers get updated.

**Comment by HeartSaVioR** [comment]
@revans2 
Thanks for the information. :)
Since @ptgoetz says he will contact ASF INFRA to update site automatically without svn repo, we can wait a new instruction for updating site. I think this could be a first test of new instruction.

@ptgoetz 
Did you contact ASF INFRA to update site, or just updated via svn repo? 
If you contacted ASF INFRA, could you update README.md on asf-site branch to reflect new instruction?
Thanks in advance!

**Comment by ptgoetz** [comment]
@HeartSaVioR Publishing is still svn-based, git based publishing is not yet enabled. I will update the README when git publishing gets turned on.

**Comment by HeartSaVioR** [comment]
@ptgoetz OK, I'll reflect this to site via svn. :)

**Pull request merged**
