### PR TITLE
(1.x) STORM-1911 IClusterMetricsConsumer should use seconds to timestamp unit

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* to have consistency with IMetricsConsumer

PR for master: #1498

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by abhishekagarwal87** [comment]
+1

**Comment by unsleepy22** [comment]
@HeartSaVioR could you use Time.currentTimeSecs instead? there's already a method to get current time secs.

**Comment by HeartSaVioR** [comment]
@unsleepy22 Thanks for pointing out. I addressed your comment to master / 1.x PR. Could you take a look again?

**Pull request merged**
