### PR TITLE
[STORM-1561] Supervisor should kill/restart if existing worker has changed assignments

### PR DESCRIPTION
**Pull request by kishorvpatil**
Currently, supervisor validates new assignments against existing assignments by port. It should also check on the same port - if executors have changed. The new executors won't have any threads associated with them in the worker.

### CODE REVIEW

**Comment by kishorvpatil** [comment]
@longdafeng I have refactored the changes into  separate method.

**Comment by jerrypeng** [comment]
+1

**Comment by ppoulosk** [comment]
+1, NB

**Comment by kishorvpatil** [comment]
I merged this changed in both master and 1.x-branch.

**Pull request merged**
