### PR TITLE
Added scope for junit and mockito dependencies

### PR DESCRIPTION
**Pull request by shoebamer**

### CODE REVIEW

**Comment by shoebamer** [comment]
JIRA Ticket: STORM-1531 - Junit and mockito dependencies need to have correct scope defined in storm-elasticsearch pom.xml

**Comment by revans2** [comment]
+1 pending travis

**Comment by revans2** [comment]
Oh we should also pull this into the 1.x line too.

**Comment by dossett** [comment]
+1

@revans2 The travis failures seem unrelated to this change?  I pulled @shoebamer's PR and could not reproduce the test failures locally (with `mvn clean integration-test -Pall-tests -Prat`)  If you are still +1 I'll merge

**Comment by revans2** [comment]
@dossett Yes I am still +1

**Pull request merged**
