### PR TITLE
remove duplicate semecolon

### PR DESCRIPTION
**Pull request by lujinhong**
just a little fix: remove duplicate semecolon.

### CODE REVIEW

**Comment by knusbaum** [comment]
+1

**Comment by zhuoliu** [comment]
+1

**Comment by zhuoliu** [comment]
Can you please create a named branch in your repository and then do the pull request? Otherwise it would be difficult for it be merged.

**Comment by lujinhong** [comment]
A new PR is here #1152

**Comment by zhuoliu** [comment]
can we close this duplicate one?

**Pull request closed without merging**
