### PR TITLE
[STORM-1069], add check case for external change of 'now' value.

### PR DESCRIPTION
**Pull request by 3Dragan**

### CODE REVIEW

**Comment by revans2** [comment]
It looks good to me I am +1 on the change, but I would like to hear from others too.

**Comment by revans2** [comment]
My only comment is that STORM-123 is a different JIRA associated with Nimbus HA.  Could you rename it to point to the JIRA you filed.

**Comment by 3Dragan** [comment]
Sure, my fault)

**Comment by Parth-Brahmbhatt** [comment]
+1.

**Comment by zhuoliu** [comment]
Looks good. I am +1.

**Comment by revans2** [comment]
Still +1

**Pull request merged**
