### PR TITLE
STORM-2268 Disable integration test for Travis CI build

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Please refer discussion thread (below link) for detail:
http://dev.storm.apache.narkive.com/73yPjLtn/discussion-disable-integration-test

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
This should be ported back to 1.x and 1.0.x branches.

**Comment by harshach** [comment]
@HeartSaVioR I am negative disabling this. I asked @raghavgautam to take a look. if we can't find a solution we can disable this.

**Comment by raghavgautam** [comment]
@HeartSaVioR I will take a look at why it is failing and fix it.

**Comment by harshach** [comment]
@raghavgautam  any update on this.

**Comment by raghavgautam** [comment]
@harshach I worked on this jira and found a few product issues. I worked with @HeartSaVioR and all these issues have been fixed & closed. The tests are running fine now. We only see one intermittent failure for which I have a potential fix.

@HeartSaVioR Do you want to close this pull request ?

**Comment by HeartSaVioR** [comment]
OK I'll close this. Thanks @raghavgautam for following up the issue.

**Pull request closed without merging**
