### PR TITLE
fix the dismatch between doc and code for read-all-supervisor-details

### PR DESCRIPTION
**Pull request by chuanlei**
fix the dismatch between doc and source code in function read-all-supervisor-details

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
You don't need to worry about test failures. It's random test failure which Storm struggles with.

**Comment by chuanlei** [comment]
what should I do so that this pr can be merged?

**Comment by HeartSaVioR** [comment]
I think you need to read https://github.com/apache/storm/blob/master/DEVELOPER.md to get familiar with contributing to Apache Storm Project.

You may want to read http://storm.apache.org/documentation/BYLAWS.html, too.

Btw, looks good to me.

**Comment by revans2** [comment]
@chuanlei Sorry this has taken so long.  The change looks good to me.  +1

@HeartSaVioR I don't think we need a JIRA for this, it is a minor documentation change.

**Comment by HeartSaVioR** [comment]
@revans2 
I didn't mean this PR needs a JIRA issue. I just guided @chuanlei to get familiar with contributing rule while waiting for committers to review. 
I wasn't a committer at that time, so I couldn't give +1. :)

**Comment by revans2** [comment]
@HeartSaVioR Sounds good.  Thanks by the way for all of the reviews before becoming a committer.  We need more people to keep up with all of the pull requests.

**Comment by HeartSaVioR** [comment]
@revans2 
Sure. The more, the better.
We(PMC members) are responsible for considering how to make Storm community more active.

**Comment by chuanlei** [comment]
@revans2 @HeartSaVioR 
Thank you very much. @HeartSaVioR has helped me a lot in the Storm topic. You can really patient and friendly to newbie to Storm.

**Comment by HeartSaVioR** [comment]
@chuanlei Thanks, it's my pleasure. :)

**Pull request merged**
