### PR TITLE
Fix storm-jms parent version (1.0.x)

### PR DESCRIPTION
**Pull request by HeartSaVioR**

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Since it's version issue, and it affects Travis CI build result, I will merge when Travis CI passes.

**Comment by HeartSaVioR** [comment]
All of builds passed and run into integration tests. #1715 needs to be ported back to 1.0.x-branch.

**Comment by HeartSaVioR** [comment]
Ported back #1715 and rebased and force pushed this.

**Comment by ptgoetz** [comment]
+1 Thanks for catching this @HeartSaVioR

**Comment by satishd** [comment]
+1

**Comment by HeartSaVioR** [comment]
Merged into 1.0.x branch.

**Pull request merged**
