### PR TITLE
Fix bug related to error handling in js multilang implementation

### PR DESCRIPTION
**Pull request by anyatch**

### CODE REVIEW

**Comment by d2r** [comment]
Hi @anyatch, is there an issue in JIRA for this pull request?

Also, I noticed there are various differences in the three storm.js files that are changed in this pull request.  Should all three of these files be exactly the same?

**Comment by d2r** [comment]
@anyatch any update?

**Comment by knusbaum** [comment]
@anyatch ping

**Comment by d2r** [comment]
@anyatch I will be closing this pull request for inactivity.  If this is in error, please re-open it, create a Jira for the work, and resolve current conflicts with the master branch.

**Pull request closed without merging**
