### PR TITLE
STORM-2413: Make new Kafka spout respect tuple retry limits

### PR DESCRIPTION
**Pull request by srdo**
Sorry about mixed diff, but https://github.com/apache/storm/pull/1924 had some changes I needed. Hopefully that one gets merged soon so the diff here is nicer. Only change from the other branch is https://github.com/srdo/storm/commit/86c39a349cdb053e1949ed1739feef0f6b2bcaf7

https://issues.apache.org/jira/browse/STORM-2413

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1 for srdo@86c39a3

**Comment by harshach** [comment]
@srdo can you squash some of those commits.

**Comment by srdo** [comment]
@harshach I'll rebase this when https://github.com/apache/storm/pull/1924 gets merged, it should be much more readable then.

**Comment by srdo** [comment]
Squashed and rebased onto https://github.com/apache/storm/pull/1924.

**Comment by HeartSaVioR** [comment]
@srdo 
+1
Sorry but could you rebase once more? I'd like to merge this in.

**Comment by srdo** [comment]
@HeartSaVioR Rebased

**Comment by HeartSaVioR** [comment]
+1 again.

**Pull request merged**
