### PR TITLE
STORM-2609: Simple command line DRPC Client

### PR DESCRIPTION
**Pull request by revans2**

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1

**Comment by vesense** [comment]
+1
We'd better add the new command to document. (Command-line-client.html)

**Comment by HeartSaVioR** [comment]
Agreed. @revans2 Could you update the doc to reflect the change?

**Comment by revans2** [comment]
@HeartSaVioR and @vesense I just updated the docs

**Comment by knusbaum** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
