### PR TITLE
STORM-943: In TestHiveBolt make the collector mock slightly more precise

### PR DESCRIPTION
**Pull request by dossett**
The OutputCollector passed to bolt.prepare() can be mocked directly instead of mocking an IOutputCollector used to construct the collector each time.  This makes the tests slightly more readable and it will be easier to verify more complex interactions with the collector in the future if needed.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by revans2** [comment]
+1
@dossett do you want to file a JIRA for this?  It is not a big deal because it is such a small change, but it does impact what type of credit you get for your changes.  No JIRA currently means it does not show up in the change log.  Which usually is not a big deal for doc changes, but is slightly more important for code changes.

**Comment by dossett** [comment]
Thanks for the feedback @revans2.  STORM-943 created and associated to this JIRA.

**Comment by dossett** [comment]
@revans2 Per your suggestion I did create a JIRA and associate it.  Feel free to merge this at your convenience.  Thanks!

**Comment by dossett** [comment]
@HeartSaVioR Could you merge this?  Thank you! :-)

**Comment by HeartSaVioR** [comment]
@dossett 
As you can see, there's no diff. Seems like it is already applied to master in any way.
Could you close this PR? Thanks!

**Comment by dossett** [comment]
@HeartSaVioR Will do, apologies for the oversight!

**Comment by HeartSaVioR** [comment]
Seems like STORM-938 contains this patch.
I'd like to recommend you to use branch so each pull request doesn't affect other pull request.

**Pull request closed without merging**
