### PR TITLE
[STORM-1927] upgrade to jetty 9

### PR DESCRIPTION
**Pull request by Ethanlm**
We need to upgrade to jetty latest version. The current jetty version is really old

### CODE REVIEW

**Comment by Ethanlm** [comment]
I don't know why the storm-core is waiting for so long and not yet started. 
https://travis-ci.org/apache/storm/builds/292621349

 However, the build on my repo https://travis-ci.org/Ethanlm/storm/builds/292621326 passed.

**Comment by revans2** [comment]
I am getting the UI crashing on startup, but with no stacktrace in the logs.  Could you look into it?

**Comment by Ethanlm** [comment]
Thanks @revans2  for pointing it out. I made stupid mistakes.  I am still fixing it.  Please don't merge yet.

**Comment by Ethanlm** [comment]
I fixed the bugs and tested it. It should be good now.

**Pull request merged**
