### PR TITLE
STORM-852 - Replaced Apache Log4j Logger with SLF4J API.

### PR DESCRIPTION
**Pull request by rmkellogg**

### CODE REVIEW

**Comment by revans2** [comment]
+1

**Comment by ptgoetz** [comment]
+1

**Comment by vesense** [comment]
+1

**Comment by HeartSaVioR** [comment]
LGTM.
Could we apply it to clj implementations?

**Comment by HeartSaVioR** [comment]
LGTM.
Removed last comment cause logviewer.clj uses log4j2 directly, not log4j.

**Pull request merged**
