### PR TITLE
[STORM-1519] - Storm syslog logging not confirming to RFC5426 3.1

### PR DESCRIPTION
**Pull request by jerrypeng**

### CODE REVIEW

**Comment by erikdw** [comment]
This seems like it could have a *major* impact on performance, no?   It's not clear to me what is so horrible in STORM-1519 that we need to force a disk write for every single log message.

**Comment by jerrypeng** [comment]
Well this only changes that config for the syslog appender.  The syslog appender writes data to a network socket.  This doesn't change the other appenders that will actually write to disk.

**Comment by jerrypeng** [comment]
If a user has a log parser that adheres to RFC5426, then how log4j2 is configured to write to syslog is a problem.

**Comment by erikdw** [comment]
@jerrypeng : ahhh.... thanks for the extra info, both points make sense. To be pedantic, that detail woulda been cool in the (empty :wink:) description.

**Comment by jerrypeng** [comment]
@erikdw the jira i filed contained more detailed information

https://issues.apache.org/jira/browse/STORM-1519

**Comment by erikdw** [comment]
@jerrypeng : heh, yep, I read the whole bug before my first reply.  And it had this note:
* "immediateFlush - When set to true - the default, each write will be followed by a flush. This will guarantee the data is written to disk but could impact performance."

And *that* is what scared me into replying actually!   The log4j2 docs should probably just be updated to "written to disk or network".

**Comment by revans2** [comment]
The change looks fine to me +1.

@erikdw do you have any other concerns about this?

**Comment by erikdw** [comment]
@revans2 : not at all!  I just misunderstood the implications, totally my bad.

**Pull request merged**
