### PR TITLE
STORM-1663: Stats couldn't handle null worker HB.   	STORM-1665: Worker cannot instantiate kryo     STORM-1666: Kill from the UI fails silently

### PR DESCRIPTION
**Pull request by revans2**

### CODE REVIEW

**Comment by knusbaum** [comment]
+1

**Comment by revans2** [comment]
@knusbaum please look again, just fixes STORM-1666 on this too, they are all related

**Comment by knusbaum** [comment]
Still +1 Pending SD

**Comment by abhishekagarwal87** [comment]
+1. It took me a while to figure out why the Objenesis exclusion is present in master, 0.10.x branch but not in 1.x-branch. @ptgoetz had already fixed this in 1.x while adding the changelog.

**Pull request merged**
