### PR TITLE
Corrected ConnectionPrvoider to ConnectionProvider

### PR DESCRIPTION
**Pull request by randerzander**
credit for finding the issue goes to @gbraccialli

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Seems like something is messed.

- https://github.com/apache/storm/pull/556
- https://github.com/Parth-Brahmbhatt/incubator-storm/commit/d268903f026cf275b72e6246b61c769d28fb3ed1

It was already fixed. Is it missed spot, or messed thing?

**Comment by HeartSaVioR** [comment]
My bad. Sorry, it seems to be just missed spot. ;)

**Comment by HeartSaVioR** [comment]
+1. 
Since it modifies method name, it should be applied to 0.10.0 to keep backward compatibility with 0.10.0 and 0.11.0.

**Comment by randerzander** [comment]
How do you want to handle the .10 update? Separate PR?

**Comment by HeartSaVioR** [comment]
Maybe cherry-pick would be enough since it contains only one commit.

**Comment by randerzander** [comment]
that's something you need to be comitter to do, right?

I'm not sure how to use one PR to commit to multiple branches.

**Comment by HeartSaVioR** [comment]
@randerzander Yes, right. I'll take care of it.

**Comment by HeartSaVioR** [comment]
@randerzander Thanks for the work, I merged into master and 0.10.x-branch.

**Pull request merged**
