### PR TITLE
 STORM-2867: Add consumer lag metrics to KafkaSpout

### PR DESCRIPTION
**Pull request by omkreddy**

### CODE REVIEW

**Comment by srdo** [comment]
There are checkstyle violations, you can find the list in storm-kafka-client/target/checkstyle-violations.xml. Other than that this looks good.

**Comment by omkreddy** [comment]
@srdo  Thanks for the review. Fixed the checkstyle issues.

**Comment by srdo** [comment]
Thanks, this looks good. 

+1, if you squash to one commit we should be able to merge soon. Please also squash the 1.x version.

**Comment by omkreddy** [comment]
@srdo  squashed the  commits.

**Comment by arunmahadevan** [comment]
@omkreddy , thanks for the patch. +1

**Comment by srdo** [comment]
I believe we don't need to wait 24 hours since this is just port work. Will merge shortly.

**Pull request merged**
