### PR TITLE
STORM-1569: Adding option in nimbus to specify request queue size in …

### PR DESCRIPTION
**Pull request by Parth-Brahmbhatt**
…config.

### CODE REVIEW

**Comment by wuchong** [comment]
+1  LGTM

**Comment by satishd** [comment]
+1

**Comment by abhishekagarwal87** [comment]
LGTM

**Comment by knusbaum** [comment]
+1

**Comment by knusbaum** [comment]
@Parth-Brahmbhatt I merged this and resolved the jira, but the the jira's resolved version was listed as 1.0. I changed it to 2.0, but do we want to backport this to 1.0 as well?

**Comment by Parth-Brahmbhatt** [comment]
@knusbaum I think we should. WE have see RejectedExecutionException on > 5 different customer clusters. I can backport this if others also agree.

**Comment by knusbaum** [comment]
@Parth-Brahmbhatt I'll just go ahead and merge it. It is a very small change and was already marked for 1.0.

**Pull request merged**
