### PR TITLE
STORM-1773 (1.x) Utils.javaDeserialize() doesn't work with primitive types

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* upgrade commons-io from 2.4 to 2.5 to resolve IO-378

Fix for master: #1411

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
It should be backported to 1.0.x-branch. 
Btw, Github mirror doesn't catch up new branch on ASF repo. Should I push dummy commit to 1.0.x-branch?

**Comment by harshach** [comment]
+1

**Comment by HeartSaVioR** [comment]
Thanks for reviewing @harshach. Could you review #1411 too?

**Comment by satishd** [comment]
+1

**Pull request merged**
