### PR TITLE
STORM-2320: DRPC client printer class reusable for local and remote DRPC

### PR DESCRIPTION
**Pull request by hmcl**
- Client necessary to check for DRPC results while running in distribute mode

### CODE REVIEW

**Comment by hmcl** [comment]
@harshach as requested, this is the 1.x-branch version of the patch merged into master

**Comment by HeartSaVioR** [comment]
@hmcl Could you rebase this?

**Comment by hmcl** [comment]
@HeartSaVioR done

**Comment by HeartSaVioR** [comment]
+1 Thanks!

**Pull request merged**
