### PR TITLE
[STORM-2410]modify Trident-state.md

### PR DESCRIPTION
**Pull request by liu-zhaokun**
[https://issues.apache.org/jira/browse/STORM-2410](url)
The sentence, "(One side note – once Kafka supports replication, it will be possible to have transactional spouts that are fault-tolerant to node failure, but that feature does not exist yet.)" ,should be removed,because Kafka has supported replication.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1
Please clean up your commits. I think only a commit is sufficient.

**Comment by liu-zhaokun** [comment]
Hello,@HeartSaVioR 
It's not easy to clean up the commits.And there is only one file changed in the end.Is it necessary to clean up the commits?

**Comment by liu-zhaokun** [comment]
Hello,@HeartSaVioR
Need I create a new PR to clean the commits?But you can merge the PR with only one file changed,isn't that acceptable?

**Comment by HeartSaVioR** [comment]
@liu-zhaokun 
Sorry I missed this PR. AFAIK, only cherry-picking `6cf2ffb` will cover this, right?
You need to close this PR after merging since Github doesn't support auto close against non-master branch.

**Comment by liu-zhaokun** [comment]
@HeartSaVioR 
Yes,only cherry-picking 6cf2ffb is effective.Would you merge this PR soon?I will close this PR after merging manually.Thanks for your reply.

**Comment by HeartSaVioR** [comment]
Cherry-picked via 4f4c7b4fb8992f879cbbe76cb328c4e13b89b07e

@liu-zhaokun Thanks for contribution. You can close the PR.

**Comment by liu-zhaokun** [comment]
@HeartSaVioR
Have you merged it to apache storm?Why can't I see the "Assignee" assigned to me in [issues](https://issues.apache.org/jira/browse/STORM-2410) ?

**Comment by HeartSaVioR** [comment]
@liu-zhaokun 
Sorry I forgot. Just handled. I added you to the contributor list, so now you can assign issue to yourself.

**Pull request closed without merging**
