### PR TITLE
STORM-996: netty-unit-tests/test-batch demonstrates out-of-order delivery

### PR DESCRIPTION
**Pull request by knusbaum**
Netty calls notifyInterestChanged which causes a race condition in flushMessages.

### CODE REVIEW

**Comment by d2r** [comment]
+1 This seems to fix the issue. I ran test-batch ~50 times without a failure.

**Comment by kishorvpatil** [comment]
LGTM. +1

**Comment by HeartSaVioR** [comment]
+1
Great! Missed StormClientHandler so there's only one thread which accesses to Client at any time.

**Comment by ptgoetz** [comment]
+1 Nice work.

**Pull request merged**
