### PR TITLE
STORM-512 KafkaBolt doesn't handle ticks properly

### PR DESCRIPTION
**Pull request by nielsbasjes**
I implemented this by 
1.   Adding an 'boolean isTick()' method to the Tuple interface. 
       This way it is for application builders much easier to  determine if the tuple at hand is a Tick or not.
2.   Letting the KafkaBolt use that method to ignore the ticks.
3.   Updating the other place in the code base that handles ticks differently to use this new method.

### CODE REVIEW

**Comment by revans2** [comment]
The changes look find to me I am +1 for merging this in.

@nathanmarz I would like to get your opinion on this before merging it in, because you had the original reservations about the patch.

**Comment by nielsbasjes** [comment]
@nathanmarz / @revans2 What must I do/change to get this solution committed?

**Comment by revans2** [comment]
@nathanmarz any update on your opinion of this.  Your original concerns were addressed, and I feel we should check this in.  If I don't hear back soon I'll assume that it is OK.  This patch has languished far too long.

**Comment by revans2** [comment]
@nathanmarz I merged this in, but if you feel that there is something wrong with it still I am happy to adjust it on a follow on JIRA, or revert it if it is truly critical.

**Comment by miguno** [comment]
Since KafkaBolt is extending BaseRichBolt, I think we should perform a `collector.ack(input)` before `return`.  Tick tuples must be acked like "normal" tuples.

```
public class KafkaBolt<K, V> extends BaseRichBolt {

    public void execute(Tuple input) {
        if (TupleUtils.isTick(input)) {
          return; // Do not try to send ticks to Kafka
        }
        ...
    }
```

**Comment by miguno** [comment]
I created [STORM-786](https://issues.apache.org/jira/browse/STORM-786) to track the tick tuple acking.  Pull request is already sent.

**Comment by nielsbasjes** [comment]
I had this ack for the tick in there in an earlier version of the change.
Then I asked on the mailing list if this ack is needed and I was told that it is not required.
http://mail-archives.apache.org/mod_mbox/storm-user/201411.mbox/%3CCAAognGZ1pEt0RfKXn+sSeo+djy38LKQ4e3gw1GBn-WmMqWk9YQ@mail.gmail.com%3E
So I took it out. 

Just to understand: Is ackibg a tick needed?

**Comment by miguno** [comment]
My understanding is yes, you do need to ack tick tuples.  See @nathanmarz [comment](https://groups.google.com/forum/#!topic/storm-user/ZEJabXT5nQA) from some time back:

>> Do I need to ack tick tuples?  Since they're system generated I'm think yes but I'm not sure.
>
> Nathan's answer: You should ack all tuples.

**Comment by nathanmarz** [comment]
I didn't get a notification that you were pinging me – but fwiw I'm +1 on it

**Pull request merged**
