### PR TITLE
[STORM-1347] display topology version on UI

### PR DESCRIPTION
**Pull request by Ethanlm**
Display topology version on UI.

see: https://issues.apache.org/jira/browse/STORM-1347

### CODE REVIEW

**Comment by Ethanlm** [comment]
image

**Comment by HeartSaVioR** [comment]
Actually this issue is the subtask of topology online update, and topology version is expected to be set automatically to the increasing number.
But I also think this patch doesn't hurt in any way. When we support online update and have version, we can just overwrite `topology.version` only if user doesn't set custom version string.
Moreover, supporting version as label looks like good idea indeed.

+1 on this. Thanks @Ethanlm

**Comment by Ethanlm** [comment]
Thanks for review @HeartSaVioR

**Comment by HeartSaVioR** [comment]
@Ethanlm 
Sorry there's merge conflict now. Could you resolve this?
You may want to just regenerate classes from thrift since the conflict occurs from generated files.

**Comment by Ethanlm** [comment]
Thanks @HeartSaVioR  Regenerated them

**Comment by Ethanlm** [comment]
storm-cassandra failed. Should be not related to this PR.

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
