### PR TITLE
STORM-2555 handle impersonation properly for HBase delegation token

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Please refer [STORM-2555](http://issues.apache.org/jira/browse/STORM-2555) for more details.

There had been code block for handling impersonation, but actually it didn't work.

Please review and comment, thanks in advance.

PR for 1.x branch: #2171

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
This can be cherry-picked via 1.x-branch.

**Comment by HeartSaVioR** [comment]
master and 1.x-branch are diverged due to STORM-2556.
Just raised PR for 1.x-branch (#2171) and will rebase the PR.

**Comment by HeartSaVioR** [comment]
Rebased.

**Comment by HeartSaVioR** [comment]
Also addressed review comments from 1.x branch.

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
I think the changeset is same as #2171 except fixing some styles. Could you review this as well?

**Comment by arunmahadevan** [comment]
+1 LGTM

**Pull request merged**
