### PR TITLE
STORM-2185: Storm Supervisor doesn't delete directories properly sometimes - 1.x branch

### PR DESCRIPTION
**Pull request by knusbaum**

### CODE REVIEW

**Comment by revans2** [comment]
+1 the travis failure looks unrelated to this change.

**Comment by revans2** [comment]
As a note to whoever merges this in we should merge this to 1.0.x too.

**Comment by HeartSaVioR** [comment]
+1 Commit message should be modified but can be handled while merging. (Same as PR for master)

**Comment by HeartSaVioR** [comment]
@knusbaum I merged 1.x and 1.0.x branch. Could you close this PR? Auto-closing PR doesn't work with PR which is not against master branch.

**Comment by knusbaum** [comment]
@HeartSaVioR Are you using harshach's script to merge these?

**Comment by HeartSaVioR** [comment]
@knusbaum No I manually did it. I have been creating branch even cherry-picking for backporting.

**Comment by revans2** [comment]
@knusbaum if this is merged in could you please close this?

**Pull request closed without merging**
