### PR TITLE
add hadoop-common dependency in README for storm-hdfs

### PR DESCRIPTION
**Pull request by mazhechao**
If hadoop-common is not included in pom.xml since storm-hdfs 1.0.0, we will get runtime errors. README should mention that.

`
java.lang.NoClassDefFoundError: org/apache/hadoop/fs/CanUnbuffer at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:800) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) at java.net.URLClassLoader.access$100(URLClassLoader.java:71) at java.net.URLClassLoader$1.run(URLClassLoader.java:361) at java.net.URLClassLoader$1.run(URLClassLoader.java:355) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:354) at java.lang.ClassLoader.loadClass(ClassLoader.java:425) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) at java.lang.ClassLoader.loadClass(ClassLoader.java:358) at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149) at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2596) at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91) at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630) at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612) at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370) at org.apache.storm.hdfs.bolt.HdfsBolt.doPrepare(HdfsBolt.java:95) at org.apache.storm.hdfs.bolt.AbstractHdfsBolt.prepare(AbstractHdfsBolt.java:119) at org.apache.storm.daemon.executor$fn__7953$fn__7966.invoke(executor.clj:792) at org.apache.storm.util$async_loop$fn__625.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.CanUnbuffer at java.net.URLClassLoader$1.run(URLClassLoader.java:366) at java.net.URLClassLoader$1.run(URLClassLoader.java:355) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:354) at java.lang.ClassLoader.loadClass(ClassLoader.java:425) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ... 24 more
`

### CODE REVIEW

**Comment by mazhechao** [comment]
@ptgoetz Will you have a look at it?

**Comment by mazhechao** [comment]
@dossett Will you have a look?

**Comment by dossett** [comment]
@mazhechao You are saying that using the hdfs-bolt without including that dependency throws the class not found?

**Comment by mazhechao** [comment]
Yes.

**Comment by mazhechao** [comment]
@dossett Yes. Somebody asked this in storm-user maillist in February this year.

**Comment by HeartSaVioR** [comment]
@mazhechao Could you please add hadoop-auth, too? Thanks in advance!

**Comment by HeartSaVioR** [comment]
And filing a new JIRA would be ideal.

**Comment by mazhechao** [comment]
@HeartSaVioR Is hadoop-auth necessary?

**Comment by HeartSaVioR** [comment]
I'm not clearly saying that it is, but hadoop-auth is added at pom.xml now and it also refers to same version so version of hadoop-auth also should be changed when users want to exclude and replace version of hadoop dependencies.

**Pull request closed without merging**
