### PR TITLE
[STORM-3044] AutoTGT should check if a TGT is address-less and reject if it's not

### PR DESCRIPTION
**Pull request by Ethanlm**
https://issues.apache.org/jira/browse/STORM-3044

### CODE REVIEW

**Comment by Ethanlm** [comment]
The failures should be unrelated. The build succeeded on my repo https://travis-ci.org/Ethanlm/storm/builds/371698263

**Comment by Ethanlm** [comment]
@HeartSaVioR  Sorry I forgot to change it. I don't see any merge button. Do I need to do it in some other way

**Comment by HeartSaVioR** [comment]
@Ethanlm 
You can refer the DEVELOPER doc which guides contributors as well as committers. 
https://github.com/apache/storm/blob/master/DEVELOPER.md#merge-a-pull-request-or-patch
You would want to read BYLAWS for Storm project as well: http://storm.apache.org/contribute/BYLAWS.html

Please keep in mind we need to wait for 24hrs to merge code change. :) So you would like to try it out after 5 hours later.

**Comment by Ethanlm** [comment]
@HeartSaVioR  Thanks very much!

**Pull request merged**
