### PR TITLE
STORM-694: java.lang.ClassNotFoundException: backtype.storm.daemon.common.SupervisorInfo

### PR DESCRIPTION
**Pull request by duke-bartholomew**
Exception in thread "main" java.lang.ClassNotFoundException: backtype.storm.daemon.common.SupervisorInfo, compiling:(supervisor.clj:16:1)

### CODE REVIEW

**Comment by caofangkun** [comment]
@duke-bartholomew 
Does this still a issue? 
See  SupervisorInfo has already be imported at : 
https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/daemon/supervisor.clj#L21

**Comment by duke-bartholomew** [comment]
@caofangkun 
I just tried again on the latest master branch, and sadly enough, yes the issue is still there.
When executing 'mvn package' or 'mvn test' I still get the same error : 
```
Exception in thread "main" java.lang.ClassNotFoundException: backtype.storm.daemon.common.SupervisorInfo, compiling:(supervisor.clj:16:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558)
	at clojure.lang.Compiler.compile1(Compiler.java:7226)
	at clojure.lang.Compiler.compile1(Compiler.java:7216)
	at clojure.lang.Compiler.compile(Compiler.java:7292)
	at clojure.lang.RT.compile(RT.java:398)
	at clojure.lang.RT.load(RT.java:438)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$compile$fn__5071.invoke(core.clj:5652)
	at clojure.core$compile.invoke(core.clj:5651)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.Compile.main(Compile.java:
```

**Comment by caofangkun** [comment]
@duke-bartholomew 
It works very well  when I try to reproduce this issue:
```
   git clone https://github.com/apache/storm.git  
   cd storm 
   mvn package -Dmaven.test.skip=true 
```

**Comment by duke-bartholomew** [comment]
@caofangkun 
indeed, you are right.  If I start from a new clone, it seems to work.
Thanks for your reply!

It still confuses me though why this is not working when I pull _master_ on my already cloned storm repo.
But that's most probably a problem on my side then.

**Comment by knusbaum** [comment]
You're including `common` twice, once on line 29, and once on line 18.

The real solution is to remove the import of `[backtype.storm.daemon.common SupervisorInfo]` and use the record constructor `(->SupervisorInfo ...)` rather than the Java constructor `(SupervisorInfo. ...)` on line 504.

**Comment by duke-bartholomew** [comment]
@knusbaum Thanks for the input :+1:

**Comment by d2r** [comment]
@duke-bartholomew , Seems STORM-694 was closed because #492 was merged in.  Should this pull request be closed?

**Pull request closed without merging**
