### PR TITLE
STORM-2736: fix o.a.s.b.BlobStoreUtils [ERROR] "Could not update the blob with key"

### PR DESCRIPTION
**Pull request by hmcc**
Connected to https://issues.apache.org/jira/browse/STORM-2736.
Check for empty nimbus info list before attempting to update the blobstore.

### CODE REVIEW

**Comment by hmcc** [comment]
Thanks! I'll work on a separate PR for master.

**Comment by hmcc** [comment]
`master` PR: https://github.com/apache/storm/pull/2323

When I was doing that, I noticed that the spacing in the log message had already been fixed more nicely there, so https://github.com/apache/storm/pull/2320/commits/d812b6af7b31feadbc2a79f61926fc3774b593c0 changes mine to match.

I also noticed that the tests didn't test everything I'd wanted to test and had some whitespace that didn't belong, so those have been [updated too](https://github.com/apache/storm/pull/2320/commits/f0f21bf9acbed631d621a3f95d59eb70f63efc41).

I'll squash before merging.

**Comment by HeartSaVioR** [comment]
+1

**Comment by hmcc** [comment]
Rebased & squashed.

**Comment by revans2** [comment]
Still +1

**Pull request merged**
