### PR TITLE
STORM-1096: Fix some issues with impersonation on the UI

### PR DESCRIPTION
**Pull request by revans2**
Conflicts:
	storm-core/src/clj/backtype/storm/ui/core.clj

### CODE REVIEW

**Comment by revans2** [comment]
The test failure was the intermittent kafka issue.

**Comment by kishorvpatil** [comment]
+1. Good catch.

**Comment by d2r** [comment]
+1

**Comment by HeartSaVioR** [comment]
I found that I made a mistake while backporting. At least bin/storm.py should be fixed.

**Pull request merged**
