### PR TITLE
STORM-203 Adding paths to default java library path

### PR DESCRIPTION
**Pull request by picadoh**
Adding /usr/lib64 and /usr/lib/x86_64-linux-gnu to default java library path

### CODE REVIEW

**Comment by knusbaum** [comment]
/usr/lib64 is FHS standard. /usr/lib/x86_64-linux-gnu is Debian-specific. I think we should avoid setting distro-specific defaults.

**Comment by picadoh** [comment]
yeah, makes total sense 👍 removed it from the path. thanks @knusbaum

**Comment by revans2** [comment]
@knusbaum are you OK with the change?

I am +1

**Comment by knusbaum** [comment]
+1

**Pull request merged**
