### PR TITLE
[STORM-1215] Use Asynchronous logger for improving performance.

### PR DESCRIPTION
**Pull request by kishorvpatil**
The changes to loggers for all daemons and workers.
- Turn off immediateFlush.
- Enable async logging.
- Turn off Immediate Fail for log events on syslog logger to avoid making blocking call without timeout.

### CODE REVIEW

**Comment by d2r** [comment]
This also switches to UTF-8 encoding for syslog, for compatibility.  We have seen issues with this in the past.

Evidently we cannot configure the context except via a System property, so looks OK to me.

+1

**Comment by revans2** [comment]
The log level changes on the UI still work, and performance seems fine too, but if I enable topology.debug I am seeing some very odd things that I would like to explore some more.

**Comment by revans2** [comment]
+1 I just tested and the workers are no longer crashing, but it might be good to set immediateFlush="false" in the worker.

**Comment by kishorvpatil** [comment]
@revans2  Turned off immediateFlush for worker.

**Comment by revans2** [comment]
+1 looks good to me

**Comment by revans2** [comment]
@d2r any other comments on the most recent changes?

**Comment by d2r** [comment]
Looks good to me +1

**Comment by rajeshksv** [comment]
You mean Turn ON Immediate Fail right ?

**Pull request merged**
