### PR TITLE
STORM-850 Convert storm-core's logback-test.xml to log4j2-test.xml

### PR DESCRIPTION
**Pull request by HeartSaVioR**
In order to prevent Travis CI complaining about log exceeding, we need to apply this.

Please review and comment. Thanks in advance!

### CODE REVIEW

**Comment by revans2** [comment]
+1

**Comment by d2r** [comment]
+1, and it seems this should be merged in together with https://github.com/apache/storm/pull/562

**Comment by revans2** [comment]
This is just config changes, not code and it is only for testing so I am going to merge this in without waiting the full 24 hours.  If others object I will be happy to revert the changes.

**Comment by ptgoetz** [comment]
+1 No objections for merging.

**Pull request merged**
