### PR TITLE
[STORM-1875]Separate Jedis/JedisCluster Config

### PR DESCRIPTION
**Pull request by darionyaphet**
[STORM-1875](https://issues.apache.org/jira/browse/STORM-1875)

Separate Jedis / JedisCluster to provide full operations for each environment to users .

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
The problem is actually not simple. The blocking point is JedisCommands interface, not config.
JedisCommands exposes operations which use only single key. Since some multiple keys operations of Redis is not suitable for Redis Cluster (operation is available but not making sense), Jedis and JedisCluster takes different interfaces, which blocks us to provide unified interface from storm-redis side.

One simple way is separating existing classes to RedisLookupBolt / RedisClusterLookupBolt, RedisStoreBolt / RedisClusterStoreBol, as State/MapState did, but it incurs backward incompatibility if users use RedisLookupBolt / RedisStoreBolt to access Redis Cluster.

**Comment by HeartSaVioR** [comment]
One other way without breaking compatibility but not beauty is adding some utility methods to AbstractRedisBolt like, 

```
public JedisCluster asJedisCluster(JedisCommands instance) throws IllegalArgumentException
public JedisCluster asJedis(JedisCommands instance) throws IllegalArgumentException
```

and let users convert their JedisCommands instance to actual type before using full features.

**Comment by darionyaphet** [comment]
Both `Jedis` and `JedisCluster ` have implemented `JedisCommands` interface . So I think we can use `JedisCommands` calling the same method on single redis instance and redis cluster . 

Just use `JedisConfig` to control instance `JedisContainer` or `JedisCommandsInstanceContainer` maybe a good idea and support two difference interface is useless :P

**Comment by HeartSaVioR** [comment]
@darionyaphet 
This is Jedis class diagram when Jedis was 2.5.0. At that time JedisCluster doesn't support multiple keys operation so now it becomes more complicated.
https://lh5.googleusercontent.com/-kMPsNHe6t2I/U0Dn01HxIoI/AAAAAAAAt4U/U8I0j570rI4/s3200/Jedis+Class+Diagram+without+fields_methods.jpg

DISCLAIMER: I'm also a committer of Jedis. :)

**Comment by darionyaphet** [comment]
@HeartSaVioR Good !  I will try to split into two class . BTW Do you have any idea to unified `Jedis` and `JedisCluster` interface ?

**Comment by darionyaphet** [comment]
`Storm-Redis` have support multiple keys operation ?

**Comment by HeartSaVioR** [comment]
No for predefined operations (StoreBolt, LookupBolt) but we can still support full features for AbstractRedisBolt and let users extend this class.

**Comment by darionyaphet** [comment]
OK , I will try to separating classes :D

**Pull request closed without merging**
