### PR TITLE
[STORM-1908] Support Storm HBase ZooKeeper Config

### PR DESCRIPTION
**Pull request by darionyaphet**
[STORM-1908](https://issues.apache.org/jira/browse/STORM-1908)

Support Storm HBase ZooKeeper Config . About ZooKeeper host , port and parent .

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Since we override all options being provided from HBase config, these three parameters can be fed as well. I think just removing TODO would be fine.

**Comment by darionyaphet** [comment]
@HariSekhon what you mean is should remove `TODO` when all HBase options have provided ?

**Comment by HariSekhon** [comment]
@darionyaphet wrong @ person?

**Comment by darionyaphet** [comment]
@HariSekhon Yep  So sorry ~

**Comment by HeartSaVioR** [comment]
@darionyaphet 
I mean we already support the thing what TODO describes. 
Please refer https://github.com/apache/storm/blob/master/external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/AbstractHBaseBolt.java#L66-L68

So this issue is invalid, and TODO can be removed.

**Comment by darionyaphet** [comment]
@HeartSaVioR  I got we can set config using `Config` and don't have to support new API ?

**Comment by HeartSaVioR** [comment]
@darionyaphet 
You can set properties which we can pass to hbase-*.xml into Storm configuration Map (under specific key for hbase), and storm-hbase merges (override) that configuration with default HBase configuration which reads hbase-*.xml to initialize. So passing them to Storm configuration Map before submitting topology would be sufficient.

**Comment by darionyaphet** [comment]
@HeartSaVioR Yes I know . Because Zookeeper properties is very useful , so I wish to open a new API to support it :) . If you think it's unnecessarily , I will close this PR .

**Comment by HeartSaVioR** [comment]
@darionyaphet Let's close for now. We can enrich description to README how to pass ZK properties when we think it would be better to guide passing ZK properties.

**Comment by darionyaphet** [comment]
@HeartSaVioR   OK  Close it :)

**Pull request closed without merging**
