### PR TITLE
[STORM-1217] - making small fixes in RAS

### PR DESCRIPTION
**Pull request by jerrypeng**

### CODE REVIEW

**Comment by revans2** [comment]
The bug fixes look good, but could you file a JIRA just to track that these fixes went in?

**Comment by jerrypeng** [comment]
@revans2 will fill a JIRA to track

**Comment by zhuoliu** [comment]
+1

**Comment by kishorvpatil** [comment]
+1

**Comment by kishorvpatil** [comment]
still +1

**Comment by jerrypeng** [comment]
@kishorvpatil can we merge it now?

**Comment by d2r** [comment]
Merging this since comments are address, >= 2 +1's, one by PMC.

**Pull request merged**
