### PR TITLE
STORM-2078: enable paging in worker datatable

### PR DESCRIPTION
**Pull request by abellina**
This can get cherry-picked to 1.x

### CODE REVIEW

**Comment by revans2** [comment]
+1

**Comment by abellina** [comment]
@revans2 I moved the call to my function that checks for whether the worker components should show or not to a callback that triggers on each render of the datatable. I noticed a bug where filtering would cause odd behavior... this fixes it.

**Comment by ppoulosk** [comment]
+1, NB

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
