### PR TITLE
STORM-1020 - Added Javadoc to Fields and ITuple.

### PR DESCRIPTION
**Pull request by rmkellogg**
Broke combined PR into distinct branches.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@rmkellogg 
+1 Could you upmerge?
Hint: Modifying CHANGLOG.md would make conflicts.

**Comment by rmkellogg** [comment]
Having difficulties with merge operation.  Pardon me.

**Comment by HeartSaVioR** [comment]
OK, then I'll merge this by cherry-picking c2fa25f.

**Comment by rmkellogg** [comment]
Thank you.  Will try to make it easier next time.

**Comment by HeartSaVioR** [comment]
@rmkellogg I merged into master by cherry-picking. Could you close this PR?

**Pull request closed without merging**
