### PR TITLE
STORM-1156: Link Developer.md doc to the contributing page

### PR DESCRIPTION
**Pull request by tgravescs**
https://issues.apache.org/jira/browse/STORM-1156

### CODE REVIEW

**Comment by tgravescs** [comment]
jdk8 build succeeded, jdk7 had unit test failure that isn't related to this change.

**Comment by revans2** [comment]
+1 looks good

**Comment by revans2** [comment]
@tgravescs looks like I was confused about how the documentation is working now.  Could you update your request to go off of the asf-site branch instead of master?  I know it is a little odd, but for now that is where the code is.

**Comment by tgravescs** [comment]
moved to: https://github.com/apache/storm/pull/867

**Pull request closed without merging**
