### PR TITLE
[STORM-1671]-1.x Enable logviewer to delete directory with no yaml file

### PR DESCRIPTION
**Pull request by zhuoliu**
Apply [https://github.com/apache/storm/pull/1285] to 1.x-branch

### CODE REVIEW

**Comment by zhuoliu** [comment]
@HeartSaVioR this is for 1.x, just one line difference from the patch to master.

**Comment by zhuoliu** [comment]
@ptgoetz , thanks for applying this one to 1.x already. One minor concern is that the change to logviewer_test.clj is not included.

**Comment by ptgoetz** [comment]
@zhuoliu Yep, just caught that now and applied. Running tests and will commit shortly.

**Comment by zhuoliu** [comment]
@ptgoetz, nice, then I will close this one.

**Comment by zhuoliu** [comment]
Taylor has applied this patch to 1.x.

**Pull request closed without merging**
