### PR TITLE
STORM-3071: change checkstyle plugin setting logViolationsToConsole t…

### PR DESCRIPTION
**Pull request by krichter722**
…o true

- Logging checkstyle violations to console which is now possible since all violations have been fixed
- Remove unnecessary maxAllowedViolations from configurations of projects

Note: The removal of maxAllowedViolations in the server project is covered in #3050 which needs to be merged before.

### CODE REVIEW

**Comment by d2r** [comment]
I took a look at #3050 . We can come back to this once the former's changes are merged.

**Comment by Ethanlm** [comment]
It looks nice. Will come back to this once #3050 is merged

**Comment by Ethanlm** [comment]
#3050 is now merged. Could you please rebase this so we can get this in to? Thanks again for the efforts

**Comment by Ethanlm** [comment]
The failed test doesn't seem related 
```
[INFO] Running org.apache.storm.daemon.drpc.DRPCTest
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.038 s <<< FAILURE! - in org.apache.storm.daemon.drpc.DRPCTest
[ERROR] testGoodBlocking  Time elapsed: 0.012 s  <<< ERROR!
java.util.concurrent.TimeoutException
```

**Pull request merged**
