### PR TITLE
STORM-3068: STORM_JAR_JVM_OPTS are not passed to storm-kafka-monitor …

### PR DESCRIPTION
**Pull request by rajkrrsingh**
added STORM_JAR_JVM_OPTS to java command in storm-kafka-monitor file to pass java configuration

### CODE REVIEW

**Comment by priyank5485** [comment]
@rajkrrsingh Is the presumption that STORM_JAR_JVM_OPTS will be set? Have you checked if its okay when the variable is not set? Can you add it to README as well regarding this change?

**Comment by rajkrrsingh** [comment]
@priyank5485 I actually verified that STORM_JAR_JVM_OPTS is not propagating to the java args, the test I ran to confirm is 

without the change java command look like
```
+ exec /usr/jdk64/jdk1.8.0_112/bin/java -cp /usr/hdp/2.6.2.0-205/storm/toollib/storm-kafka-monitor-1.1.0.2.6.2.0-205.jar org.apache.storm.kafka.monitor.KafkaOffsetLagUtil
```

while with the change and setting STORM_JAR_JVM_OPTS=-Xmx1024m the command look like
```
+ exec /usr/jdk64/jdk1.8.0_112/bin/java -Xmx1024m -cp /usr/hdp/2.6.2.0-205/storm/toollib/storm-kafka-monitor-1.1.0.2.6.2.0-205.jar org.apache.storm.kafka.monitor.KafkaOffsetLagUtil
```

**Comment by priyank5485** [comment]
@rajkrrsingh When you say STORM_JAR_JVM_OPTS is not propagating to the java args, where is it not propagating from? I don't see it being set anywhere in this script. And i see that its sourcing the storm-env.sh script. So i was just suggesting just adding a check like we have for JAVA_HOME to handle case where its not defined.

**Comment by priyank5485** [comment]
+1(NB)

**Pull request merged**
