### PR TITLE
STORM-1381:Adding client side submission hook along with LocalCluster…

### PR DESCRIPTION
**Pull request by Parth-Brahmbhatt**
… changes to run tets.

Conflicts:
	storm-core/src/jvm/backtype/storm/Config.java

Topology hook should work in local mode too.

LocalCluster changes to run nimbus thrift server.

StormSubmitter hook changes along with LocalCluster changes to run tets.

Conflicts:
	storm-core/src/clj/backtype/storm/daemon/nimbus.clj
	storm-core/src/jvm/backtype/storm/StormSubmitter.java
	storm-core/src/jvm/backtype/storm/utils/Utils.java

### CODE REVIEW

**Comment by Parth-Brahmbhatt** [comment]
the local cluster changes should be credited to @harshach

**Comment by harshach** [comment]
+1

**Comment by 2new** [comment]
+1

**Comment by knusbaum** [comment]
+1 Unit tests pass locally.

**Pull request merged**
