### PR TITLE
Adding hdfs-conf.yaml to all test cases to support security.

### PR DESCRIPTION
**Pull request by csivaguru**

### CODE REVIEW

**Comment by csivaguru** [comment]
@harshach @hmcl @HeartSaVioR Can I get a review on this change?

**Comment by HeartSaVioR** [comment]
@csivaguru Could you file an issue and link it? I think it's not trivial fix so we would want to track.

**Comment by HeartSaVioR** [comment]
@csivaguru Missing one more thing, you need to submit pull request against master unless there's specific reason to not do. You may want to submit additional pull requests against version branches if it needs to resolve conflicts.

**Comment by csivaguru** [comment]
I have created a PR against 1.x-branch. I am closing this PR.
https://github.com/apache/storm/pull/1511

**Pull request closed without merging**
