### PR TITLE
Quick fix: correcting markdown format

### PR DESCRIPTION
**Pull request by Ethanlm**
A really trivial fix

### CODE REVIEW

**Comment by vesense** [comment]
Thanks @Ethanlm Merged into master.

**Comment by hmcl** [comment]
@Ethanlm can you please "Quick Fix" with "MINOR: " Thanks.
+1 after fixing the commit message.

**Comment by Ethanlm** [comment]
@hmcl  This is merged already. Is it possible to change the commit message?

**Comment by hmcl** [comment]
@Ethanlm yeah, I noticed it right after my comment. Somehow I had not refreshed my PRs view. If it is easy I will change the commit message since I am about to merge something. Otherwise we will just leave it.

**Comment by Ethanlm** [comment]
@hmcl  Thanks. Will use "MINOR:" next time

**Pull request merged**
