### PR TITLE
[STORM-1895] Blob Store replication-factor argument

### PR DESCRIPTION
**Pull request by darionyaphet**
[STORM-1895](https://issues.apache.org/jira/browse/STORM-1895)

Storm command line argument --repl-fctr have update to replication-factor and update the document .

Replace repl-fctr with replication-factor

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
@darionyaphet can you add jira id in the commit. Looks good otherwise

**Comment by satishd** [comment]
+1

**Comment by darionyaphet** [comment]
@abhishekagarwal87  Should I update commit message to `STORM-1895 	: replace repl-fctr with replication-factor` ?

**Comment by HeartSaVioR** [comment]
@darionyaphet Yes, or `STORM-1895: blobstore replication-factor argument` as title and `replace repl-fctr with replication-factor` as description is also fine for me.

**Comment by darionyaphet** [comment]
@HeartSaVioR Thanks commit message same with JIRA title maybe better :)

**Comment by HeartSaVioR** [comment]
@darionyaphet 
FYI: You don't need to close your pull request. You can `git rebase -i HEAD~1` and modify `pick` to `reword` and save & exit, and modify your commit message for last commit. After rebasing you can force push your rebased changes by using force parameter `--force`.
Please refer this article: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by darionyaphet** [comment]
@HeartSaVioR just a miss operation .. btw I couldn't reopen this ?

**Comment by HeartSaVioR** [comment]
You can normally reopen your pull request, but AFAIK, if you delete your branch and push your changes, you can't reopen pull request.

**Comment by darionyaphet** [comment]
@HeartSaVioR Thanks ~~ I have update commit message to JIRA title

**Comment by abhishekagarwal87** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
