### PR TITLE
[STORM-1413] remove unused variables for some tests

### PR DESCRIPTION
**Pull request by vesense**
fix backtype/storm/localizer/LocalizerTest.java

### CODE REVIEW

**Comment by harshach** [comment]
@vesense thanks for these fixes but please send these PRs under 1 jira.

**Comment by vesense** [comment]
@harshach  Thanks. I will fix it.

**Comment by vesense** [comment]
@harshach Done.

**Comment by vesense** [comment]
Since the change is included in #974, I will close this PR.

**Pull request closed without merging**
