### PR TITLE
STORM-3097: Remove storm-druid

### PR DESCRIPTION
**Pull request by revans2**
This is the follow on to  #2706 which deprecates storm-druid for 1.x releases.

### CODE REVIEW

**Comment by srdo** [comment]
Remember https://github.com/apache/storm/blob/master/docs/storm-druid.md and any links in the other docs referring to druid. +1 otherwise.

**Comment by revans2** [comment]
Thanks @srdo I removed storm-druid.md and removed the link form index.md (which was the only one I could find)

**Comment by srdo** [comment]
Thanks, +1 again

**Comment by HeartSaVioR** [comment]
My bad. I should have closed #2704 instead of this. Will merge this.

**Comment by HeartSaVioR** [comment]
Closed in 0eb6b5116f251e17b6f14a61cebfadfc286faa59

**Pull request closed without merging**
