### PR TITLE
STORM-2411 Setting topology.eventlogger.executors=0 in defaults.yaml

### PR DESCRIPTION
**Pull request by roshannaik**

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1 This makes consistent with 1.x branch.

**Comment by Ethanlm** [comment]
Just realized that https://github.com/apache/storm/blob/master/storm-client/src/jvm/org/apache/storm/Config.java#L398 should be updated because of this patch

**Comment by roshannaik** [comment]
Good point. Will provide a fix.

**Comment by Ethanlm** [comment]
I think I can include it in my PR for https://issues.apache.org/jira/browse/STORM-3021

**Comment by roshannaik** [comment]
thanks.

**Pull request merged**
