### PR TITLE
[STORM-1377] Adds lock when launching a test cluster

### PR DESCRIPTION
**Pull request by d2r**
There seems to be a race that results in certain tests accessing the wrong test nimbus server, and that is causing failures.  This gates attempts of any of the tests to talk to a nimbus cluster.

### CODE REVIEW

**Comment by d2r** [comment]
storm-core jdk8 had 1 failure each on netty-unit-test and nimbus-test
!storm-core jdk7 had an apparent crash while testing storm-sql-core

Will close and re-open to kick another build.

**Comment by revans2** [comment]
+1

**Comment by knusbaum** [comment]
+1

**Comment by d2r** [comment]
I am not sure this will solve the problem—the jdk8 build failed even on this branch. I have reproduced this on a local, single-core cluster.  Closing until I can find a more reliable work-around.

I am suspecting an unexpected exception is being thrown here, and it is not actually a locking issue.

Closing until I can figure this out.

**Pull request closed without merging**
