### PR TITLE
[STORM-831] Adding jira and central logging links to UI

### PR DESCRIPTION
**Pull request by kishorvpatil**
To main UI page
 - Add link to create JIRA page
 - Optional link to central logging
screen shot 2015-05-20 at 2 01 37 pm

Both links can be configured to custom service desk link.

### CODE REVIEW

**Comment by knusbaum** [comment]
+1

**Comment by ptgoetz** [comment]
@kishorvpatil Are you sure the two binary images are in the public domain and that we would be allowed to include them in an Apache release? Is there an associated license somewhere?

Also, I'd rather have the references to JIRA be more generic, for example "UI_PROJECT_BUGTRACKER_URL" instead of "UI_PROJECT_JIRA_URL". 

It would also help to add some documentation on how to set the links up. It's obvious to me, but it may not be to a new Storm user.

**Comment by kishorvpatil** [comment]
@ptgoetz Thank you for the feedback. I will rename the config o `UI_PROJECT_BUGTRACKER_URL`. Find licensed images and add documentation to the this PR.

**Comment by revans2** [comment]
@kishorvpatil could you rebase?  I really would like to get this into 0.11.0.

**Comment by kishorvpatil** [comment]
bugtracker-screen

**Comment by kishorvpatil** [comment]
@revans2 @ptgoetz Sorry for the delay in fixing this. 
- I updated config name to `UI_PROJECT_BUGTRACKER_URL`.  
- The new images are from public domain.
- rebased the branch.
- New screenshot image.

**Comment by revans2** [comment]
I am +1

@ptgoetz do you have any concerns still?

**Comment by ptgoetz** [comment]
The bug icon is licensed free for commercial use, so that should be fine.

The statistics icon is MIT licensed by Github, Inc., so we should have an entry in LICENSE for it.

Once that's done I'm +1. I'm also fine if the LICENSE entry is added at merge time. As long as it gets done.

Also note that we have two LICENSE files, one for source releases, and one for binary releases. Both should be updated.

**Comment by kishorvpatil** [comment]
@ptgoetz and @revans2 
Added MIT license to both LICENSE files. Thanks again for reviewing this.

**Comment by ptgoetz** [comment]
+1

I think the copyright line should read:

```
Copyright (c) 2015 Github, Inc.
```

But that can be done at merge time.

**Pull request merged**
