### PR TITLE
STORM-3488 Scheduling can cause RAS_Node resources to become negative

### PR DESCRIPTION
**Pull request by dandsager1**
Pull STORM-3488 into 2.1.x

### CODE REVIEW

**Comment by srdo** [comment]
@Ethanlm I can't remember if this is described anywhere, so just in case no one told you: Generally when cherry picking back changes, unless there are conflicts with the base branch I think you can do the cherry pick without a PR/review and without waiting for the 24 hour waiting period. I think we have been considering the original branch review sufficient when there aren't conflicts. Just in case you don't want to go through the delay :)

**Comment by Ethanlm** [comment]
@srdo  Thanks for the information. I tried to cherry-pick this commit but there were conflicts. So I asked @dandsager1 to file a separate PR so we can review.

**Comment by srdo** [comment]
Ok, I just wanted to be sure you knew.

**Comment by Ethanlm** [comment]
@srdo  Thank you very much. I really appreciated it

**Pull request merged**
