### PR TITLE
Storm 1649 Optimize Kryo instaces creation in trident windowing for 1.x

### PR DESCRIPTION
**Pull request by satishd**
@ptgoetz @harshach https://github.com/apache/storm/pull/1295 was raised on master. There were conflicts with 1.x-branch because of different HBase version issues in 1.x-branch and master, which are resolved.

### CODE REVIEW

**Comment by satishd** [comment]
@ptgoetz @harshach This PR is upmerged and resolved conflicts. Good to have it in 1.0.x though it is missed in 1.0

**Comment by harshach** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1 Confirmed local build passed.

**Comment by HeartSaVioR** [comment]
@satishd 
I'd like to see the commits having meaningful messages. Could you reword the commit messages?

**Comment by HeartSaVioR** [comment]
At least commit message should be "STORM-1649 kryo serialization in windowing" to match to PR against master. I guess squashing commits would be good since this is not huge patch.

**Comment by satishd** [comment]
@HeartSaVioR done with the suggested changes.

**Comment by HeartSaVioR** [comment]
@satishd 
+1 Retested with local build.
Thanks for the quick fix!

**Pull request merged**
