### PR TITLE
STORM-2639: [1.x-branch] Kafka Spout incorrectly computes numCommittedOffsets due to voids in the topic (topic compaction)

### PR DESCRIPTION
**Pull request by askprasanna**

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by srdo** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1

**Comment by srdo** [comment]
@askprasanna Could I get you to update the commit message to reflect the current JIRA number? I checked if this would go on 1.0.x unmodified as well, but 1.0.x was before we added the OffsetManager class. Would you like to see if it can be ported to 1.0.x, or does it work for you if this only makes it into 1.2.0?

**Comment by HeartSaVioR** [comment]
Let's just reword the commit title while merging.

**Comment by HeartSaVioR** [comment]
Merged via 6cfcbeef4cd2da9f601687966aa08f6b75e41597 
@askprasanna 
I can't use Github automatic close because this PR is not against master branch. 
Could you close this PR? Thanks in advance!

**Comment by askprasanna** [comment]
Closing the PR.

**Pull request closed without merging**
