### PR TITLE
STORM-2320: DRPC client printer class reusable for local and remote DRPC

### PR DESCRIPTION
**Pull request by hmcl**

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1

**Comment by ptgoetz** [comment]
JIRA? Rationale?

**Comment by hmcl** [comment]
@ptgoetz I have filed a [JIRA](https://issues.apache.org/jira/browse/STORM-2320) which describes the motivation and necessity for this patch. Let's let me know if you need further clarification.

**Comment by ptgoetz** [comment]
+1 thanks for the update @hmcl

**Comment by harshach** [comment]
@hmcl can you open a PR against 1.x-branch as well.

**Pull request merged**
