### PR TITLE
Python 3 print statement error

### PR DESCRIPTION
**Pull request by Darkless012**

### CODE REVIEW

**Comment by macheins** [comment]
Maybe should add a `from __future__ import print_function` to ensure backward compatibility.

**Comment by HeartSaVioR** [comment]
In fact, no need to add __future__ `for now`, but it's more safer to add this.
+1

**Comment by amitripshtos** [comment]
+1

**Comment by HeartSaVioR** [comment]
Thanks @Darkless012, I merged into master, 1.x, 1.0.x branch so it'll be reflected to upcoming 1.0.2.

**Pull request closed without merging**
