### PR TITLE
STORM-2104 1.x

### PR DESCRIPTION
**Pull request by srdo**
1.x version of https://github.com/apache/storm/pull/1696

### CODE REVIEW

**Comment by revans2** [comment]
+1 pending travis (and the waiting period)

**Comment by hmcl** [comment]
+1

**Comment by ptgoetz** [comment]
+1

**Comment by HeartSaVioR** [comment]
@srdo
Could you rebase? I can merge this based on multiple binding +1 after rebasing.

**Comment by srdo** [comment]
@HeartSaVioR Thanks, rebased

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
