### PR TITLE
STORM-1161: Add License headers and add rat checks to builds

### PR DESCRIPTION
**Pull request by dossett**
This moves Apache Rat out of the release profile and into the standard build process.  It will add a slight amount of time to builds for the benefit of more frequent and thorough license audits.

I also updated 16 files with the appropriate license header.

### CODE REVIEW

**Comment by revans2** [comment]
+1

**Comment by redsanket** [comment]
+1 NB

**Comment by ptgoetz** [comment]
+1

**Comment by dossett** [comment]
Travis says that storm-hive failed the rat check.  Can someone show me the contents of "/home/travis/build/apache/storm/external/storm-hive/target/rat.txt" ?

**Comment by revans2** [comment]
@dossett none of us have permission for those files, in fact they are probably gone by now.  Travis only saves what was output to the log.  You could put in something in the ./dev-tools/travis that will spit out the contents of rat.txt files if the build fails because of rat.

**Comment by dossett** [comment]
Thanks @revans2, I'm learning a lot today.

**Comment by dossett** [comment]
I found the storm-hive issue.  The remaining java7 failure appears unrelated to these changes and java8 build was successful.

**Comment by dossett** [comment]
@revans2 @ptgoetz @redsanket Are you still +1 on this change?  I added the small travis step of printing file names with failed licenses since your vote.

**Comment by revans2** [comment]
Yes I am +1.  It looks great.

**Comment by ptgoetz** [comment]
@dossett Yes. +1

**Comment by revans2** [comment]
I just tried to build with this and we need to upmerge because filght.bash has been added in recently.

**Comment by dossett** [comment]
Upmerged and squashed to a single commit @revans2

**Comment by revans2** [comment]
Still +1

**Pull request merged**
