### PR TITLE
STORM-1429: LocalizerTest fix

### PR DESCRIPTION
**Pull request by revans2**

### CODE REVIEW

**Comment by revans2** [comment]
The Travis failure in this case is unrelated and is from storm-kafka

**Comment by HeartSaVioR** [comment]
+1

Btw, would 100ms be enough to work with Travis CI?

**Comment by revans2** [comment]
@HeartSaVioR I tested this on my own under-powered linux VM where I was seeing the issue, so I think it is.  The delete has already happened on the same thread, in a method call just above it.  I am not sure why Java and/or the OS is reporting that the file is still there, but it did occasionally.

**Comment by knusbaum** [comment]
+1

**Pull request merged**
