### PR TITLE
STORM-3647: Adds OFF HEAP to worker child opts

### PR DESCRIPTION
**Pull request by govind-menon**

### CODE REVIEW

**Comment by Ethanlm** [comment]
please update commit message to also include the jira id

**Comment by govind-menon** [comment]
@Ethanlm Done.

**Comment by Ethanlm** [comment]
How can a topology use off heap memory? Setting %OFF-HEAP-MEM% doesn't seem enough?

**Comment by govind-menon** [comment]
The off heap memory requested for the executor is what is put in the flag

**Comment by Ethanlm** [comment]
Yes but if worker.childopts doesn't have `%OFF-HEAP-MEM%`, this setting is not really enforced, right?

**Comment by govind-menon** [comment]
Yes that is correct

**Pull request merged**
