### PR TITLE
upgrade kafka version 0.8.2.1 --> 0.8.2.2

### PR DESCRIPTION
**Pull request by darionyaphet**
upgrade kafka version 0.8.2.1 --> 0.8.2.2

### CODE REVIEW

**Comment by knusbaum** [comment]
Two questions: 
 - Is there a Jira for this?
 - What is the purpose for upgrading? (It's a minor version so I'm not too concerned)

**Comment by revans2** [comment]
@darionyaphet this seems like a good change.  I am +1 for it, but I would like to see @knusbaum's questions answered.

**Comment by darionyaphet** [comment]
Hi @knusbaum @revans2 I read `Kafka Release Notes Version 0.8.2.2`  and found a bug fixed ([KAFKA-2308](https://issues.apache.org/jira/browse/KAFKA-2308)) about New producer and Snappy un-compression errors when Kafka Broker restart . So I think this is maybe useful .

**Comment by darionyaphet** [comment]
@revans2 @knusbaum I push some kafka spout modify to trunk but I don't know why auto append into this PR . I closed this PR and will reopen it if needed . thanks a lot :)

**Pull request closed without merging**
