### PR TITLE
STORM-1989: X-Frame-Options support for Storm UI

### PR DESCRIPTION
**Pull request by tibkiss**

### CODE REVIEW

**Comment by ptgoetz** [comment]
+1

**Comment by tibkiss** [comment]
Thanks @ptgoetz for the review!

The Travis test failure seems unrelated to me: 
The base version of the patch also fails with test errors.

**Comment by ptgoetz** [comment]
@tibkiss Yes. I tested locally and the build succeeded.

**Comment by harshach** [comment]
@tibkiss can you post a patch against 1.x-branch as well. Also how does this works with CORS enabled.

**Comment by tibkiss** [comment]
@harshach : The patch is not interfering with CORS filter. It is an additional filter addressing the ClickJacking vulnerability. 

@ptgoetz : Super thanks for merging the PR to both branches. Next time I'll address the delivery to additional branches quicker.

**Pull request merged**
