### PR TITLE
[STORM-1481] avoid Math.abs(Integer) get a negative value

### PR DESCRIPTION
**Pull request by vesense**
https://issues.apache.org/jira/browse/STORM-1481

### CODE REVIEW

**Comment by zhuoliu** [comment]
+1.
The fix is necessary due to follows, which can cause problem during grouping.
Integer.MAX_VALUE % 1 = 0
Integer.MAX_VALUE % 2 = 0
Integer.MAX_VALUE % 3 = -2
Integer.MAX_VALUE % 4 = 0
Integer.MAX_VALUE % 5 = -3
Integer.MAX_VALUE % 6 = -2
Integer.MAX_VALUE % 7 = -2
Integer.MAX_VALUE % 8 = 0

**Comment by arunmahadevan** [comment]
why not `Math.abs(val.hashCode() % numPartitions)` ?

**Comment by revans2** [comment]
OK so Math.abs(Integer.MIN_VALUE) actually returns Integer.MIN_VALUE because of an integer overflow error.  That is a good corner case to remember in the future.

@arunmahadevan `Math.abs(val.hasCode() % numPartitions)` would work too.  The only reason to do one over the other would be performance vs readability.  In my very unscientific test
```
public class Test {
    public static int toPositive(int number) {
        return number & Integer.MAX_VALUE;
    }

    public static void main(String [] args) {
        int count = Integer.valueOf(args[0]);
        long start = System.nanoTime();
        for (int i = 0; i < count; i++) {
            int ret = Math.abs(i);
            //int ret = toPositive(i);
        }
        long end = System.nanoTime();
        System.out.println(end+" - "+ start+" = "+(end-start)+" rate: "+(((double)count)/(end-start)));
    }
}
```
I get about 291 ops per nanosecond for toPositive

`1453216134803090000 - 1453216134799657000 = 3433000 rate: 291.29041654529567`

and 289 ops per nanosecond for Math.abs
`1453216159561620000 - 1453216159558157000 = 3463000 rate: 288.7669650591972`

To me it is such a small difference About 1% over a part of the code where computing the hash code dominates that it should come down to readability.  Both look equally as readable to me (because of the comments on toPositive).

I am +1 for this change.

**Comment by revans2** [comment]
@vesense I don't see any indication in the JIRA which branches you want this fix merged into.  master and 1.x seem simple enough, but it appears to be a bug in 10.x and 9.x releases too.  I'm not sure it is critical enough to go back to either of them, but I wanted to check with you before merging this in.

**Comment by ptgoetz** [comment]
+1

I wouldn't mind seeing this go back to 1.x and 0.10.x (0.10.x has a few other minor fixes). But I don't think we need to support 0.9.x too much longer.

**Comment by revans2** [comment]
Because the files have change locations porting to 0.10.x is going to need a separate pull request (git is not happy)

I will merge this in for master and 1.x-branch

**Comment by ptgoetz** [comment]
@revans2 I'll take care of the merge to 0.10.x as soon as this is in master.

**Comment by revans2** [comment]
@ptgoetz sounds good just running a sanity check with the tests before merging it in.

**Pull request merged**
