### PR TITLE
STORM-794 Modify Spout async loop to treat activate/deactivate ASAP

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Currently when overflow buffer is not empty or pending is equal or greater than max spout pending, Spout doesn't handle activate / deactivate.

I've met this scenario with Trident topology, max spout pending is 10, $batch's complete latency is about to 20 sec.
Please refer https://issues.apache.org/jira/browse/STORM-794 for more description.

After applying this patch to 0.9.3, issue is resolved, though it still handles already emitted batches. 

>> deactivate
```
2015-05-04 16:35:52.127 INFO  [Thread-12-spout0][RecollectSpout] batchId <46253> start
2015-05-04 16:35:53.538 INFO  [Thread-16-$mastercoord-bg0][executor] Deactivating spout $mastercoord-bg0:(1)
2015-05-04 16:35:54.130 INFO  [Thread-12-spout0][RecollectSpout] batchId <46244> end
2015-05-04 16:35:54.130 INFO  [Thread-12-spout0][RecollectSpout] batchId <46254> start
...
2015-05-04 16:36:10.153 INFO  [Thread-12-spout0][RecollectSpout] batchId <46262> start
...
2015-05-04 16:36:12.297 INFO  [Thread-12-spout0][RecollectSpout] batchId <46262> end
... no more batch emitted (46253 + 10 = 46263, no txid 46263 found)
```

>> activate
```
2015-05-04 16:42:23.715 INFO  [Thread-16-$mastercoord-bg0][executor] Activating spout $mastercoord-bg0:(1)
...
2015-05-04 16:42:23.721 INFO  [Thread-12-spout0][RecollectSpout] batchId <46263> start
2015-05-04 16:42:25.159 INFO  [Thread-12-spout0][RecollectSpout] batchId <46264> start
2015-05-04 16:42:27.162 INFO  [Thread-12-spout0][RecollectSpout] batchId <46265> start
```

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Kafka test failures again. Other things are OK.

**Comment by HeartSaVioR** [comment]
@ptgoetz @revans2 
I'd like you to take a look. Thanks!

**Comment by revans2** [comment]
@HeartSaVioR is this something you still want?  I like the idea of the change, and the code looks good, but we would need to upmerge.

**Comment by HeartSaVioR** [comment]
@revans2 
Yes, as I described to [JIRA issue](https://issues.apache.org/jira/browse/STORM-794?focusedCommentId=14526316&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14526316), MasterBatchCoordinator doesn't play well with async loop, since it  handles emitting batch independently. MasterBatchCoordinator could make pending tuple count always same to max spout pending in point of async loop's view, which makes async loop to never trigger deactivate.
I'll do upmerge and let you know. Thanks!

**Comment by HeartSaVioR** [comment]
@revans2 Upmerged.

**Comment by revans2** [comment]
The changes look good to me and all of the tests pass so I am +1 for this.

**Pull request merged**
