### PR TITLE
STORM-2638: Add in maximum object size for Pacemaker Thrift objects

### PR DESCRIPTION
**Pull request by knusbaum**

### CODE REVIEW

**Comment by vesense** [comment]
Looks good to me. It would be better if we can apply new code style to the changes.

**Comment by knusbaum** [comment]
@vesense Agreed. How do I run the linter?

**Comment by knusbaum** [comment]
@vesense Done. I think I've cleared the checkstyle warnings on all the lines I changed. Let me know if I've missed something.

**Comment by vesense** [comment]
Sorry for the delay. +1

**Pull request merged**
