### PR TITLE
STORM-3184: Mask the plaintext passwords from the logs

### PR DESCRIPTION
**Pull request by arunmahadevan**
Introduce a `Password` config annotation and use it to mark configs that are
sensitive and mask the values while logging.

### CODE REVIEW

**Comment by arunmahadevan** [comment]
ping @HeartSaVioR

**Comment by HeartSaVioR** [comment]
ping @arunmahadevan

**Comment by arunmahadevan** [comment]
@HeartSaVioR , i had a quick look and its not straightforward to port this patch to master. The Configs are now split into Config and DaemonConfig and quite a lot of refactoring has happened. I need to figure out the right place to put this so that the code can be shared across the storm-client and storm-server modules.

**Comment by arunmahadevan** [comment]
@HeartSaVioR  heres the master port - https://github.com/apache/storm/pull/2801

I guess sooner we release 2.0 and stick to master branch for even minor feature development the better.

**Comment by HeartSaVioR** [comment]
@arunmahadevan Totally agreed. We should move onto Storm 2.0.0, and actually most of recent pull requests have been only applied to master branch.

**Pull request merged**
