### PR TITLE
修改jdbcClient

### PR DESCRIPTION
**Pull request by conkeyn**

### CODE REVIEW

**Comment by Renkai** [comment]
You'd better use English and contribute by this guide
http://storm.apache.org/documentation/Contributing-to-Storm.html

**Comment by d2r** [comment]
@conkeyn,

Could you change commit messages to English, create a Jira issue for this pull request, and fix the conflicts with the master branch?

**Comment by Parth-Brahmbhatt** [comment]
What jira is this associated with? I see some ip addresses in pom and even looking at the change I cant understand what is this intending to do.

**Comment by vesense** [comment]
@d2r @Parth-Brahmbhatt  Since the PR is no longer updated, I think we can close it now. @conkeyn can create a new PR if necessary.

**Pull request closed without merging**
