### PR TITLE
STORM-2256: storm-pmml breaks on java 1.7

### PR DESCRIPTION
**Pull request by harshach**

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1 Nice finding.

**Comment by vesense** [comment]
+1

**Comment by hmcl** [comment]
+1. Thanks for the fix.

I compiled this locally, a few times... wonder how this wasn't detected :(

**Comment by HeartSaVioR** [comment]
Integration test fails consistently so we eventually don't see build result. We should drop integration test for now and refer Travis CI result.

**Pull request merged**
