### PR TITLE
[STORM-1411] some fixes for storm-windowing

### PR DESCRIPTION
**Pull request by vesense**
https://issues.apache.org/jira/browse/STORM-1411

### CODE REVIEW

**Comment by vesense** [comment]
The Travis CI failed build seems unrelated.

**Comment by arunmahadevan** [comment]
@vesense can you submit it in a single commit?

**Comment by vesense** [comment]
@arunmahadevan Thanks. I have rebased the PR.

**Comment by arunmahadevan** [comment]
I see two PRs with same title. Can you include the changes in https://github.com/apache/storm/pull/968 in this PR in the same commit ?

**Comment by vesense** [comment]
@arunmahadevan OK. Done.

**Comment by arunmahadevan** [comment]
+1

**Comment by arunmahadevan** [comment]
Thanks @vesense merged to master

**Pull request merged**
