### PR TITLE
STORM-1189: Maintain wire compatability with 0.10.x versions of storm.

### PR DESCRIPTION
**Pull request by revans2**

### CODE REVIEW

**Comment by revans2** [comment]
I have not tested this manually between a 0.10.x client and a 0.11.x server, but I do plan to.

Note that this only maintains wire compatibility, not API compatibility.  The constructor for ClusterSummary is not the same, as required parameters have been removed.  I don't see this as critical because only internal storm code should ever be creating instances of this class, but it is an incompatibility with 0.10.x.

**Comment by kishorvpatil** [comment]
LGTM. +1

**Comment by zhuoliu** [comment]
+1

**Comment by revans2** [comment]
I just ran the test and I was able to use a 0.10.1 UI against a nimbus instance running using this patch.

I did find that ShellBolt is not backwards compatible.  I will file a JIRA around that.

**Comment by HeartSaVioR** [comment]
+1

**Comment by spicoflorin** [comment]
Hello!
 I have downloaded the version 0.10.0 and applied the patch from  https://patch-diff.githubusercontent.com/raw/apache/storm/pull/868.patch, but I got compilation errors. I would like to use the 0.10.0 storm version. Can you please test again? Or what code version should I use : the one from tags (0.10.0) or the one from the branch 0.10.x master?
 ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project storm-core: Compilation failure: Compilation failure:
ERROR] /d:/Temp/stom-10/storm-0.10.0/storm-core/src/jvm/backtype/storm/generated/ClusterSummary.java:[321,5] duplicate case label
ERROR] /d:/Temp/stom-10/storm-0.10.0/storm-core/src/jvm/backtype/storm/generated/ClusterSummary.java:[403,13] variable this_present_nimbus_uptime_secs is already defined in method equals(backtype.storm.generated.ClusterSummary)
ERROR] /d:/Temp/stom-10/storm-0.10.0/storm-core/src/jvm/backtype/storm/generated/ClusterSummary.java:[404,13] variable that_present_nimbus_uptime_secs is already defined in method equals(backtype.storm.generated.ClusterSummary)
ERROR] /d:/Temp/stom-10/storm-0.10.0/storm-core/src/jvm/backtype/storm/generated/ClusterSummary.java:[617,11] duplicate case label
ERROR] -> [Help 1]

**Comment by YuChem** [comment]
@spicoflorin: I have encountered the same issue. Did you get it resolved? Would you mind get some tips on how to workaround?

**Comment by spicoflorin** [comment]
Hi!
  I didn't solve it.

**Pull request merged**
