### PR TITLE
STORM-1153 Use static final instead of just static for class members

### PR DESCRIPTION
**Pull request by sureshms**
Along with making static variables, I have also cleaned up the code in those files. Especially around reducing code verbosity by using Generic Type Inference.

### CODE REVIEW

**Comment by revans2** [comment]
+1 the changes look good.

**Comment by revans2** [comment]
@harshach I just noticed that this has already been merged in, but the JIRA was not closed and this pull request was also not closed, there also was no vote on it.  Could you resolve the JIRA and see if you can find a way to close this pull request?

**Comment by harshach** [comment]
@revans2 Sorry. I thought I already gave my +1 on this. Not sure why the PR isn't closed. retroactive +1 on this.

**Comment by harshach** [comment]
@sureshms can you please close the PR.

**Comment by revans2** [comment]
@harshach I am not concerned about it.  The change is good and I assumed you had giving it a +1 just simply by checking it in.  I just wanted to be sure things got cleaned up and @sureshms got credit for his work.

**Pull request closed without merging**
