### PR TITLE
[STORM-3491] BoltReaderRunnable shouldn't throw IllegalArgumentException for sync command

### PR DESCRIPTION
**Pull request by Ethanlm**
Refer to https://issues.apache.org/jira/browse/STORM-3491

### CODE REVIEW

**Comment by srdo** [comment]
I'm wondering if we should revert back to the old behavior of accepting any string? Someone else may be depending on that behavior.

**Comment by Ethanlm** [comment]
Makes sense. Fixing it

**Comment by srdo** [comment]
+1, thanks

**Comment by Ethanlm** [comment]
Thanks for the review

**Pull request merged**
