### PR TITLE
[STORM-752] [storm-redis] Clarify Redis*StateUpdater's expire is optional

### PR DESCRIPTION
**Pull request by HeartSaVioR**
It's not released to official, and I've just changed constructor signature so I'm not sure it can be treated to small patch.

If you feel that it requires JIRA issue, please let me know to file it. Thanks!

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@dashengju @revans2 Please take a look.

**Comment by dashengju** [comment]
nice, +1

**Comment by HeartSaVioR** [comment]
Filed a issue to JIRA.

**Comment by ptgoetz** [comment]
+1

**Comment by revans2** [comment]
+1

**Pull request merged**
