### PR TITLE
[STORM-1544] Document Debug/Sampling of Topologies

### PR DESCRIPTION
**Pull request by arunmahadevan**
Added documentation for logging/sampling events in a topology.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1
I think we can add a note about performance issue regarding #1217 when we're sure it does have performance hit.

**Comment by revans2** [comment]
It looks good can we add a link to this in docs/index.md as well?  Otherwise it will not be easy to find in the UI.

**Comment by ptgoetz** [comment]
@revans2 The yaml front matter `documentation: true` should take care of that.

+1

**Comment by revans2** [comment]
@ptgoetz Not for the release specific docs.  At least I didn't end up setting it up that way, and so if I missed something, then I am happy to go back and try and fix it.

**Comment by ptgoetz** [comment]
@revans2 Okay. I didn't realize that had changed, I'm okay with either approach.

One thing I did notice is that the documentation dropdown is missing from the home page, and the downloads page is now a 404.

(sorry for hijacking this pull request)

**Comment by revans2** [comment]
@ptgoetz I didn't realize that we were generating an index using the docs tag.  I am happy to go back and add something in again for it.

Also everything is working fine for me.  what browser are you using?  is there something in your cache that is messed up? Just FYI I renamed the download.html to releases.html, because it includes more then just download links, but the download button points to the proper place.  I am happy to revert that change too if you had other stuff pointing to it.

**Comment by harshach** [comment]
@revans2 we should add redirection from downloads.html to release.html.

**Comment by ptgoetz** [comment]
@revans2 It was a caching issue. Sorry for the noise.

I agree with @harshach, we may want to consider a redirect from downloads.html to release.html to keep from breaking external links and bookmarks.

I think we need to add a link to the KEYS file for releases, and it might help to add maven information like we did in the old downloads page.

**Comment by arunmahadevan** [comment]
@revans2 @ptgoetz added a link in docs/index.md

**Comment by HeartSaVioR** [comment]
+1 again.
I think we can grep issues on website and raise an issue to follow up.

**Comment by arunmahadevan** [comment]
Appears that some html pages are broken. E.g. http://storm.apache.org/releases/1.0.0-SNAPSHOT/State-checkpointing.html beyond the section "IStateful bolt hooks", the formatting and sections headings are lost. Do we need to fix something in the scripts that generate the html files ?

**Comment by ptgoetz** [comment]
@arunmahadevan That's likely a typo or formatting error in the markdown file.

**Comment by arunmahadevan** [comment]
@ptgoetz updated the doc to reflect the new (disabled by default) behavior. Please review.

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
