### PR TITLE
STORM-1629 (For 1.x) Files/move doesn't work properly with non-empty directory in Windows

### PR DESCRIPTION
**Pull request by HeartSaVioR**
PR based on master is here: https://github.com/apache/storm/pull/1214

* Use FileUtils/moveDirectory on Windows
  * It copies whole contents inside directory, and delete directory
* Keep using Files/move on non-Windows
  * it's still better option since doesn't require copying contents inside directory

### CODE REVIEW

**Comment by hustfxj** [comment]
+1

**Comment by harshach** [comment]
+1

**Comment by vesense** [comment]
LGTM

**Comment by HeartSaVioR** [comment]
Please review #1214 as well. Thanks!

**Comment by ptgoetz** [comment]
+1

**Pull request merged**
