### PR TITLE
hotfix: parent version for pom.xml in storm-mongo is not properly set

### PR DESCRIPTION
**Pull request by HeartSaVioR**

### CODE REVIEW

**Comment by dossett** [comment]
+1

**Comment by vesense** [comment]
+1 Good catch!

**Comment by ptgoetz** [comment]
+1

**Comment by hustfxj** [comment]
+1 good

**Comment by vesense** [comment]
The bug has been fixed by https://github.com/apache/storm/pull/1231
@HeartSaVioR Could you close this PR?

**Comment by HeartSaVioR** [comment]
@vesense Thanks for noticing. Closing.

**Pull request closed without merging**
