### PR TITLE
STORM-971: Metric for messages lost due to kafka retention

### PR DESCRIPTION
**Pull request by abhishekagarwal87**

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by vesense** [comment]
LGTM

**Comment by abhishekagarwal87** [comment]
@harshach - can you merge this? We need this in 1.x branch as well.

**Comment by ptgoetz** [comment]
+1

**Comment by ptgoetz** [comment]
Merged to master and 1.x-branch.

**Pull request merged**
