### PR TITLE
[STORM-1344]  Remove sql command from storm-jdbc build.

### PR DESCRIPTION
**Pull request by ppoulosk**
Works around STORM-1344 by ensuring table is not double-created.

### CODE REVIEW

**Comment by abellina** [comment]
could we remove the file all together? Seems like unit tests are also creating that table...

**Comment by HeartSaVioR** [comment]
We need to ensure that created table from unit tests will be dropped when cleaning up tests. Removing data directory would be also OK.

**Comment by HeartSaVioR** [comment]
@abellina I got what you are saying.
@ppoulosk Let's remove test.sql and relevant setting from pom.xml since JdbcClientTest is already in charge to create table.

**Comment by ppoulosk** [comment]
@HeartSaVioR, @abellina, will fix as you suggest.

**Comment by ppoulosk** [comment]
Fixed.  Re-ran tests.  Thanks.

**Comment by HeartSaVioR** [comment]
OK. Checked changeset doesn't affect the build result. Nice work. +1

**Comment by HeartSaVioR** [comment]
@ppoulosk 
Could you rebase this into master and squash commits into one? I guess discarding first commit would be good. 
Also please add STORM-1344 as prefix to commit message since we don't get any information from the commit message.

**Comment by ppoulosk** [comment]
@HeartSaVioR Thanks for the review!!  I've squashed commits and added JIRA to commit comment.

**Comment by abellina** [comment]
@ppoulosk were you able to test without the plugin all together?

**Comment by ppoulosk** [comment]
@abellina Yes.  I've now pushed the change without the plugin.

**Comment by abellina** [comment]
+1 Thanks

**Comment by HeartSaVioR** [comment]
still +1

**Pull request merged**
