### PR TITLE
[STORM-990] Refactored TimeCacheMap to extend RotatingMap.

### PR DESCRIPTION
**Pull request by ddebree**
This should allow current users of the TimeCacheMap to progressively migrate off the deprecated TimeCacheMap to the simpler RotatingMap.
 This also improves code reuse since many of the methods were shared.

### CODE REVIEW

**Comment by knusbaum** [comment]
For large changes like this and #683, Please file a jira at https://issues.apache.org/jira/browse/STORM/

**Comment by ddebree** [comment]
Issue raised: https://issues.apache.org/jira/browse/STORM-990

**Comment by knusbaum** [comment]
@ddebree Thanks. I should have mentioned it, but we also include the issue name in the title of our pull requests by convention.
```
[STORM-990] Refactored TimeCacheMap to extend RotatingMap.
```

**Comment by knusbaum** [comment]
I'm in favor of using RotatingMap to implement TimeCacheMap, but I'd rather have a RotatingMap as a member of TimeCacheMap than as a superclass.

**Comment by ddebree** [comment]
I have updated the class to rather use the RotatingMap as a member variable. It comes out a lot more similar to the original.

**Comment by knusbaum** [comment]
+1 Looks good to me.

**Pull request merged**
