### PR TITLE
[STORM-2283] Fix multi threading issues in DefaultStateSerializer

### PR DESCRIPTION
**Pull request by arunmahadevan**
Raising a separate patch for the state issue fixed in https://github.com/apache/storm/pull/1693

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1 Confirmed this works well from #1693.

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
Just realized you're using Optional from JDK 8. 
Given that it's a bug across 1.x version lines, could you craft a patch for 1.x? Thanks in advance.

**Comment by arunmahadevan** [comment]
@HeartSaVioR guava's Optional did not have a public default ctor and Kryo was throwing errors during deserialization. I will try to address it and raise a different patch for 1.x branch.

**Comment by arunmahadevan** [comment]
@HeartSaVioR I made some change so that it works without any changes to RedisEncoder and compatible with 1.x-branch as well. Please take a look. I also applied the same changes to https://github.com/apache/storm/pull/1693

**Comment by HeartSaVioR** [comment]
+1 Thanks for the quick fix.

**Pull request merged**
