### PR TITLE
STORM-1848: Make KafkaMessageId and Partition serializable to support…

### PR DESCRIPTION
**Pull request by srdo**
… eventlogging

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1
Build failures are due to nexus issue.

**Comment by srdo** [comment]
Does it make sense to restrict the emit functions on SpoutOutputCollector to take only serializable messageIds?

**Comment by revans2** [comment]
@srdo that would not be a backwards compatible change for something that never had to have this before.  And we don't require it to be serializable, if you have it properly registered with kryo then it will handle it instead.

**Comment by srdo** [comment]
You're right, I forgot about backwards compatibility, I mainly wanted to ensure this doesn't pop up in other spouts :) Is there any way for the Kafka spout to register with Kryo instead?

How about a comment on the SpoutOutputCollector interface about this?

**Comment by hmcl** [comment]
+1

**Comment by revans2** [comment]
+1 for the comment. I think that would be great, and having the KafkaSpout register things with kryo would be good, but I don't know if the API is setup to support that, as the KafkaSpout would need to have access to the topology config before submitting the topology.

**Comment by srdo** [comment]
I'll leave it at adding the comments then.

**Comment by ptgoetz** [comment]
+1

**Pull request merged**
