### PR TITLE
STORM-959:remove unnecessary dependency from storm-hive/pom.xml

### PR DESCRIPTION
**Pull request by caofangkun**
org.apache.calcite:calcite-core:0.9.2-incubating does not take affect at all.

### CODE REVIEW

**Comment by caofangkun** [comment]
@harshach 
Could you please have a look at this PR?

**Comment by caofangkun** [comment]
duplicates #609

**Comment by HeartSaVioR** [comment]
@caofangkun 
I can see "nexus.codehaus.org" is unreachable. I merged your PR to my forked repo and started Travis CI build.
https://travis-ci.org/HeartSaVioR/storm/builds/74997515
We can see if it helps.

**Comment by HeartSaVioR** [comment]
There're some issues regarding using SNAPSHOT version of dependencies.

- Tez: https://issues.apache.org/jira/browse/HIVE-8845
- Calcite: https://issues.apache.org/jira/browse/HIVE-8873

Since it is fixed at 1.0.0, we'd be better to upgrade Hive version, not excluding artifacts.
I didn't have time to use Hive, but normally 1.x.y feels more stable compared to 0.x.y. ;)

@harshach @ptgoetz @revans2 
Could you verify storm-hive can work with recent version of Apache Hive, 1.2.1? Thanks!

**Comment by HeartSaVioR** [comment]
I'm sorry, but it would be better to discuss it from #609 since this PR is duplicated and it contains same patch.

@caofangkun 
Could you close this PR and relevant issue as duplicated? Thanks!

**Pull request closed without merging**
