### PR TITLE
STORM-806: use storm.zookeeper.connection.timeout in storm-kafka ZkState when newCurator

### PR DESCRIPTION
**Pull request by tedxia**

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Build is failed from ZkCoordinatorTest.
You should also provide Config.STORM_ZOOKEEPER_CONNECTION_TIMEOUT from ZkCoordinatorTest to let build passed.

```
    private Map buildZookeeperConfig(TestingServer server) {
        Map conf = new HashMap();
        conf.put(Config.TRANSACTIONAL_ZOOKEEPER_PORT, server.getPort());
        conf.put(Config.TRANSACTIONAL_ZOOKEEPER_SERVERS, Arrays.asList("localhost"));
        conf.put(Config.STORM_ZOOKEEPER_SESSION_TIMEOUT, 20000);
        conf.put(Config.STORM_ZOOKEEPER_RETRY_TIMES, 3);
        conf.put(Config.STORM_ZOOKEEPER_RETRY_INTERVAL, 30);
        return conf;
    }
```

I recommend you to run tests from dev. machine at least once before posting PR.

**Comment by tedxia** [comment]
@HeartSaVioR sorry about the failure in test, I had added a new patch to fix this.

**Comment by tedxia** [comment]
```
48495 [Thread-229] ERROR backtype.storm.task.ShellBolt - Halting process: ShellBolt died. Command: [ruby, tester_bolt.rb], ProcessInfo pid:7283, name:2 exitCode:-1, errorString:(Unable to capture error stream) 
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170) ~[na:1.8.0_31]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:283) ~[na:1.8.0_31]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_31]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_31]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_31]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_31]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_31]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[na:1.8.0_31]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[na:1.8.0_31]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[na:1.8.0_31]
	at backtype.storm.multilang.JsonSerializer.readString(JsonSerializer.java:179) ~[classes/:na]
	at backtype.storm.multilang.JsonSerializer.readMessage(JsonSerializer.java:166) ~[classes/:na]
	at backtype.storm.multilang.JsonSerializer.readShellMsg(JsonSerializer.java:100) ~[classes/:na]
	at backtype.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:99) ~[classes/:na]
	at backtype.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:321) ~[classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
```

Test failed due to the error above, someone have idea about this.

**Comment by HeartSaVioR** [comment]
30.1 is random failure of Kafka tests in Travis CI, which seems to be occurred with slow machine.
https://issues.apache.org/jira/browse/STORM-798

I can't see reason of failure about 30.2, since it doesn't print out test-report properly.

**Comment by HeartSaVioR** [comment]
Btw, restricting log level to WARN level is only applied to storm-core now, since I didn't add logback-test.xml on any other modules. Other modules don't print out much so it can be fully printed without issues.

**Comment by tedxia** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Storm ............................................. SUCCESS [0.550s]
[INFO] maven-shade-clojure-transformer ................... SUCCESS [0.840s]
[INFO] storm-maven-plugins ............................... SUCCESS [1.063s]
[INFO] multilang-javascript .............................. SUCCESS [0.105s]
[INFO] multilang-python .................................. SUCCESS [0.102s]
[INFO] multilang-ruby .................................... SUCCESS [0.096s]
[INFO] Storm Core ........................................ SUCCESS [3:48.903s]
[INFO] storm-starter ..................................... SUCCESS [2.032s]
[INFO] storm-kafka ....................................... SUCCESS [57.901s]
[INFO] storm-hdfs ........................................ SUCCESS [0.741s]
[INFO] storm-hbase ....................................... SUCCESS [0.944s]
[INFO] storm-hive ........................................ SUCCESS [50.312s]
[INFO] storm-jdbc ........................................ SUCCESS [1.186s]
[INFO] storm-redis ....................................... SUCCESS [0.209s]
[INFO] storm-eventhubs ................................... SUCCESS [2.440s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:48.069s
[INFO] Finished at: Mon May 04 11:53:15 CST 2015
[INFO] Final Memory: 53M/925M
```
Without run multilang_test.clj,  all tests pass on my machine. I don't think the change in stom-kafka will break multilang_test, will someone give some advice, thanks a lot.

**Comment by HeartSaVioR** [comment]
Yes, you don't need to fix current tests since it seems to be random tests failure on slow machine.

Btw, I'd like to fix kafka tests failure cause it has been occurred with very high probability.
But I don't know about Kafka so I wish someone helps me or I will learn Kafka someday and try to fix.

**Comment by tedxia** [comment]
I will try to fix STORM-798 , but how about this patch.

**Comment by HeartSaVioR** [comment]
LGTM.

**Comment by tedxia** [comment]
@ptgoetz Will you have a look at this, thank you.

**Comment by harshach** [comment]
+1

**Comment by harshach** [comment]
Thanks @tedxia merged into master.

**Pull request merged**
