### PR TITLE
Storm 1379 Removed Redundant Structure

### PR DESCRIPTION
**Pull request by darionyaphet**
Storm KafkaSpout have a static class `MessageAndRealOffset` which is same with Kafka API 's `kafka.message.MessageAndOffset` . 

So I hava remove MessageAndRealOffset and replace with MessageAndOffset  :)

### CODE REVIEW

**Comment by unsleepy22** [comment]
LGTM +1

**Comment by zhuoliu** [comment]
Looks good. +1

**Comment by ptgoetz** [comment]
+1

**Comment by wuchong** [comment]
+1
Could you rebase your commits into one? the last two commits change only one/two lines.

**Comment by d2r** [comment]
@wuchong Is it OK to merge it in even with the minor commits?

**Comment by wuchong** [comment]
The commits is  unimportant .  That's fine to  merge  It.

发自我的 iPhone

**Comment by kishorvpatil** [comment]
@darionyaphet Could you please take care of merge conflicts?

**Comment by darionyaphet** [comment]
hi @kishorvpatil I think I don't know how to resolve `merge conflicts`  and what should I do . 

Could you support some help? thanks

**Comment by darionyaphet** [comment]
This issue have merged [STORM-1379](https://issues.apache.org/jira/browse/STORM-1379)  and close this pull request :)

**Pull request closed without merging**
