### PR TITLE
[STORM-2238] Add Timestamp extractor for windowed bolt

### PR DESCRIPTION
**Pull request by arunmahadevan**
Added a timestamp extractor so that the tuple timestamp can be derived from the tuple than directly
mapping it to a field within the tuple.

https://github.com/apache/storm/pull/1819 applied to 1.x-branch

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by hmcl** [comment]
+1

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
Didn't we have document around setting up timestamp field? I think we should have it, or if we did, it should be updated.
Other than that it looks great overall.

**Comment by arunmahadevan** [comment]
@HeartSaVioR good point. Old api is retained, added additional doc for new api in docs/Windowing.md

**Comment by HeartSaVioR** [comment]
@arunmahadevan Thanks for the quick update. +1

**Pull request merged**
