### PR TITLE
STORM-1455: Do not reset the emittedOffset for offsetOutOfRangeExceptions

### PR DESCRIPTION
**Pull request by abhishekagarwal87**
There are two changes in this PR 

- If there is a TopicOffsetOutOfRangeException, it can be due to an old failed tuple. We should not reset the state back to the beginning. 
- Apart from the last completed offset, also emit the last emitted offset in the metric. latestEmittedOffset now points to the last emitted offset.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
@HeartSaVioR @revans2  can you review these changes?

**Comment by revans2** [comment]
First of all travis saw a compilation failure.
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/apache/storm/external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaSpout.java:[103,39] cannot find symbol
  symbol:   method setLatestEmittedOffset(org.apache.storm.kafka.Partition,long)
  location: variable _kafkaOffsetMetric of type org.apache.storm.kafka.KafkaUtils.KafkaOffsetMetric
[ERROR] /home/travis/build/apache/storm/external/storm-kafka/src/jvm/org/apache/storm/kafka/trident/TridentKafkaEmitter.java:[68,27] cannot find symbol
  symbol:   method setLatestEmittedOffset(org.apache.storm.kafka.Partition,java.lang.Long)
  location: variable _kafkaOffsetMetric of type org.apache.storm.kafka.KafkaUtils.KafkaOffsetMetric
```

**Comment by revans2** [comment]
Other then that it looks OK to me.

**Comment by abhishekagarwal87** [comment]
Thanks @revans2 . Fixed the compilation error. I had missed some changes. To put these changes in 1.0 release, do I need to open another pull request?

**Comment by revans2** [comment]
Typically you don't need a separate pull request.  Just ask for it and we will cherry-pick it.  If there are merge conflicts we may come back and ask for a separate pull request.

**Comment by abhishekagarwal87** [comment]
Thank you. can you merge this into master and also select these commits for backport onto 1.0 release?

**Comment by abhishekagarwal87** [comment]
can this be merged?

**Comment by HeartSaVioR** [comment]
@abhishekagarwal87 
Sorry to review in late. Looks good to me, +1.

**Comment by HeartSaVioR** [comment]
Merged to master, backporting to 1.x-branch...

**Comment by abhishekagarwal87** [comment]
Thanks @HeartSaVioR

**Comment by HeartSaVioR** [comment]
Forgot to leave comment, also backported to 1.x-branch.

**Pull request merged**
