### PR TITLE
STORM-590: added Kafka API based partition reader

### PR DESCRIPTION
**Pull request by wurstmeister**
Following the discussion in https://github.com/apache/storm/pull/387 I've prepared an alternative implementation that is backwards compatible 

- I’ve isolated the use of the ```BrokerHosts``` interface and marked its use as deprecated together with the zookeeper based code
- I’ve then added an implementation for API based partition information (based on the implementation https://github.com/apache/storm/pull/387)

### CODE REVIEW

**Comment by ogorun** [comment]
Hi @wurstmeister,

There is my pull request https://github.com/apache/storm/pull/406 and corresponding comments in pull request https://github.com/apache/storm/issues/387 . I'd be glad to see your feedback

**Comment by wurstmeister** [comment]
this is going to be discussed in STORM-650

**Comment by d2r** [comment]
@wurstmeister What is the status of this PR?  I see it needs an up-merge, but other than that, is there any other work that this needs before we review it?

**Comment by knusbaum** [comment]
Closing

**Pull request closed without merging**
