### PR TITLE
Backporting STORM-1027

### PR DESCRIPTION
**Pull request by abhishekagarwal87**

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
This PR is to backport STORM-1027 into 0.9.x branch. @HeartSaVioR can you merge this?

**Comment by HeartSaVioR** [comment]
@abhishekagarwal87 
Vote for releasing 0.9.6 and 0.10.0 is in progress.
I heard from @ptgoetz that Storm 0.9.x line will be faded out, so I'm expecting non-critical bugs cannot trigger new release of 0.9.x line.
So if you're affecting STORM-1027 and willing to resolve it ASAP using official release, using 0.10.0 will be fastest way to do it.
I can merge it to 0.9.x line, but I can't say when to release, so I'm curious that this should be backported.

**Comment by abhishekagarwal87** [comment]
can this not be released as part of 0.9.6? We see this deadlock regularly in our kafka spout based topologies.

**Comment by ptgoetz** [comment]
@abhishekagarwal87 @HeartSaVioR 

I'm okay with canceling the current 0.9.6 release vote and cutting a new release candidate if there is enough community support. I'll raise the question on the 0.9.6 release thread.

**Comment by HeartSaVioR** [comment]
@ptgoetz @abhishekagarwal87 
If we can cancel current release vote, and decide to cancel, I'll do backport this to 0.9.6. Decision should be made.

**Comment by abhishekagarwal87** [comment]
For long running topologies using kafka spout, we have always ran into this deadlock. It completely blocks the topology. Internally, we are already running the storm with this patch.

**Pull request merged**
