### PR TITLE
STORM-1849: HDFSFileTopology should use the third argument as topologyName.

### PR DESCRIPTION
**Pull request by csivaguru**
The change with the fix needs to be cherry picked into master.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by csivaguru** [comment]
Can this change be merged in?

**Comment by hmcl** [comment]
+1

**Comment by csivaguru** [comment]
Created a new PR against 1.x-branch, https://github.com/apache/storm/pull/1495

**Pull request closed without merging**
