### PR TITLE
STORM-1772 Adding Perf module with topologies for measuring performance

### PR DESCRIPTION
**Pull request by roshannaik**
Contributing some topologies for measuring Storm performance.
I have used these topos to identify and resolve perf issued with Storm in the past.  Also some of these have been used to publish these benchmarks : https://hortonworks.com/blog/microbenchmarking-storm-1-0-performance/ 

Some topos measure purely the internal functioning of Storm, while others measure I/O with external systems like Kafka and Hdfs. Topologies of the former type can be used for both:

 - Profiling speed within the IDE using profilers like JProfiler.
 - Benchmarking on a cluster

The topos which measure how fast you can do I/O with Kafka/Hdfs ... are intended for running on cluster and not designed for profiling within IDE.

### CODE REVIEW

**Comment by roshannaik** [comment]
Wanted to give credit the authors of Intel benchmark :
https://github.com/intel-hadoop/storm-benchmark  
from where I borrowed (with modification) the code to collect and compute metrics.

**Comment by harshach** [comment]
@roshannaik looks good to me. Can you add a doc on how to run these.

**Comment by roshannaik** [comment]
@harshach  I have added the doc.

**Comment by harshach** [comment]
+1

**Comment by roshannaik** [comment]
@harshach   FYI: I have squashed the commits. Also addressed rat issues.

**Comment by harshach** [comment]
Merged into master and 1.x-branch

**Pull request merged**
