### PR TITLE
STORM-1670 LocalState#get(String) can throw FileNotFoundException which may result supervisor.clj#sync-processes stop assigning new workers/assignments 

### PR DESCRIPTION
**Pull request by satishd**
LocalState#get(String) can throw FileNotFoundException which may result supervisor.clj#sync-processes stop assigning new workers/assignments etc and supervisor goes down later.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by ptgoetz** [comment]
+1

**Comment by hustfxj** [comment]
+1

**Comment by ptgoetz** [comment]
@satishd For some reason this is causing the storm-core clojure tests to fail consistently. Could you take a look?

**Comment by satishd** [comment]
@ptgoetz Tests in `org.apache.storm.versioned-store-test` does not really create a file with the created version but invoked `succeedVersion` which internally creates a `<version-path>.VERSION`. Those tests should have created a file with whatever data that wants to be saved.

**Comment by ptgoetz** [comment]
+1 (again). Confirmed this fixes the test failures on 1.x-branch.

**Pull request merged**
