### PR TITLE
added missing @Override annotations

### PR DESCRIPTION
**Pull request by krichter722**
help to detect inheritance issues when generics are used more intensively

### CODE REVIEW

**Comment by Parth-Brahmbhatt** [comment]
I don't think we should modify the thrift generated files, any way we could tell thrift to generate these annotation? If not, can we leave those files as is given they should never be modified manually anyways so @override will not provide any value in those cases.

**Comment by nathanmarz** [comment]
-1

Agree with Parth. Modifying the generated files is out of the question. The Thrift compiler should be patched to add those annotations if it doesn't have an option for that already.

**Comment by revans2** [comment]
@krichter722 thanks for the pull request, if you could remove the changes you made to the generated thrift code the rest seems fine.

**Comment by knusbaum** [comment]
@krichter722 Any news on this?

**Comment by d2r** [comment]
@krichter722 this pull request has been inactive for months, so I will be closing it soon.  Please reopen the pull request if you would like to address the comments.  If you do, please create a Jira for this work and resolve conflicts with the master branch.

**Comment by krichter722** [comment]
@d2r I rebased the branch, removed changes in classes generated by the Thrift compiler and included all subprojects. Since checkstyle is now in place I reviewed all `maxAllowedViolations` in POMs in order to avoid future missing `@Override`s.

I can reduce the `maxAllowedViolations` values is a separate PR, but I think it makes sense to include them here.

Please reopen this PR (I can't do it) can trigger Travis.

**Comment by srdo** [comment]
@krichter722 Sorry, I guess no one noticed your comment. Github won't let us reopen closed PRs if the base branch has been force pushed. If you still want these changes in, please open a new PR.

**Comment by d2r** [comment]
Apologies @krichter722, my GitHub notifications were getting black-holed while my employer changed its name. I had missed them for a while and evidently I did not see your comment. Yes I think we are not able to re-open this PR due to a GitHub limitation. This PR is superseded by #3020

**Comment by krichter722** [comment]
@d2r You can merge #3020 if you want :)

**Comment by d2r** [comment]
> @d2r You can merge #3020 if you want :)

OK I took a look at it, thanks for the reminder.

**Pull request closed without merging**
