### PR TITLE
STORM-2491: Adding extra Cassandra configuration parameters

### PR DESCRIPTION
**Pull request by tandrup**

### CODE REVIEW

**Comment by tandrup** [comment]
It fails on 
```
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project storm: Too many files with unapproved license: 3 See RAT report in: /home/travis/build/apache/storm/target/rat.txt -> [Help 1]
```
Do I need to do anything with licenses?

**Comment by harshach** [comment]
@tandrup can you please a file a JIRA https://issues.apache.org/jira/browse/ under STORM project. Also update the title of the JIRA and squash the commits in this PR. More details https://github.com/apache/storm/blob/master/DEVELOPER.md#contribute-code
https://github.com/apache/storm/blob/master/DEVELOPER.md#pull-requests

**Comment by tandrup** [comment]
@harshach OK. I was hoping my changes was small enough to fall into the _small patches_ category. I'll create a jira.

**Comment by harshach** [comment]
@tandrup for small docs changes etc. we don't file JIRAs but this one had quite few changes good to have that in JIRA and subsequently in CHANGELOG.

**Comment by harshach** [comment]
overall LGTM. +1 . 
@tandrup  would like to see these configs documented here https://github.com/apache/storm/blob/master/external/storm-cassandra/README.md

**Comment by tandrup** [comment]
@harshach I've added the new configs to the existing README list.

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
