### PR TITLE
[STORM-2464] update storm-mongodb.md

### PR DESCRIPTION
**Pull request by liu-zhaokun**
[https://issues.apache.org/jira/browse/STORM-2464](url)
storm-mongodb.md is out of date.For example,there is a new method in MongoMapper,but there isn't description in storm-mongodb.md. So ,storm-mongodb.md should be updated to be as same as storm-mongodb's README.md.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by vesense** [comment]
+1

**Comment by liu-zhaokun** [comment]
Hi, @vesense how are you?
I am sorry to bother you again.Would you help me to merge it?Thanks for your help these days.

**Comment by liu-zhaokun** [comment]
Hello,@vesense 
Could you help me to merge this PR?

**Pull request merged**
