### PR TITLE
[STORM-1359] change kryo links from google code to github

### PR DESCRIPTION
**Pull request by vesense**

### CODE REVIEW

**Comment by unsleepy22** [comment]
Hi vesense,
thanks for the PR, but it seems there're 3 files affected by this link:
Serialization.md
Structure-of-the-Codebase.md
backtype.storm.Config L1102.

currently only 1 file is changed. Could you change the other 2 files too?

**Comment by vesense** [comment]
@unsleepy22  Thanks. I will fix that.

**Comment by vesense** [comment]
Done.Since files are not in the same branch, I have created a new PR (https://github.com/apache/storm/pull/909) for backtype.storm.Config.

**Comment by rfarivar** [comment]
The updated links look good.

**Comment by knusbaum** [comment]
+1

**Pull request merged**
