### PR TITLE
STORM-3168 prevent AsyncLocalizer cleanup from crashing

### PR DESCRIPTION
**Pull request by agresch**
Just catching and logging any error that may be occurring.

### CODE REVIEW

**Comment by srdo** [comment]
Seems reasonable to me, but do we really want to catch the Error subtypes as well?

**Comment by agresch** [comment]
If an error occurred, what should be the expected behavior?  Shutdown?

**Comment by srdo** [comment]
Yes, we probably don't want to keep running if we hit an Error.

**Comment by agresch** [comment]
@srdo - updated to shutdown on errors.  Filed https://issues.apache.org/jira/browse/STORM-3174 to standardize exit codes.  I'm not clear on why we're selecting the values we are.

**Comment by srdo** [comment]
Thanks. +1

**Pull request merged**
