### PR TITLE
fix bin/storm's inconsistent indentation and if-then styling

### PR DESCRIPTION
**Pull request by erikdw**

### CODE REVIEW

**Comment by erikdw** [comment]
Most of the changes are whitespace only, but [there are a couple of non-whitespace changes](https://github.com/apache/storm/pull/751/files?w=0) which consist of joining 2 lines with a `;` between the `if []` and `then`

**Comment by HeartSaVioR** [comment]
+1

**Comment by HeartSaVioR** [comment]
@erikdw Thanks for making it consistent, I merged into master.

**Comment by erikdw** [comment]
@HeartSaVioR : thanks for accepting & merging!

**Pull request merged**
