### PR TITLE
STORM-1637: Correct the master version of storm in storm-mongodb module

### PR DESCRIPTION
**Pull request by abhishekagarwal87**

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
This build error is definitely unrelated (intermittent failure in storm-kafka)

**Comment by revans2** [comment]
+1

**Comment by harshach** [comment]
+1. @abhishekagarwal87 Thanks for the patch. For small fixes like this lets not file a jira

**Comment by abhishekagarwal87** [comment]
Actually @revans2 had already created a JIRA for this. @HeartSaVioR has a PR open for the same bug I think. So this JIRA can be resolved as duplicate.

**Comment by HeartSaVioR** [comment]
Not wanted to take another action, but just leaving a note: according to BYLAWS, change of pom.xml belongs source code change, so we should wait 1 day for initial patch. That's why I didn't merge #1228 after receiving +1 from dossett.
If we want to make exception cases like hotfix (this seems to go to hotfix), I'd love to discuss and reflect to BYLAWS.

**Comment by vesense** [comment]
BTW, I think @revans2 's main concern is **why JDK7 builds pass while JDK8 builds fail with** in JIRA [STORM-1637](https://issues.apache.org/jira/browse/STORM-1637).
img

**Comment by abhishekagarwal87** [comment]
Yes. It is weird. I am taking a look at it.

**Comment by HeartSaVioR** [comment]
The difference is...

* https://travis-ci.org/apache/storm/jobs/116573241 (oraclejdk7, `!storm-core`)

```
[INFO] Scanning for projects...
[INFO] Downloading: https://repository.apache.org/snapshots/org/apache/storm/storm/2.0.0-SNAPSHOT/maven-metadata.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
...
```

No error to download metadata of Storm 2.0.0 SNAPSHOT from repository.apache.org.
*This is the strange point.*

* https://travis-ci.org/apache/storm/jobs/116573242 (oraclejdk8, `!storm-core`)

```
[INFO] Scanning for projects...
[INFO] Downloading: https://repository.apache.org/snapshots/org/apache/storm/storm/2.0.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/storm/storm/2.0.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://nexus.codehaus.org/snapshots/org/apache/storm/storm/2.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.apache.storm:storm:2.0.0-SNAPSHOT/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org: unknown error
[INFO] Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/storm/storm/2.0.0-SNAPSHOT/storm-2.0.0-SNAPSHOT.pom
[INFO] Downloading: https://repository.apache.org/snapshots/org/apache/storm/storm/2.0.0-SNAPSHOT/storm-2.0.0-SNAPSHOT.pom
[INFO] Downloading: https://nexus.codehaus.org/snapshots/org/apache/storm/storm/2.0.0-SNAPSHOT/storm-2.0.0-SNAPSHOT.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.storm:storm-mongodb:[unknown-version] (/home/travis/build/apache/storm/external/storm-mongodb/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.apache.storm:storm:pom:2.0.0-SNAPSHOT from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org and 'parent.relativePath' points at wrong local POM @ line 21, column 13: Unknown host nexus.codehaus.org -> [Help 2]
```

It can't find the metadata from repository.apache.org so go on finding alternative repositories.
And stuck on nexus.codehaus.org, because all codehaus services have now been terminated and maven too.
Please refer https://www.codehaus.org/
I don't have an idea why it searches nexus.codehaus.org, but anyway that's the point why build failed.

**Pull request merged**
