### PR TITLE
STORM-706 . Clarify examples README.

### PR DESCRIPTION
**Pull request by jayunit100**
STORM-706

### CODE REVIEW

**Comment by jayunit100** [comment]
( updated ).  This PR now implements the *compile* scope for intellij, so that it doesnt require hacking the pom file.  I also updated the README

**Comment by d2r** [comment]
Anyone have a link to some document for how to set up a dev environment with IntelliJ IDEA?

I'd like to try this change out if I could.

**Comment by jayunit100** [comment]
examples/storm-starter/README.markdown  is updated in this PR, you can use that link .  Im hoping to merge this soon into storm itself so its all in one place

**Comment by jayunit100** [comment]
hi folks.  anyone interested in merging this or should i close?

**Comment by ptgoetz** [comment]
+1

**Comment by revans2** [comment]
+1

**Pull request merged**
