### PR TITLE
[STORM-1364] logs the storm version when starting

### PR DESCRIPTION
**Pull request by d2r**

### CODE REVIEW

**Comment by unsleepy22** [comment]
LGTM +1

**Comment by d2r** [comment]
```
testPollWhileThereAreNoDataAvailable(backtype.storm.utils.ShellBoltMessageQueueTest)  Time elapsed: 1.005 sec  <<< FAILURE!
junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:201)
	at backtype.storm.utils.ShellBoltMessageQueueTest.testPollWhileThereAreNoDataAvailable(ShellBoltMessageQueueTest.java:55)
```

This is the test I see failing both in this pull request and also on my travis
ci setup.

It does not seem related to my changes, but it is causing the overall check to
fail for storm-core, and that causes the other modules not to be tested.

**Comment by d2r** [comment]
closing/reopening to trigger another ci build

**Comment by revans2** [comment]
+1 looks good to me.

**Comment by knusbaum** [comment]
+1

**Comment by wuchong** [comment]
+1

**Comment by d2r** [comment]
3 failures in nimbus-auth-test for storm-core on jdk8 only.  Need to look at why it happened.

**Comment by darionyaphet** [comment]
It seems just add some log info

**Comment by jerrypeng** [comment]
+1

**Comment by d2r** [comment]
> 3 failures in nimbus-auth-test for storm-core on jdk8 only. Need to look at why it happened.

I did look at these test failures.  They are likely not related to this change.  There is a race condition whenever we try to get an ephemeral port from the system such that sometimes multiple tests launch nimbus nodes with the same port.

Separately I will look into tightening the race and/or locking such that each test case will use only the test nimbus instance that is configured especially for it.

In the meantime, I will close and re-open this pull request to start another travis-ci build.

**Comment by d2r** [comment]
Created [STORM-1377](https://issues.apache.org/jira/browse/STORM-1377) for nimbus-auth-test issues.

Checks have passed, so I will merge this since there are binding +1s and no unresolved issues after 1 day.

**Pull request merged**
