### PR TITLE
(STORM-1674) Idle KafkaSpout consumes more bandwidth than needed

### PR DESCRIPTION
**Pull request by moesol**
* Allows minBytes in fetch request to be configured
      from KafkaConfig.fetchMinBytes.
    * Defaults new configuration KafkaConfig.fetchMinBytes to 1.
    * Defaults fetchMaxWait to 100ms instead of 10000ms.

    Discovered 30 megabits of traffic flowing between a set of KafkaSpouts
    and our kafka servers even though no Kafka messages were moving.
    Using the wireshark kafka dissector, we were able to see that
    each FetchRequest had maxWait set to 10000
    and minBytes set to 0. When binBytes is set to 0 the kafka server
    responds immediately when there are no messages. In turn the KafkaSpout
    polls without any delay causing a constant stream of FetchRequest/
    FetchResponse messages. Using a non-KafkaSpout client had a similar
    traffic pattern with two key differences
    1) minBytes was 1
    2) maxWait was 100
    With these FetchRequest parameters and no messages flowing,
    the kafka server delays the FetchResponse by 100 ms. This reduces
    the network traffic from megabits to the low kilobits. It also
    reduced the CPU utilization of our kafka server from 140% to 2%.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by ptgoetz** [comment]
+1 Nice catch!

**Comment by ptgoetz** [comment]
I'm in the process of merging this. Other committers please hold off. More info to follow...

**Comment by ptgoetz** [comment]
Thanks @moesol I merged this into master, 1.x-branch and 1.0.x-branch.

Note that with 1.0.x-branch this created a conflict, as `KafkaConfig.minFetchByte` had been introduced to do the same thing as your `KafkaConfig.fetchMinBytes` variable. These are public variables, so they make up part of the API.

Since 1.0.1 had already been released with the `minFetchByte` varibable, to ensure backward compatibility I used the `minFetchByte` variable name across branches.

While I prefer the variable name you chose, I think it's more important to ensure backward compatibility. :)

Thanks again!

**Comment by moesol** [comment]
I think it's awesome that this change is getting in! I'll be looking out for the next release that contains this PR.<br> 

Robert Hastings, Lab SDL: 619-553-0826, Cell: 858-395-4436, Moebius: 858-455-5431x210 
SIPR: hasting@spawar.navy.smil.mil 
JWICS: hasting@spawar.navy.ic.gov

**Pull request merged**
