### PR TITLE
STORM-2750：fix double_checked locking

### PR DESCRIPTION
**Pull request by xiaoyong03**
update HBaseSecurityUtil singleton to fix double_checked locking
See url link for details: http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

### CODE REVIEW

**Comment by xiaoyong03** [comment]
@srdo  I have  created an issue for this at https://issues.apache.org/jira and then rename the PR and commit message to contain the issue number as your request.
thanks for the review

**Comment by HeartSaVioR** [comment]
+1 Nice finding.

**Comment by srdo** [comment]
+1, thanks @xiaoyong03. Please squash to one commit and we'll merge after the 24 hour waiting period.

**Comment by xiaoyong03** [comment]
@revans2  this is found in our other projec, and I find there is the same bug in strom while reading source code with static analysis.

**Comment by xiaoyong03** [comment]
thanks @srdo . I squashd my commits to one.

**Comment by srdo** [comment]
Thanks @xiaoyong03, merged to master and 1.x-branch. Keep up the good work :)

**Pull request merged**
