### PR TITLE
Updating Trident RAS Documentation.

### PR DESCRIPTION
**Pull request by knusbaum**
Adding documentation for defaults, clarifying other parts.

### CODE REVIEW

**Comment by jerrypeng** [comment]
LGTM +1

**Comment by ptgoetz** [comment]
+1 Thanks for the update.

**Comment by HeartSaVioR** [comment]
+1

**Comment by HeartSaVioR** [comment]
Thanks @knusbaum , I merged into master, 1.x, 1.0.x branches.

**Pull request merged**
