### PR TITLE
[STORM-1711] Kerberos principals gets mixed up while using storm-hive

### PR DESCRIPTION
**Pull request by arunmahadevan**
Storm-hive uses UserGroupInformation.loginUserFromKeytab which updates the static variable that stores current UGI. Modified HiveUtils.authenticate to use UserGroupInformation.loginUserFromKeytabAndReturnUGI() which returns the new UGI instead of modifying the current UGI.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by vesense** [comment]
LGTM

**Comment by arunmahadevan** [comment]
updated the PR with the commit that fixes the issue found during test.

**Comment by harshach** [comment]
+1

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
We seemed to miss this. Could you confirm if it's still valid?

**Comment by arunmahadevan** [comment]
@HeartSaVioR apparently the proposed changes does not fix the issue. I will close the PR

**Pull request closed without merging**
