### PR TITLE
Fix typo in get_jars_full

### PR DESCRIPTION
**Pull request by dossett**
I was considering writing a python unit test to go with this change, but given the discussion in STORM-904 that doesn't seem useful if this will be migrated to java soon.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1
Test failure should not be relevant.

**Comment by redsanket** [comment]
+1 NB

**Comment by zhuoliu** [comment]
Good catch. +1

**Comment by dossett** [comment]
Closing this a opening a new PR.

**Comment by erikdw** [comment]
Pointer to the new PR referenced above: https://github.com/apache/storm/pull/924

**Pull request closed without merging**
