### PR TITLE
[STORM-643] KafkaUtils repeatedly fetches messages whose offset is out of range

### PR DESCRIPTION
**Pull request by vesense**
STORM-643 fixing for 0.9.x-branch

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1. I'll merge it.

Please note that we're considering only 0.9.x now, so we should try to reproduce and fix from 0.10.x and master later.

**Comment by vesense** [comment]
Thanks for reminding. Yes, I'm working on it.

**Comment by HeartSaVioR** [comment]
@vesense Though I don't know about storm-kafka deeply, seems like ExponentialBackoffMsgRetryManager doesn't care about it. It just delays retrying failed tuples, and doesn't remove failed tuples with invalid offset.

**Comment by vesense** [comment]
@HeartSaVioR Yeah, you are right. We can reproduce the issue with 0.10.x branch too. And I will make a new PR based on master branch.

**Comment by vesense** [comment]
@HeartSaVioR
I have created a new PR(https://github.com/apache/storm/pull/642) based on master branch. Could you take a look? Thx.

**Pull request merged**
