### PR TITLE
Storm-539. Storm hive bolt and trident state.

### PR DESCRIPTION
**Pull request by harshach**

### CODE REVIEW

**Comment by Parth-Brahmbhatt** [comment]
+1

**Comment by harshach** [comment]
@revans2 @ptgoetz  can you please review this. Thanks.

**Comment by ptgoetz** [comment]
+1

You should probably list yourself as a committer sponsor. ;) (You can add me as well if you like.)

**Comment by harshach** [comment]
Thanks @ptgoetz  for the review. Added sponsors and included you.

**Comment by harshach** [comment]
upmerged.

**Pull request merged**
