### PR TITLE
[STORM-4015][DOCS] Update the minimum Java version required to Java 11

### PR DESCRIPTION
**Pull request by engrravijain**
## What is the purpose of the change

Update the documentation to reflect the minimum version of Java required. 

*(Explain why we should have this change)*

Updated documentation

## How was the change tested

Checked the Java version against which storm is being built in github actions. 

*(Explain what tests did you do to verify the code change)*

Not Applicable

### CODE REVIEW

**Comment by engrravijain** [comment]
@rzo1 please review.

**Review by rzo1 — APPROVED** [review]

**Comment by rzo1** [comment]
Thanks @engrravijain - will re-generate the website + close the Jira afterwards. If you have a Jira account, plz let me know, so I can assign the issue accordingly ;-)

**Comment by engrravijain** [comment]
Welcome @rzo1! :) 

Yes, I have a jira account with username **engrravijain**

**Comment by rzo1** [comment]
Website is updated. Couldn't find you in the ASF Jira. Feel free to leave a comment in https://issues.apache.org/jira/browse/STORM-4015 and I will assign it to you later.

Thanks for the doc contribution anyway!

**Pull request merged**
