### PR TITLE
[STORM-1506] It's better to be Integer about port of STORM_ZOOKEEPER_PORT&TRANSACTIONAL_ZOOKEEPER_PORT

### PR DESCRIPTION
**Pull request by hustfxj**
It's better to replace Object by Integer about port of STORM_ZOOKEEPER_PORT&TRANSACTIONAL_ZOOKEEPER_PORT

### CODE REVIEW

**Comment by unsleepy22** [comment]
LGTM +1

**Comment by HeartSaVioR** [comment]
While Utils.getInt(Object) does provide safe conversion, this PR forces type conversion, which breaks unit tests (Nimbus crashed).
Please see https://travis-ci.org/apache/storm/jobs/105184033 and https://travis-ci.org/apache/storm/jobs/105184034.
We can find the reason of ClassCastException from http://clojuredocs.org/clojure.core/type, type of number literal is actually Long in Clojure.

We may want to consider Clojure unless porting is complete.

**Comment by HeartSaVioR** [comment]
After porting whole things to Java, I think we may have a chance to review type usages (based on strong typing) and try not to use Object when possible. This issue seems to be a bit early.

**Comment by revans2** [comment]
@hustfxj, I probably was not clear enough in my review comments that spawned this JIRA.  I was thinking along the lines of @HeartSaVioR.  Once the majority of the code is in java we can review types everywhere.  I wanted this JIRA filed so it is one that we do not forget about.  If you can make all of the tests pass before the full java conversion I am OK with it, but like @HeartSaVioR said you will need to update the clojure code to go from a long which is the clojure default to a int explicitly.

**Comment by HeartSaVioR** [comment]
Yeah, I'm definitely fine to apply this PR if we can address kinds of type issues from Clojure. 
If we're not sure, let's port first and take a look at STORM-1506 again.

**Comment by HeartSaVioR** [comment]
Btw, you may want to see whole tests succeed at least once from local dev. before submitting a pull request.
Storm has random test failures so you may have to run tests several times, but Storm normally doesn't have consistent test failures.

**Comment by hustfxj** [comment]
@HeartSaVioR @revans2  Thanks for your explanation. In fact I'm not particularly familiar with clojure. So I run into issues with local tests. But I will try my best to port clojure to java for storm. Thanks again!

**Pull request closed without merging**
