### PR TITLE
STORM-1922: Supervisor summary default order by host

### PR DESCRIPTION
**Pull request by vesense**
*before fix preview:*
before-fix

*after fix preview:*
after-fix

### CODE REVIEW

**Comment by vesense** [comment]
and, it's easy to cherry-pick to 1.x-branch.

**Comment by harshach** [comment]
+1

**Comment by vesense** [comment]
@HeartSaVioR Can you merge this into 1.0.2 too?

**Comment by harshach** [comment]
Thanks @vesense merged into master,1.x, 1.0.x

**Pull request merged**
