### PR TITLE
STORM-2158: Fix OutOfMemoryError in Nimbus' SimpleTransportPlugin

### PR DESCRIPTION
**Pull request by tibkiss**

### CODE REVIEW

**Comment by ptgoetz** [comment]
+1

**Comment by HeartSaVioR** [comment]
@tibkiss Thanks for contributing. Could you also craft pull request against master if you don't mind? It's recommended unless the patch is for specific version.

**Comment by tibkiss** [comment]
@HeartSaVioR : Sure, will do it shortly. 
I'm wondering: shall make a PR for 1.0.x-branch too?

**Comment by HeartSaVioR** [comment]
@tibkiss 
Normally merger (or other committers) ports back commit to other branches. Multiple PRs are needed only when there're number of conflict so would be better to review porting patches as well.

**Comment by tibkiss** [comment]
@HeartSaVioR : Thanks for the explanation.
Created the PR for master: https://github.com/apache/storm/pull/1741

**Comment by revans2** [comment]
+1

**Pull request merged**
