### PR TITLE
STORM-354: Testing: allow users to pass TEST-TIMEOUT-MS as param for complete-topology

### PR DESCRIPTION
**Pull request by aaronlevin**
It would be nice if `complete-topology` allowed a user to pass in the default timeout as a parameter (rather than just setting it as `5000ms`). I had a test that kept failing by taking too long. 

This PR adds functionality without breaking any existing code. Tests pass.

JIRA ticket: https://issues.apache.org/jira/browse/STORM-354

### CODE REVIEW

**Comment by vkaggalumn** [comment]
Hello!
I am also wondering on how to set this parameter in java? Would somebody comment please?

Thanks

**Comment by vkaggalumn** [comment]
Nevermind!

For anybody that is facing a similar question, this seems to address the issue:

<pre>
Config conf = new Config();
conf.put("TEST-TIMEOUT-MS", 10000);
...
CompleteTopologyParam completeTopologyParam = new CompleteTopologyParam();
completeTopologyParam.setMockedSources(mockedSources);
completeTopologyParam.setStormConf(conf);
</pre>

**Comment by revans2** [comment]
https://github.com/apache/storm/blob/master/storm-core/src/clj/backtype/storm/testing.clj#L190-192

Shows that the environment variable STORM_TEST_TIMEOUT_MS, can be used to set the value globally.  We probably should document this better somewhere.

**Comment by harshach** [comment]
@revans2 its in DEVELOPER.md https://github.com/apache/storm/blob/master/DEVELOPER.md#build-the-code-and-run-the-tests

**Comment by revans2** [comment]
So it is.  I guess I should read the documentation before I start digging though the code :)  Thanks @harshach

**Comment by vkaggalumn** [comment]
Thanks @harshach.

If I am reading the documentation right, I see the following which instructs how to build the storm code base with the STORM_TEST_TIMEOUT_MS set? Being a new user, I am wondering about the this - How should we be setting this (STORM_TEST_TIMEOUT_MS) when using Eclipse to run our tests in our storm project? Or am I not reading this right?

<pre>
# Build the code and run the tests, with specifying default test timeout (in millisecond)
$ export STORM_TEST_TIMEOUT_MS=10000
$ mvn clean install
</pre>

Any pointers would be greatly appreciated.

Many thanks!

**Comment by harshach** [comment]
@vkaggalumn  I don't think we tested that part of dev cycle. Its definitely a valid use case. Most of the time storm tests timeout in a build env for unit tests when a user running all the test suite.  
I just poked around eclipse you can add Environment variable under Run configurations for a project or set a system wide environment variable for STORM_TEST_TIMEOUT_MS.

**Comment by vkaggalumn** [comment]
@harshach Sorry for the delay in my response.

Thanks for your response. I had already tried to pass STORM_TEST_TIMEOUT_MS at runtime (Run Configuration-> environment) which did not seem to work. However, I will double check, try again.

Thanks for your help.

**Pull request merged**
