### PR TITLE
MINOR: Clarify error message when TGT has problems

### PR DESCRIPTION
**Pull request by jacobtolar**
If you're not very familiar with Kerberos, having more explicit instructions in these error messages can be helpful.

### CODE REVIEW

**Comment by Ethanlm** [comment]
Could you please prepend "MINOR" to the commit message and summary? For example https://github.com/apache/storm/pull/2946/commits

**Comment by srdo** [comment]
Thanks @jacobtolar, merged.

@Ethanlm I think if you link your Github account to your Apache id, you can edit PR summaries, and we can use squash and merge to edit commit messages before merge.

**Comment by Ethanlm** [comment]
Okay. Thanks. I thought we don't want to use squash for committers.

**Comment by srdo** [comment]
I think we don't if multiple people have worked on a branch, e.g. if you had made some commits in this branch working alongside Jacob. In that case we don't want to squash to one commit, because we then can't tell who did what.

When there's only one author, I don't think squashing is a problem. It looks like Github puts the real author's name on the squashed commit, and then just lists me as the committer. See https://github.com/apache/storm/commit/9f10f8a14482e4eb1c1323ac86d3c373634539c2

**Comment by srdo** [comment]
Git log for the squashed commit shows

> Author:     jacobtolar <accounts@sheckel.net>
AuthorDate: Fri Jul 26 11:49:05 2019 -0500
Commit:     Stig Døssing <srdo@apache.org>
CommitDate: Fri Jul 26 18:49:05 2019 +0200

While the original commit shows

> Author:     jacobtolar <accounts@sheckel.net>
AuthorDate: Thu May 23 13:27:05 2019 -0500
Commit:     GitHub <noreply@github.com>
CommitDate: Thu May 23 13:27:05 2019 -0500

which I think is okay?

**Comment by Ethanlm** [comment]
I am fine with this

**Pull request merged**
