### PR TITLE
[Minor] Removing obsolete files (TODO and kafka-storm changelog) 

### PR DESCRIPTION
**Pull request by lazyval**
No other storm/external project has changelog and it looks like log became obsolete ever since storm-kafka was incorporated into storm.

### CODE REVIEW

**Comment by lazyval** [comment]
I also doubt that https://github.com/apache/storm/blob/master/TODO should be around

**Comment by lazyval** [comment]
@revans2 any love for it?

**Comment by lazyval** [comment]
@revans2 ping

**Comment by HeartSaVioR** [comment]
@lazyval Great! Thanks. Could you remove TODO, too?

**Comment by revans2** [comment]
+1

**Pull request merged**
