### PR TITLE
STORM-682: supervisor should handle worker state corruption gracefully.

### PR DESCRIPTION
**Pull request by Parth-Brahmbhatt**

### CODE REVIEW

**Comment by nathanmarz** [comment]
-1

Please change the catch block to explicitly return nil. Don't depend on log-warn to do that for you.

**Comment by Parth-Brahmbhatt** [comment]
@nathanmarz done.

**Comment by kishorvpatil** [comment]
Looks good. +1

**Comment by harshach** [comment]
+1. @nathanmarz can you review the latest patch. Thanks.

**Comment by ptgoetz** [comment]
+1

**Comment by ptgoetz** [comment]
We may want to consider applying this to the 0.9.x branch as well.

**Comment by harshach** [comment]
@nathanmarz we need this PR for 0.9.4 release . Please take a look at the latest patch.

**Comment by Parth-Brahmbhatt** [comment]
@ptgoetz I will create new jira for 0.9.x branch and apply the fix.
@nathanmarz given this is blocking the release and you have a -1 vote I would really appreciate if you could take some time to review this again.

**Comment by nathanmarz** [comment]
+1

**Pull request merged**
