### PR TITLE
I have tried to improve the page about symlinks in Windows

### PR DESCRIPTION
**Pull request by alexlehm**

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@alexlehm 
The updated explanation looks good. 
Please split commit message by title and body, and leave only abstraction for the change. You can rebase or amend the commit and force push.

**Comment by alexlehm** [comment]
not complete sure it that is what you mean, I changed the commit message a bit

**Comment by HeartSaVioR** [comment]
@alexlehm Thanks. This is exactly what I want. +1

**Comment by HeartSaVioR** [comment]
@alexlehm Thanks for contribution, I merged this to master, 1.x, 1.0.x branches.

**Pull request merged**
