### PR TITLE
STORM-130. Supervisor getting killed due to java.io.FileNotFoundException: File '../stormconf.ser' does not exist.

### PR DESCRIPTION
**Pull request by harshach**

### CODE REVIEW

**Comment by harshach** [comment]
@revans2 @ptgoetz @d2r @Parth-Brahmbhatt  please take a look at this patch. Thanks.

**Comment by ptgoetz** [comment]
@harshach One nit: white space changes make the diff harder to read. (Though appending '?w=1' to the URL will force github to ignore white space.)

Otherwise, given a cursory review of the changes, I'm +1 initially. I'd like to verify the patch myself and/or give others a chance to do so as well.

Regardless, nice work on tracking down the probable root cause and formulating a fix. This has been an oft reported issue that's difficult to reproduce.

**Comment by harshach** [comment]
Closing this pr will re-open a new one. Thanks.

**Comment by Parth-Brahmbhatt** [comment]
+1, lgtm.

**Pull request closed without merging**
