### PR TITLE
Upgraded HBase version to 1.1.0

### PR DESCRIPTION
**Pull request by satishd**

### CODE REVIEW

**Comment by knusbaum** [comment]
Is there a reason we want to do this?

**Comment by harshach** [comment]
@knusbaum apache hbase moved 1.1 for sometime now. Running 0.98.4 clients in a topology causing dependency issues.

+1 .

**Comment by harshach** [comment]
@knusbaum any update on this. Are you ok with merging this in?

**Comment by knusbaum** [comment]
+1

**Pull request merged**
