### PR TITLE
STORM-950. Apache Storm website redesign.

### PR DESCRIPTION
**Pull request by harshach**

### CODE REVIEW

**Comment by harshach** [comment]
@revans2 how are you running this I didn't see any issues with resources or js missing 404s.
@HeartSaVioR can you please check this PR .  I ran though the links didn't see any broken ones. Can you please point them out . Thanks.

**Comment by harshach** [comment]
@HeartSaVioR @revans2 my bad looks like I missed a commit last time. Please try again. Thanks

**Comment by HeartSaVioR** [comment]
@harshach It seems fixed. Thanks. I'll look into it.

**Comment by HeartSaVioR** [comment]
@harshach 
Looks beautiful to me. And spots I reported seems be fixed.
I looked at whole things and found new points to fix.

downloads.html
—
- Download link for “Current Beta Release" is still pointed to 0.10.0-beta, not 0.10.0-beta1.

multi-language.html
—
- Adapters that implement this protocol exist for Ruby, Python, Javascript, Perl.
  - Link of Ruby, Python, Javascript are broken. It should link to storm-multilang module.

documentation.html
—
- "#" anchor doesn't work, so when we move to link and back, it always points to "basics of storm".

documentation.html#basic
—
- Javadoc link points to Nathan’s github repo. It should be replaced to recent javadoc.

documentation/Serialization.html
—
- We should replace all links about Kyro to github, https://github.com/EsotericSoftware/kryo.

documentation/Setting-up-a-Storm-cluster.html
—
- The Storm releases can be downloaded from here.
  - It would be better to link "Download" page instead of github releases.

documentation/Clojure-DSL.html
—
- "backtype.storm.clojure" link points to 0.5.3 branch, which should point to master branch.
- "Direct groupings" links to its page, "Clojure-DSL", which doesn't explain direct groupings. 

documentation/Metrics.html
—
- "builtin metrics" and "builtin_metrics.clj" link points to specific commit, which would be better to point to master branch.

documentation/Acking-framework-implementation.html
—
- "Storm's acker" and "execute method", and "put the record" link points to specific commit, which would be better to point to master branch.

contribute/Contributing-to-Storm.html
—
- Modules built on top of Storm
  - Do we still support @stormprocessor? If not, it would like to guide him/her to become part of storm-external.

Overall
—
- All links which point to javadoc are broken. Can I expect it will work when site resources are deployed to official site?
- Minor: We would be better to create new page Kafka-and-Storm.html and replace Kestrel-and-Storm.html.
- Minor: How about removing all documents which are based on older than 0.9.0?

**Comment by harshach** [comment]
@HeartSaVioR Thanks for the review. 
All links which point to javadoc are broken. Can I expect it will work when site resources are deployed to official site?
Yes this will work once they deployed on the official site.
Minor: We would be better to create new page Kafka-and-Storm.html and replace Kestrel-and-Storm.html.
Since the patch is big and we are trying to use the existing content we probably should be file follow-up jiras  to replace them.
Minor: How about removing all documents which are based on older than 0.9.0?
I'll try to look into it but we should be doing a follow-up jiras to do this. Since this JIRA more about the redesign.

Thanks.

**Comment by HeartSaVioR** [comment]
@harshach Agreed. Let's focus to redesign  :)

**Comment by harshach** [comment]
@HeartSaVioR Thanks. Will file a follow-up jira for the issues you raised.

**Comment by harshach** [comment]
@ptgoetz can you take a look at it as well.

**Comment by harshach** [comment]
@revans2 @ptgoetz waiting for you to take a look at it before we can merge it in.

**Comment by ptgoetz** [comment]
I have a few things that I think need to be fixed before we publish this. But rather than enumerate every last little thing and ask you to fix them, I'd rather jump in and fix them myself and let others do the same.

I propose we move this off to an empty branch that just contains the storm website code -- similar to the way github pages work. Then anyone could help fix things by opening a pull request against that branch. Then once we are all satisfied enough to publish it, we do so and remove the website code from the main source branches.

I don't have a reference handy, but I think ASF INFRA has a way to publish web content from a specially-named branch (similar to how "gh-pages" branches work). That would eliminate the extra step of generating the site to SVN and committing that way. I'll look into this option some more.

How does that sound?

**Comment by harshach** [comment]
@ptgoetz if these issues are layout please list them out we can send a new patch. I don't think website layout needs to be blocked on docs or other fixes. I want to see this published soon rather than make it into feature branch and taking time to fix this. If its about docs we can file follow-up jiras to fix those. Even if its layout issues these should be minor and can be make it into follow-up jiras. It doesn't need to get into feature branch and IMHO its ready get published.

**Comment by ptgoetz** [comment]
@harshach I'm not suggesting we create a feature branch, I'm suggesting we change the way we publish the site to make it easier for people to contribute to. I forgot to mention it before, but I'm happy to set that up.

Some of the issues I see are minor layout issues (twitter feed should be below news, for example), some are maintenance-related (the recent news on the home page should be generated, not hard-coded in HTML), and some are related to ASF policy (we are pulling in content from facebook.com and google.com domains that potentially includes end-user tracking, and I'm not sure if that's allowed -- I'd have to check).

I'm not worried about docs/textual content, that can be fixed anytime.

**Comment by harshach** [comment]
@ptgoetz will look into the fb & goog calls and also generating the news feed. As far as separate branch goes thats fine by me but another issue could be that the doc contributions will not be counted towards master branch rather into another branch and also merging those changes into another branch.

**Comment by harshach** [comment]
@ptgoetz removed references to google & fb and news widget is on top. Can you take a look.

**Comment by harshach** [comment]
@ptgoetz upmerged. Can you take a look.

**Comment by ptgoetz** [comment]
+1

I will merge this into a new empty "asf-site" branch and work with INFRA to setup git-based publishing, which will eliminate the extra svn step to publish the site.

In the meantime, we can let contributors open up pull requests against the asf-site branch and start fixing some of the issues that still exist with the redesign.

**Comment by ptgoetz** [comment]
@harshach This has been merged into the "asf-site" branch. Can you close this pull request?

**Pull request closed without merging**
