### PR TITLE
STORM-1533: IntegerValidator for metric consumer parallelism hint

### PR DESCRIPTION
**Pull request by abhishekagarwal87**

### CODE REVIEW

**Comment by knusbaum** [comment]
Please revert the pom changes. Other than that, +1

**Comment by abhishekagarwal87** [comment]
Thanks for review @knusbaum . This PR has fix for STORM-1533 and STORM-1534. Since commits have the individual JIRA ids attached, I have sent the fix in same PR.

**Comment by revans2** [comment]
+1 looks good to me.

**Comment by abhishekagarwal87** [comment]
Thanks @revans2 - can you also merge this PR? This affects 1.x release so it should be backported as well.

**Pull request merged**
