### PR TITLE
[STORM-1528] Fixing MetricsUtils csv directory location

### PR DESCRIPTION
**Pull request by kishorvpatil**
I was calling `ConfigUtils.absoluteHealthCheckDir` instead of `ConfigUtils.absoluteStormLocalDir`. I need to be more careful..

### CODE REVIEW

**Comment by d2r** [comment]
+1

**Comment by knusbaum** [comment]
+1

**Comment by ppoulosk** [comment]
+1, NB

**Comment by d2r** [comment]
Still +1. Looks like an unrelated failure.

**Pull request merged**
