### PR TITLE
STORM-1126:  allow for configMethods with no args (Flux)

### PR DESCRIPTION
**Pull request by ashnazg**

### CODE REVIEW

**Comment by revans2** [comment]
This looks good to me I am +1, but I would like to have someone more familiar with Flux take a look too.

@ptgoetz can you take a look or point out someone who can?

**Comment by ashnazg** [comment]
Do we think this one can get in for 0.11?

**Comment by ptgoetz** [comment]
+1

@ashnazg Yes, I will add to the list.

**Comment by ashnazg** [comment]
Is there a trick to mailing dev@storm.apache.org?  I've only gotten one out of six emails to show up there.  I'm sending them as plaintext, but I'm not a subscriber.  Is it moderated, and perhaps infrequently checked?

**Pull request merged**
