### PR TITLE
STORM-2877: Backport for 1.0.x-branch

### PR DESCRIPTION
**Pull request by srishtyagrawal**
Backporting this Storm UI change which has already been merged in master. 

JIRA ticket: https://issues.apache.org/jira/browse/STORM-2877
Merged PR in master branch: https://github.com/apache/storm/pull/2505

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@srishtyagrawal 
Could you also raise pull request against 1.1.x branch?

**Comment by srishtyagrawal** [comment]
Definitely @HeartSaVioR! Thanks for merging this one.

**Comment by srishtyagrawal** [comment]
@HeartSaVioR I see STORM-2877 in the [commit history for 1.1.x branch](https://github.com/apache/storm/commits/1.1.x-branch). Did you cherry-pick the changes already? I don't need to create a backport PR now, right?

**Comment by HeartSaVioR** [comment]
@srishtyagrawal Yes right, the cherry-picking was hopefully easy one. :)

**Comment by srishtyagrawal** [comment]
Thanks for confirming that @HeartSaVioR. We have  the changes for`STROM-2877-Introduce an option to configure pagination in Storm UI` in all the development branches which are 1+

**Pull request merged**
