### PR TITLE
[STORM-1469] Decommissioning SimpleTransportPlugin and configuration

### PR DESCRIPTION
**Pull request by kishorvpatil**
This pull request awaits merging in #1173 merged into 1.x-branch as well.

### CODE REVIEW

**Comment by revans2** [comment]
+1 not sure why travis failed.  Didn't even try to build in most cases.

**Comment by ptgoetz** [comment]
+1. The travis failures seem like a red herring. All tests passed in my environment.

**Comment by d2r** [comment]
+1

**Comment by ptgoetz** [comment]
Merged #1179 to 1.x-branch.

**Pull request merged**
