### PR TITLE
STORM-924:Set the file mode of the files included when packaging release packages

### PR DESCRIPTION
**Pull request by caofangkun**
Ubuntu 14.04
Apache Maven 3.3.3

## Without this PR:
image

##  With this PR
image

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
How about setting file mode to storm_env.ini too?

**Comment by caofangkun** [comment]
Thanks @HeartSaVioR . I have fixed as you mentioned.

**Comment by HeartSaVioR** [comment]
+1

**Comment by HeartSaVioR** [comment]
I suffered this issue when I created binary dist file and install manually. 
bin/storm script doesn't have permission for "execute".

**Comment by HeartSaVioR** [comment]
Now I'm not sure to know what happens.

I created binary dist file from master, 0.10.x-branch, 0.9.x-branch and extract it, and confirmed that bin/storm doesn't have permission for "execute" for the all branches.
(without applying this PR)

But when I download binary from storm official site, bin/storm has permission for "execute". I checked 0.10.0-beta1 and 0.9.5.

@caofangkun I'm sorry, but I admit I can't understand the situation and change my vote from +1 to +0. 
@ptgoetz Could you explain this situation, and take a look this PR?

**Comment by caofangkun** [comment]
@HeartSaVioR 
 I came across the same issue when I  created binary dist from master too, and that's why I pushed this PR.

**Comment by revans2** [comment]
Hmm, when I build it on my mac everything shows up fine, either with or without this fix. +1

**Comment by revans2** [comment]
@HeartSaVioR I'm not sure exactly what is happening here either but the patch does not hurt anything.  If you want to dig more into exactly what is happening we can file another JIRA to look into it.

**Pull request merged**
