### PR TITLE
STORM-2458: Kafka Spout should allow hooking up custom logic when ret…

### PR DESCRIPTION
**Pull request by souravmitra**
Kafka Spout should allow hooking up custom logic when retries have exhausted

### CODE REVIEW

**Comment by souravmitra** [comment]
Hello @HeartSavior @vesense Would you mind having a look, it's a very small change. Thanks

**Comment by vesense** [comment]
Looks good to me. +1

**Comment by souravmitra** [comment]
@vesense : Would you mind merging this in master please, would be very helpful. Appreciate your quick feedback.

**Comment by vesense** [comment]
@souravmitra Yes, I will merge it later.

**Pull request merged**
