### PR TITLE
STORM-829: Hadoop dependency confusion

### PR DESCRIPTION
**Pull request by YvonneIronberg**

### CODE REVIEW

**Comment by knusbaum** [comment]
Just a couple comments:
 - Would you please include the summary of the Jira in the title of the pull request
 - There are a bunch of commits here. Would you squash them?
 - I think the jira calls for the removal of `hadoop-auth` from storm-core's pom. Have you found a reason for keeping it?

**Comment by YvonneIronberg** [comment]
Thanks for your review, @knusbaum !

I've followed your suggestions (title, rebase, remove hadoop-auth in storm-core/pom.xml).

**Comment by knusbaum** [comment]
+1 - Compiles and all tests pass.

**Comment by YvonneIronberg** [comment]
Thanks, @knusbaum .

**Pull request merged**
