### PR TITLE
STORM-3397: Upgrade to Zookeeper 3.5.5

### PR DESCRIPTION
**Pull request by srdo**
https://issues.apache.org/jira/browse/STORM-3397

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Does this require end users to set up Zookeeper 3.5 to work correctly, or is it also compatible with Zookeeper 3.4 as well?

**Comment by srdo** [comment]
@HeartSaVioR I would not expect this to be compatible with Zookeeper 3.4 servers, no.

**Comment by aishwaryasoni1991** [comment]
When is it planned for a merge? Is it tested already?

**Comment by srdo** [comment]
@aishwaryasoni1991 As far as I'm aware, no one has worked on this since last year. You are welcome to pick it up if you would like to see this finished.

**Comment by rzo1** [comment]
> @aishwaryasoni1991 As far as I'm aware, no one has worked on this since last year. You are welcome to pick it up if you would like to see this finished.

@srdo Are there any strict objections regarding an upgrade to 3.6.x or 3.7.x ? If not, I could probably give it a try (related to https://issues.apache.org/jira/browse/STORM-3817)

**Comment by srdo** [comment]
@rzo1 I would try asking on the dev@storm.apache.org mailing list. I'd imagine that upgrading to 3.7 would be fine, but I don't really know. People on the mailing list are probably more in the know than me.

I'm closing this PR, but feel free to use the code as a starting point if you want.

**Comment by rzo1** [comment]
> @rzo1 I would try asking on the [dev@storm.apache.org](mailto:dev@storm.apache.org) mailing list. I'd imagine that upgrading to 3.7 would be fine, but I don't really know. People on the mailing list are probably more in the know than me.
> 
> I'm closing this PR, but feel free to use the code as a starting point if you want.

Thanks for the fast response. I will drop a mail on the list.

**Pull request closed without merging**
