### PR TITLE
storm-hdfs : change visibility of create and closeOutputFile methods to protected

### PR DESCRIPTION
**Pull request by jnioche**
When extending HdfsBolt it can be useful to be able to override the methods createOutputFile() or closeOutputFile(), for instance to add a header or footer to the files created. This is currently not possible when the class is outside the `org.apache.storm.hdfs.bolt` package. This patch makes it possible.

### CODE REVIEW

**Comment by revans2** [comment]
+1 looks fine to me.

**Comment by dossett** [comment]
Would there be a drawback to making all of the abstract methods protected if we want to support end user extensions?

**Comment by ptgoetz** [comment]
+1

**Comment by jnioche** [comment]
@dossett good idea - I have just committed your suggestion
@revans2 and @ptgoetz \: will the content of the master branch become 2.x and if so could this  be committed to the next 1.x release?

**Comment by ptgoetz** [comment]
@jnioche yes, this can go into 1.0, all you need to do is request so (which you have). No need to open a second pull request unless it doesn't apply cleanly to the 1.x branch or a committer requests it.

I generally will try to resolve conflicts when merging, and punt back to the contributor when necessary if the conflicts are too ugly.

**Comment by jnioche** [comment]
@ptgoetz perfect, thanks. BTW I really like the HDFS module, great work! Would be good to have compression for HdfsBolt, I might have a go at implementing that.

**Comment by jnioche** [comment]
Anything blocking this from being committed (apart from committers' availability)?

**Comment by revans2** [comment]
@jnioche just me not getting to it.  Will merge it in now...

**Comment by revans2** [comment]
Thanks @jnioche I merged this into master and branch 1.

**Comment by jnioche** [comment]
thanks for having taken the time to do it @revans2, much appreciated

**Pull request merged**
