### PR TITLE
[STORM-710] bin/storm command list out all the classes in the output for a command

### PR DESCRIPTION
**Pull request by oleg-ost**
Added -v flag for all bin/storm commands.
Long commands' outputs are removed.
Using -v flag prints traditional long output.

### CODE REVIEW

**Comment by revans2** [comment]
I like the concept, but by having storm.py pull the -v out of the command line, it now makes it impossible for any command to use -v any other way.  This is not a big deal for the typical storm commands, but for storm jar it is backwards incompatible.  This is especially a problem for something that for some reason had a -v with an argument.  I would much rather use an environment variable, or a rather log parameter like '--storm-system-verbose' which is not likely to have any collision.

**Comment by harshach** [comment]
@oleg03 can you send us a new patch with @revans2 feedback . Thanks.

**Comment by revans2** [comment]
@oleg03 I don't really like the idea of adding in a -v option that restricts all other commands, including storm jar from supporting it.  I would much rather have a long parameter that is unlikely to collide with something someone else is already using, or us a config or environment variable to trigger it instead.

**Comment by knusbaum** [comment]
Closing this. Feel free to reopen with updates.

**Pull request closed without merging**
