### PR TITLE
.NET Core 2.0 multi-lang adapter

### PR DESCRIPTION
**Pull request by oizu**
There are some instructions in README file on how to build and test the project. Let me know if any questions arose.

### CODE REVIEW

**Comment by MaurGi** [comment]
Hello - we are proposing a new multilang adapter for .net core - this is in the storm-multilang/dotnet folder - 
In the folder we have a dotnet project for the adapter and then a dotnet project for the sample 
We also use Flux to define the topology, so there is a flux yaml config file - 

Do we need to get a Jira issue to have a reviewer assigned to this?
Thanks -

**Comment by HeartSaVioR** [comment]
@oizu @MaurGi 
Hello Azure team, please follow up the Storm developer mailing list since such discussion is taking place. If you're not subscribing dev mailing list, here's a link for tracking thread.

https://mail-archives.apache.org/mod_mbox/storm-dev/201804.mbox/%3C59AFF170-49DE-4F83-A7B9-23616DA21D0B@gmail.com%3E

**Comment by MaurGi** [comment]
Darn –
Did not realize that you replied but we did not receive the mail –
Looking at the thread now -

-MG-

**Comment by oizu** [comment]
The adapter will be published in another GitHub repository.

**Pull request closed without merging**
