### PR TITLE
STORM-1027: Use overflow buffer for emitting metrics

### PR DESCRIPTION
**Pull request by abhishekagarwal87**

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
can someone review this?

**Comment by HeartSaVioR** [comment]
@abhishekagarwal87 Great. Could you apply it to bolt, too?

**Comment by abhishekagarwal87** [comment]
Applied the same to bolt as well.

**Comment by HeartSaVioR** [comment]
+1

**Comment by abhishekagarwal87** [comment]
Can this PR be merged now?

**Comment by HeartSaVioR** [comment]
@abhishekagarwal87 Sorry for the delay. I'll merge it.

**Pull request merged**
