### PR TITLE
STORM-2209: Update documents adding new integration for some external…

### PR DESCRIPTION
**Pull request by vesense**
… systems

### CODE REVIEW

**Comment by revans2** [comment]
+1 looks good to me.  Although I am not familiar with all of the bolts, spouts, etc listed here to be sure that the code in the examples is correct.

**Comment by HeartSaVioR** [comment]
+1 I think @vesense copied the content from README.md for each of external modules.

**Comment by vesense** [comment]
@revans2 @HeartSaVioR Yes, the new files are copied from external modules README.md.

**Comment by vesense** [comment]
Added kubernetes integration.

**Comment by revans2** [comment]
Still +1

**Comment by vesense** [comment]
@revans2 @HeartSaVioR I think this PR should be cherry-picked to 1.x-branch since 1.x has contained these new modules . And we'd better sync documents to storm site.

**Comment by vesense** [comment]
I created https://github.com/apache/storm/pull/1802 for 1.x-branch.

**Pull request merged**
