### PR TITLE
[STORM-400] Thrift upgrade to thrift-0.9.2

### PR DESCRIPTION
**Pull request by kishorvpatil**

### CODE REVIEW

**Comment by ptgoetz** [comment]
Looks like this needs an up merge, but I'm +1 for the patch.

**Comment by kishorvpatil** [comment]
@ptgoetz, Thanks for reviewing this. I have up merged the changes.

**Comment by revans2** [comment]
The changes look good for the most part, but I am seeing a hang that comes up rather frequently.

```
"main" #1 prio=5 os_prio=31 tid=0x00007fc339801000 nid=0x1303 waiting on condition [0x000000010357a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000776c693f0> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at backtype.storm.daemon.drpc$service_handler$reify__7034.execute(drpc.clj:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at backtype.storm.LocalDRPC$_execute.invoke(LocalDRPC.clj:35)
	at backtype.storm.LocalDRPC.execute(Unknown Source)
	at backtype.storm.drpc_test$fn__1523$fn__1526.invoke(drpc_test.clj:189)
	at backtype.storm.drpc_test$fn__1523.invoke(drpc_test.clj:189)
	at clojure.test$test_var$fn__7187.invoke(test.clj:704)
	at clojure.test$test_var.invoke(test.clj:704)
	at clojure.test$test_vars$fn__7209$fn__7214.invoke(test.clj:722)
	at clojure.test$default_fixture.invoke(test.clj:674)
	at clojure.test$test_vars$fn__7209.invoke(test.clj:722)
	at clojure.test$default_fixture.invoke(test.clj:674)
	at clojure.test$test_vars.invoke(test.clj:718)
	at clojure.test$test_all_vars.invoke(test.clj:728)
	at clojure.test$test_ns.invoke(test.clj:747)
	at clojure.core$map$fn__4245.invoke(core.clj:2559)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	- eliminated <0x00000007757dec88> (a clojure.lang.LazySeq)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	- locked <0x00000007757dec88> (a clojure.lang.LazySeq)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1654)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.test$run_tests.doInvoke(test.clj:762)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at com.theoryinpractise.clojure.testrunner$eval12750$fn__12755$fn__12812.invoke(run-test1041168096946393675.clj:123)
	at com.theoryinpractise.clojure.testrunner$eval12750$fn__12755.invoke(run-test1041168096946393675.clj:120)
	at com.theoryinpractise.clojure.testrunner$eval12750.invoke(run-test1041168096946393675.clj:81)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$script_opt.invoke(main.clj:336)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

**Comment by knusbaum** [comment]
+1

I was having the same issues as @revans2  until I ran `mvn install -DskipTests` After that, `mvn test` has succeeded consistently.

**Comment by revans2** [comment]
the workaround from @knusbaum didn't work for me, but I also hit the same issue without this patch in, so I think it is a race condition that was not modified by this patch.  I am OK with merging this in as is, but I will keep trying to track down the root cause.

**Comment by darionyaphet** [comment]
what is difference between thrift 0.9.0 and 0.9.2 ?

**Comment by kishorvpatil** [comment]
@darionyaphet, Thrift 0.9.2 includes python hash function. [https://issues.apache.org/jira/browse/THRIFT-2621]. Without this change, we were using @nathanmarz 's storm specific thrift branch.

**Pull request merged**
