### PR TITLE
STORM-1136: Command line module to return kafka spout offsets lag and…

### PR DESCRIPTION
**Pull request by priyank5485**
… display in storm ui.

STORM-1136: Missed file in previous commit

### CODE REVIEW

**Comment by lichenglongqi** [comment]
Hi，my dear friends,I don't know where to ask a question,so I do it here,forgive me.I have a problem,I want the kafka spout offsets lag to display in the storm ui,but I don't know how to make it happen. my storm version is apache-storm-1.0.4 . AndI am not a programer,I am an Operation & Maintenance Engineer,do you have a  document about this,thank you very muck @priyank5485 @asfgit @schleyfox @trevor @mrflip

**Comment by priyank5485** [comment]
@lichenglongqi You should not have to do anything. The lag should automatically show up in storm ui on the topology page after you submit a topology that has kafka spout in it. 1.0.4 does not have that feature. Can you try 1.1.1 ?

**Comment by lichenglongqi** [comment]
@priyank5485  Thank you for your time to reply,and I want to ask more questions.My apache-storm version is 1.0.4 if I update the version to 1.1.1,a lot of code changes, and the programmers do not want to do this thing.So I beg you to teach me how to make it happen on 1.0.4? You can also send email to me (lichenglongqi@outlook.com).Thank a lot!

**Comment by priyank5485** [comment]
@lichenglongqi I dont think we can backport this to 1.0.4. You can ask on the storm dev email group.

**Pull request merged**
