### PR TITLE
[STORM-3233] Update zookeeper version to 3.4.14, master

### PR DESCRIPTION
**Pull request by pacham7**

### CODE REVIEW

**Comment by srdo** [comment]
The change looks good. Please include the issue number in the commit message, it makes it easier for us to track why a change was made.

**Comment by pacham7** [comment]
Done... I think.

**Comment by srdo** [comment]
@pacham7 Could you squash back to one commit?

**Comment by srdo** [comment]
So there is only one commit with the message "[STORM-3233] Update zookeeper version to 3.4.14"

**Comment by pacham7** [comment]
@srdo Done, thanks.

**Comment by srdo** [comment]
Test failure looks like a bit of flakiness in the integration test. Might see if I can reproduce it at some point, but it is an issue on current master as well.

Thanks for the PR. +1. We can merge after the 24 hour waiting period.

**Pull request merged**
