### PR TITLE
remove the new features of JAVA 1.7.

### PR DESCRIPTION
**Pull request by ziyunhx**
ThreadLocalRandom,System.lineSeparator() and Integer.compare are JAVA 1.7 feature. Change these to support JAVA 1.6.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Sorry but it's intended. Storm drops supporting JDK 1.6 in Apache Storm 0.10.0 and above.

**Comment by ziyunhx** [comment]
But the document of 2.0.0-SNAPSHOT is still support JAVA 6.
http://storm.apache.org/releases/2.0.0-SNAPSHOT/Setting-up-a-Storm-cluster.html

**Comment by HeartSaVioR** [comment]
I guess we missed updating the doc. Could you please file an issue, or craft pull request fixing on the doc directly? It should be applied to master, 1.x-branch, 0.10.x-branch.

**Comment by ziyunhx** [comment]
okay

**Pull request closed without merging**
