### PR TITLE
STORM-1749: Fix storm-starter github links

### PR DESCRIPTION
**Pull request by abhishekagarwal87**

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1
It should be backported to 1.x-branch, 1.0.x-branch.

**Comment by abhishekagarwal87** [comment]
Thanks a lot @HeartSaVioR. This PR fixes the github links but to correct the documentation,  svn repo has to updated. Here is a page for example pointing to wrong location of storm-starter - 
http://storm.apache.org/releases/2.0.0-SNAPSHOT/Clojure-DSL.html

**Comment by HeartSaVioR** [comment]
@abhishekagarwal87 
Yes you're right. I'll reopen the issue and keep issue to be open until I have some time to reflect change to the website.

**Comment by HeartSaVioR** [comment]
reopened the jira issue.

**Pull request merged**
