### PR TITLE
STORM-1602 Blobstore UTs are failed on Windows

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* ensures objects of InputStream / OutputStream are closed after used
  * clojure: with-open
  * java: try-with-resource
* skip checking symbolic link in LocalizerTest when on Windows
  * Windows seems not handle symbolic link in compressed file properly

Some integration tests are still failing on Windows, but it should be handled with another issues.

I'll also address this based on master immediately.

Please have a look. Thanks!

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
#1229 is based on master branch.

**Comment by revans2** [comment]
I assume they all pass on windows so +1

The test failure looks like it is a bug with the mongodb pom.xml that JDK8 does not like but JDK7 seems OK with.  Very odd.  Filed a JIRA for it though.

**Comment by redsanket** [comment]
+1

**Comment by HeartSaVioR** [comment]
@revans2 Very odd indeed... It should give us error because of storm-mongo module.

**Pull request merged**
