### PR TITLE
[STORM-1122] Fix the format issue in Utils.java

### PR DESCRIPTION
**Pull request by zhuoliu**
Delete the abandoned comment "(defn xxx )" function, 
fix a bunch of messed indention, 
unify inconsistent space format, 
expand "import java.io.*" and "import java.util.*" in the file header.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Nice, +1

**Comment by knusbaum** [comment]
+1

**Comment by revans2** [comment]
+1 nice to see it consistent.

**Comment by revans2** [comment]
We probably want to cherry-pick this to 0.10.x and maybe even 0.9.x.  Just so porting patches between them is not a pain.

**Comment by HeartSaVioR** [comment]
I merge it into master and 0.10.x-branch, but not 0.9.x since we want to fade out 0.9.x.

**Pull request merged**
