### PR TITLE
STORM-329: fix cascading Storm failure by improving reconnection strategy and buffering messages

### PR DESCRIPTION
**Pull request by miguno**
This is an improved version of the original pull request discussed at https://github.com/apache/storm/pull/268.  Please refer to the discussion in the link above.

**Note**:  Please give attribution to @tedxia when merging the pull request as he did a lot (most?) of the work in this pull request.

The changes of this pull request include:

- Most importantly, we fix a bug in Storm that may cause a cascading failure in a Storm cluster, to the point where the whole cluster becomes unusable.  This is achieved by the work described in the next bullet points.
- We refactor and improve the Netty messaging backend, notably the client.
- During the initial startup of a topology, Storm will now wait until worker (Netty) connections are ready for operation.  See the [original discussion thread](https://github.com/apache/storm/pull/268) for the detailed explanation and justification of this change.

@clockfly, @tedxia: Please add any further comments to STORM-329 to this pull request, if possible.

### CODE REVIEW

**Comment by miguno** [comment]
Note: All of the code review comments by  of @clockfly above that were added before this pull was created have already been addressed.

**Comment by clockfly** [comment]
+1

**Comment by clockfly** [comment]
Do we want to fix the commit log?

**Comment by clockfly** [comment]
Something like git rebase -i upstream/master

**Comment by miguno** [comment]
I tried rebasing (also to fix the incorrect commit message that starts with STORM-32*7*) but gave up after several failed attempts.  Feel free to give it a try though -- maybe your git-fu is better than mine. :-)

**Comment by clockfly** [comment]
I see, there are multiple remote-merging, which then make rebase impossible. 

How about create a patch file against master and then apply the patch with new commit logs?

**Comment by miguno** [comment]
Closed in favor of updated PR at https://github.com/apache/storm/pull/429.

The updated PR uses a single commit to ensure we have a cleaner commit history in our Storm repo (see @clockfly suggestion above).

Note: I attempted to rebase to retain the original commit history of the pull request itself, but I ran into several rebase/merge conflicts and didn't want to risk screwing up the patch while manually resolving the various conflicts.

Sorry for the confusion!

**Comment by miguno** [comment]
I did exactly this in #429.

**Pull request closed without merging**
