### PR TITLE
[STORM-643] KafkaUtils repeatedly fetches messages whose offset is out of range

### PR DESCRIPTION
**Pull request by vesense**
STORM-643 fixing based on master branch

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by 2new** [comment]
+1

**Comment by HeartSaVioR** [comment]
@vesense 
Seems like your patch removes one invalid offset per each fill().

We may apply same optimization here.
When TopicOffsetOutOfRangeException occurs, we can remove invalid offsets from ExponentialBackoffMsgRetryManager at once.

Though we should loop and examine each records to find them, it would be better than current.

**Comment by vesense** [comment]
@HeartSaVioR Thanks. I will fix that.

**Comment by vesense** [comment]
@HeartSaVioR
I have completed the optimization. Could you take a look? Thx.

**Comment by lazyval** [comment]
Minor complain, but [next time]  it would be handy to keep commit messages a bit more descriptive

storm 2015-07-20 14-42-47

**Comment by vesense** [comment]
@lazyval Thank you for pointing out my mistake. I'm sorry for that. It won't happen next time.
Thanks again.

**Comment by HeartSaVioR** [comment]
@vesense Since it contains too many commits compared to changed lines, I will try to squash commits into one and merge.

**Comment by HeartSaVioR** [comment]
Forgot to give +1. :)

**Comment by HeartSaVioR** [comment]
@vesense 
Thanks for quick work! I merged this into master and 0.10.x-branch respectively.

- master: https://github.com/apache/storm/commit/f091743d9ebc935c9bbbc210095884c3d819632b
- 0.10.x-branch: https://github.com/apache/storm/commit/05bd1e36697fe7038284833032da262afb82ac99

I squashed your commits into one before merging, so Github can't recognize this PR to closed.
Could you close this PR?

**Comment by vesense** [comment]
@HeartSaVioR OK. thx.

**Comment by prokopowicz** [comment]
we've seen a related problem when a custom scheme returns an empty list of lists via generateTuples.  The code in partitionManager does not ack the offset in that case.  It should be made clear that a scheme should not return an empty list of lists, but null, if it deserializes no objects.  Or, this code in PartitionManager should be fixed to treat an empty list of lists in the same way it treats a null list.

```java
            if (tups != null) {
                if(_spoutConfig.topicAsStreamId) {
                    for (List<Object> tup : tups) {
                        collector.emit(_spoutConfig.topic, tup, new KafkaMessageId(_partition, toEmit.offset));
                    }
                } else {
                    for (List<Object> tup : tups) {
                        collector.emit(tup, new KafkaMessageId(_partition, toEmit.offset));
                    }
                }
                break;
            } else {
                ack(toEmit.offset);
            }
```

**Pull request closed without merging**
