### PR TITLE
[STORM-1720]Support GEO in storm-redis

### PR DESCRIPTION
**Pull request by darionyaphet**
[STORM-1720](https://issues.apache.org/jira/browse/STORM-1720) GEO is a new feature in redis 3.2 . It's useful in Geography calculate.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@darionyaphet Builds are failing at CI for all kinds of JDK. Could you take a look at?

**Comment by darionyaphet** [comment]
@HeartSaVioR something failed in `storm-core` module . It's has nothing to this pull request :)

**Comment by HeartSaVioR** [comment]
@darionyaphet 
I guess it is not. https://travis-ci.org/apache/storm/jobs/128282521

```
[ERROR] /home/travis/build/apache/storm/external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisClusterContainer.java:[63,32] unreported exception java.io.IOException; must be caught or declared to be thrown
```

**Comment by darionyaphet** [comment]
@HeartSaVioR Yes I'm fixing this problem  thank you ~

**Comment by darionyaphet** [comment]
@HeartSaVioR 

I have running a rebuild and there are three test SUCC and one Failed .I found two job running on JDK 8  one is OK and another is Failed . 

Is it ok ? Or this test is not exactly at each time ?

**Comment by HeartSaVioR** [comment]
@darionyaphet That would be fine. Could you please rebase & squash commits since this is small fix and commit log for second commit does have typo?

**Comment by darionyaphet** [comment]
@HeartSaVioR  merge into one commit :)

**Comment by HeartSaVioR** [comment]
@darionyaphet Thanks for quick turnaround. +1

**Comment by HeartSaVioR** [comment]
@darionyaphet 
It's merged to master but github seems not recognize since I reword commit's log message.
Could you please close? Thanks for the work!

**Comment by darionyaphet** [comment]
@HeartSaVioR I don't very clearly about commit process . You can review pull request after I push commit to my repo . If the PR is fine , you will merge it into apache's master branch and my commit branch will close ? thanks

**Comment by HeartSaVioR** [comment]
@darionyaphet Yeah, right. I've just don't follow merge process since I'd like to fix log message. Normally you don't need to close your pull request when merged. Sorry for the inconvenience.

**Comment by darionyaphet** [comment]
@HeartSaVioR  thank you  ~

**Pull request closed without merging**
