### PR TITLE
[STORM-2690] resurrect invocation of ISupervisor.assigned() & make Supervisor.launchDaemon() accessible

### PR DESCRIPTION
**Pull request by erikdw**
This commit fixes the storm-mesos integration for the interaction between the Storm core's Supervisor daemon and the MesosSupervisor that implements the ISupervisor interface.

### CODE REVIEW

**Comment by erikdw** [comment]
@revans2 : can you please review this when you have a chance?  Notably we mostly need this back in the [1.0.x-branch](https://github.com/apache/storm/tree/1.0.x-branch), since (as [we discussed](https://github.com/mesos/storm/issues/222#issuecomment-352514556)) storm 1.1+ is fundamentally incompatible with storm-mesos at this point.

**Comment by ptgoetz** [comment]
+1

@erikdw Are you planning to port to earlier branches?

**Comment by erikdw** [comment]
@ptgoetz : yep!  I've been testing on `1.0.x-branch`.  I can send PRs for all the active main branches (`1.0.x-branch`, `1.1.x-branch`, `1.x-branch`).

**Comment by ptgoetz** [comment]
@erikdw Excellent! Thanks bringing this up and helping solve the issue.

**Comment by erikdw** [comment]
@ptgoetz : I've created PRs for the branches:
* [`1.0.x-branch`](https://github.com/apache/storm/pull/2470)
* [`1.1.x-branch`](https://github.com/apache/storm/pull/2471)
* [`1.x-branch`](https://github.com/apache/storm/pull/2472)

**Pull request merged**
