### PR TITLE
STORM-1009:Link on http://storm.apache.org/documentation/Kestrel-and-…

### PR DESCRIPTION
**Pull request by jayapriya90**
…Storm.html is wrong

### CODE REVIEW

**Comment by hustfxj** [comment]
+1

**Comment by revans2** [comment]
@jayapriya90 sadly the documentation was moved to the asf-site branch, but the old docs were not removed from the master branch.  Could you update your pull request to be against that branch instead?

I am +1 on the change.

**Comment by jayapriya90** [comment]
@hustfxj  and @revans2 Thanks for the review and update. I created new pull request #882 for asf-site branch. 

I've also noticed in asf-site branch that auto-generated html files are not ignored. So when I made this change, there were lots of unrelated changes to html files. In previous master branch, auto generated html files were ignored. Should we do the same for asf-site branch as well? If so, I can create a JIRA for that.

**Comment by wuchong** [comment]
Maybe we should close this PR as the new same pull request #882 have been created.

**Comment by jerrypeng** [comment]
can we close this dup PR now?

**Pull request merged**
