### PR TITLE
STORM-2621: add tuple_population metric

### PR DESCRIPTION
**Pull request by revans2**
also fix the sojourn_time metric by using the new one.

### CODE REVIEW

**Comment by revans2** [comment]
I ran some performance tests and the extra overhead is minimal.

**Comment by HeartSaVioR** [comment]
+1

In master branch we could try replacing AtomicLong with LongAdder for metrics, but I'd rather see Metrics V2 first and do the change after that.

**Comment by HeartSaVioR** [comment]
@revans2 Isn't this patch related to STORM-2621 instead of STORM-2557? Just would like to clarify.

**Comment by HeartSaVioR** [comment]
@revans2 Kindly reminder.

**Comment by revans2** [comment]
@HeartSaVioR Sorry I have been out on vacation.  Yes you are correct I copies and pasted the wrong thing.  This is a fix for an issue caused by STORM-2557.  I will update the  pull request and commit message.

**Comment by revans2** [comment]
I rebased it and amended the commit message.  @HeartSaVioR  if you want to take a look again I would appreciate it, but the rebase was automatic.

**Comment by HeartSaVioR** [comment]
Thanks for updating. +1 again.

**Pull request merged**
