### PR TITLE
Update FluxBuilder.java - buildTopology() public access modifier

### PR DESCRIPTION
**Pull request by lyonbrw**
Add public access modifier to buildTopology().

### CODE REVIEW

**Comment by ptgoetz** [comment]
+1

**Comment by lyonbrw** [comment]
Sweet. Thanks. Which release will this be applied to?

**Comment by HeartSaVioR** [comment]
+1, too.

**Comment by HeartSaVioR** [comment]
@lyonbrw 
I'd like to add you as contributor to README.md. 
Could you let me know your name or nickname, or file a new issue to JIRA? Thanks!

**Comment by lyonbrw** [comment]
Brendan W. Lyon

Updated profile. Thanks!

**Comment by HeartSaVioR** [comment]
Merged into master and 0.10.x-branch. 
(Flux has been introduced from 0.10.0-beta1, so I think bugfix or small improvement could be merged to 0.10.0.)

Currently there's sync issue between ASF repos and Github mirror. 
After mirror catches up ASF, it will be marked as merged.

**Comment by lyonbrw** [comment]
Excellent.

**Pull request merged**
