### PR TITLE
[STORM-958] adds config for group.mapping.service init params

### PR DESCRIPTION
**Pull request by d2r**
Users can provide optional parameters to the plugin in the form of a Map.

### CODE REVIEW

**Comment by harshach** [comment]
+1

**Comment by vesense** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1.

**Comment by HeartSaVioR** [comment]
@d2r 
Btw, could you please write some descriptions to document or conf/defaults.yaml?
If I were just a user of Storm, I couldn't understand what this field is for, and/or how to use it.

**Comment by d2r** [comment]
> Btw, could you please write some descriptions to document or conf/defaults.yaml?
> If I were just a user of Storm, I couldn't understand what this field is for, and/or how to use it.

@HeartSaVioR Thanks, yes, I'll do that and update this PR.  Is it sufficient to expand the Java comment in Config.java?  I think this is typically where we put config documentation.

**Comment by HeartSaVioR** [comment]
@d2r Yes, I also think it is enough to put comment to Config.java for now.
If we agree it's not enough to explain configuration, whole of things should be documented to static html page of web site.

**Comment by d2r** [comment]
@HeartSaVioR: updated

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
