### PR TITLE
STORM-1724 Fill up lacking contents to Metrics documentation

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Please keep in mind while reviewing that this is written by not native and good writing skill for English.
So you may want to correct many places which are wrong or weird use of vocabulary, grammar, nuance, and so on.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
And please note that this doesn't represent current porting state (so 1.x and master could be same.)  I guess we should clear up documentation when porting is done.

**Comment by HeartSaVioR** [comment]
Could anyone take a look?

**Comment by harshach** [comment]
+1. This looks great.

**Comment by HeartSaVioR** [comment]
@harshach Thanks for reviewing! I'll merge and reflect the website.

**Pull request merged**
