### PR TITLE
STORM-1283: port backtype.storm.MockAutoCred to java

### PR DESCRIPTION
**Pull request by abhishekagarwal87**

### CODE REVIEW

**Comment by redsanket** [comment]
+1

**Comment by unsleepy22** [comment]
+1

**Comment by hustfxj** [comment]
+1

**Comment by revans2** [comment]
Please move MockAutoCred from `src/jvm/org/apache/storm` to `test/jvm/org/apache/storm`.  The test still passes, and it was only put in the src directory because of problems with compiling clojure vs interpretation.

After that I am +1

**Comment by revans2** [comment]
@abhishekagarwal87 actually I'll just do it as part of the check-in.  There is no code change so it should be fine.

**Comment by abhishekagarwal87** [comment]
Thanks @revans2

**Pull request merged**
