### PR TITLE
[STORM-1469] Remove SimpleTransportPlugin and configuration

### PR DESCRIPTION
**Pull request by kishorvpatil**
This pull request awaits merging in #1173

### CODE REVIEW

**Comment by revans2** [comment]
Please rebase

**Comment by revans2** [comment]
+1

**Comment by revans2** [comment]
oops I missed that org.apache.storm.security.auth.auth-test / testname: digest-authentication-test is failing thinking that it want plane.

**Comment by abhishekagarwal87** [comment]
@kishorvpatil can you rebase it? Also, I see that default transport plugin in 1.x is still SimpleTransportPlugin even though it is deprecated. Is it intended?

**Comment by kishorvpatil** [comment]
@abhishekagarwal87 I supposed we did not merge this PR in time. I think we should change default plugin to `PlainSaslTransportPlugin`. Let me upmerge this.

**Comment by antoinetran** [comment]
Hi,

This has not been merged yet in storm official repository, but it is in forked kishorvpatil repository. Is this normal? Is travis blocking this? Thank you.

**Pull request closed without merging**
