### PR TITLE
[STORM-2194]  Stop ignoring socket timeout error from executor

### PR DESCRIPTION
**Pull request by ppoulosk**
This is a translation of the fix recommended by @revans2 here:

https://github.com/apache/storm/pull/1767

### CODE REVIEW

**Comment by revans2** [comment]
+1 although I really would like to see someone else review this too.

Also the test failure is unrelated.

**Comment by kishorvpatil** [comment]
LGTM. +1.

**Comment by jerrypeng** [comment]
+1

**Comment by HeartSaVioR** [comment]
+1

**Pull request merged**
