### PR TITLE
[STORM-1610] port pacemaker_state_factory_test.clj to java

### PR DESCRIPTION
**Pull request by hustfxj**

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
You can put 
```
PaceMakerClientProxy clientProxy = new PaceMakerClientProxy(response, null);
PaceMakerStateStorage stateStorage = new PaceMakerStateStorage(clientProxy, null);
```
in a method annotated with @Before of Junit and declare stateStorage as global variable.

**Comment by satishd** [comment]
@abhishekagarwal87 @hustfxj 
I do not think @Before annotation can be used here as it needs to create storage for different HBServerMessageType instances in test methods.

You may want to extract methods like below and use it in respective test methods.  
``` java
public PaceMakerStateStorage createPaceMakerStateStorage(HBServerMessageType messageType) {
  return createPaceMakerStateStorage(createPaceMakerStateStorage, null);
}

public PaceMakerStateStorage createPaceMakerStateStorage(HBServerMessageType messageType, HBMessageData messageData) {
  HBMessage response = new HBMessage(messageType, messageData);
  PaceMakerClientProxy clientProxy = new PaceMakerClientProxy(response, null);
  PaceMakerStateStorage stateStorage = new PaceMakerStateStorage(clientProxy, null);
```

**Comment by abhishekagarwal87** [comment]
@satishd I missed that. +1 to what you have suggested

**Comment by knusbaum** [comment]
+1 LGTM

**Comment by zhuoliu** [comment]
+1

**Comment by hustfxj** [comment]
@zhuoliu @satishd @knusbaum @abhishekagarwal87  Thank you. I have addressed your comments.

**Comment by satishd** [comment]
+1 LGTM

**Comment by abhishekagarwal87** [comment]
+1

**Comment by hustfxj** [comment]
@zhuoliu  if  it's ok, can you merge it ?

**Comment by zhuoliu** [comment]
still +1, sure

**Pull request merged**
