### PR TITLE
[STORM-2480] principle should be modified to principal

### PR DESCRIPTION
**Pull request by liu-zhaokun**
[https://issues.apache.org/jira/browse/STORM-2480](url)
As "principal" could be right in kerberos, "principle" should be modified to "principal".

### CODE REVIEW

**Comment by liu-zhaokun** [comment]
Hello, @HeartSaVioR 
Are you available to help me review this PR?

**Comment by liu-zhaokun** [comment]
Hello, @vesense 
Are you available to help me review this PR?

**Comment by liu-zhaokun** [comment]
@HeartSaVioR 
I am so sorry to bother you,could help me to check this PR?

**Comment by liu-zhaokun** [comment]
@vesense 
I am so sorry to bother you,could help me to check this PR?

**Comment by vesense** [comment]
+1

**Comment by liu-zhaokun** [comment]
Hi, @vesense long time no see.How are you?
Thanks for your reply,but also will trouble you to help me merge it.

**Comment by vesense** [comment]
Merged, and I added you to the contributors list.

**Comment by liu-zhaokun** [comment]
@vesense 
Will I find my name [here](http://storm.apache.org/contribute/People.html)

**Pull request merged**
