### PR TITLE
STORM-1573 (1.x): Add batch support for MongoInsertBolt

### PR DESCRIPTION
**Pull request by vesense**

### CODE REVIEW

**Comment by vesense** [comment]
master: https://github.com/apache/storm/pull/1230

**Comment by HeartSaVioR** [comment]
+1
Could you rebase these three commits? After rebasing I'll merge.

**Comment by vesense** [comment]
@HeartSaVioR Done. rebased both master and 1.x-branch.

**Comment by HeartSaVioR** [comment]
+1 Thanks for the patch.

**Pull request merged**
