### PR TITLE
[STORM-1921] Update parallelism_hint date type to integer

### PR DESCRIPTION
**Pull request by darionyaphet**
[STORM-1921](https://issues.apache.org/jira/browse/STORM-1921)

Update TopologyBuilder's parallelism_hint date type from Number to integer .

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@darionyaphet 
Could you rebase this to current master so that CI can test the pull request correctly? Thanks in advance!

**Comment by darionyaphet** [comment]
Hi @HeartSaVioR 

I should running `git rebase master` ?

**Comment by HeartSaVioR** [comment]
Yes please update your master branch to recent version, and git rebase master from STORM-1921 branch, and push STORM-1921 branch with --force option.

**Comment by darionyaphet** [comment]
@HeartSaVioR done !  travis ci started and working .

**Pull request closed without merging**
