### PR TITLE
Storm 1924: Adding conf options for Persistent Word Count Topology

### PR DESCRIPTION
**Pull request by csivaguru**

### CODE REVIEW

**Comment by harshach** [comment]
@csivaguru can you update the commit messages there it looks like an internal bug-id in the message. Please add the STORM-1924 in the commit message .

**Comment by csivaguru** [comment]
@harshach I have updated the PR to fix the commit message.

**Comment by harshach** [comment]
+1

**Comment by harshach** [comment]
Thanks @csivaguru merged into 1.x-branch and master.

**Pull request merged**
