### PR TITLE
[STORM-1479] use a simple implemention for IntSerializer

### PR DESCRIPTION
**Pull request by vesense**

### CODE REVIEW

**Comment by arunmahadevan** [comment]
Changes looks good. But wonder why isn't there a corresponding IntDeserializer?

**Comment by vesense** [comment]
@arunmahadevan 
This class is used by StormSQL.
>In StormSQL data is represented by external tables. Users can specify data sources using the CREATE EXTERNAL TABLE statement.
* kafka as data source
use XXXSerializer for data ser.
* kafka as data sink
use `org/apache/storm/spout/MultiScheme.java` for data deser.

**Comment by arunmahadevan** [comment]
MulitScheme implementations appear to deserialize raw bytes or String, not Integer.

**Comment by revans2** [comment]
+1 looks OK to me.

**Pull request merged**
